### ISSUE TITLE
Elastic 8.7

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#10059]

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion/commit/b6b49c876b74834c558f538a6791b54e0498865a

https://github.com/Security-Onion-Solutions/securityonion/commit/91c990e30a9290f12112d257ef0914276d57b37f

**Comment by dougburks** [comment]
Tested and verified.
