### ISSUE TITLE
pcap agent check-in interval

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1012]
Currently, the pcap agent check-in interval is set at 10 seconds. For eval and standalone installations, we should be able to drop that down to 1 second. For large enterprise deployments of thousands of sensors, we might need to increase that up to 60 seconds. So perhaps for distributed deployments, we continue defaulting to 10 seconds, but allow the user to tune if necessary?

**Comment by jertel** [comment]
This is implemented for RC1.
