### ISSUE TITLE
FIX: Exclude System logs from Hunt/Dashboard Queries.

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion#10122]
Hunt and Dashboards interfaces return SOC server and elastic_agent (Parsing Failures) logs when hunting or correlating on data. Recommend adding a toggle to exclude/include system logs from queries similar to case data.

**Comment by bryant-treacle** [comment]
Enabling this feature could break pivoting from the Error message in SOC to Hunt

**Comment by dougburks** [comment]
Tested and verified:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/6debe7eb-647f-4082-bd39-af1e2a5dece8)
