### ISSUE TITLE
FIX: Overview Customization link

### ISSUE THREAD

**Issue by j-bernal** [Security-Onion-Solutions/securityonion#10173]
Update the link on the SOC Overview page so that when a user clicks "Config" under the Customize This Space section it takes them directly to the Overview Page settings in the Configuration interface. Path to settings for fix below.

/#/config/soc/files/soc/Overview_Page

**Comment by dougburks** [comment]
Tested and verified:
![image](https://user-images.githubusercontent.com/1659467/233485063-990b42ac-8684-45fb-baa9-c2269f500860.png)

Clicking the Config link takes you directly to the Overview Page section of Grid Configuration:
![image](https://user-images.githubusercontent.com/1659467/233485123-2c729643-0737-4efc-badb-7bc379d4a721.png)
