### ISSUE TITLE
FIX: Update IDH Opencanary Modules to indicate they only apply to IDH nodes

### ISSUE THREAD

**Issue by j-bernal** [Security-Onion-Solutions/securityonion#10170]
Update the IDH Opencanary module(s) note to indicate that enabling the module will only affect an IDH node. Example below:

To enable this opencanary module, set this value to true. To disable set to false. This action only applies to IDH nodes within your grid.

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/11297

**Comment by MDCAllan** [comment]
+1 on this... I'm trying to set up an IDH and its not obvious whether it should be enabled at the grid level or the node level.
