### ISSUE TITLE
Linux wazuh agents failing to connect to SO

### ISSUE THREAD

**Issue by ll3N1GmAll** [Security-Onion-Solutions/securityonion#10294]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/10293

<div type='discussions-op-text'>

<sup>Originally posted by **ll3N1GmAll** May  6, 2023</sup>
SO version 2.3.240
All windows clients are reporting in successfully
One Linux client is reporting is successfully
All endpoints have their firewalls open for both protocols and in both directions to the SO standalone server
The one Linux client that is reporting in looked like this when registering:
```
2023/05/06 00:22:34 agent-auth: INFO: Started (pid: 387133).
2023/05/06 00:22:34 agent-auth: INFO: Starting enrollment process to server: SO_IP
2023/05/06 00:22:34 agent-auth: INFO: Connected to SO_IP:1515
2023/05/06 00:22:34 agent-auth: INFO: Registering agent to unverified manager.
2023/05/06 00:22:34 agent-auth: INFO: No authentication password provided.
2023/05/06 00:22:34 agent-auth: INFO: Using agent name as: <CLIENT_HOSTNAME>
2023/05/06 00:22:34 agent-auth: INFO: Request sent to manager
2023/05/06 00:22:34 agent-auth: INFO: Waiting for manager reply
2023/05/06 00:22:34 agent-auth: INFO: Received response with agent key
2023/05/06 00:22:34 agent-auth: INFO: Valid key created. Finished.
2023/05/06 00:22:34 agent-auth: INFO: Connection closed.
```
The remaining Linux clients that appear to register successfully, but that are not reporting in, even after restarting the wazuh-agent, look like this:
```
2023/05/06 00:09:43 agent-auth: INFO: Started (pid: 5984).
2023/05/06 00:09:43 agent-auth: INFO: Requesting a key from server: SO_IP
2023/05/06 00:09:43 agent-auth: INFO: No authentication password provided
2023/05/06 00:09:43 agent-auth: INFO: Using agent name as: <CLIENT_HOSTNAME>
2023/05/06 00:09:43 agent-auth: INFO: Waiting for server reply
2023/05/06 00:09:43 agent-auth: INFO: Valid key received
```

The Linux clients look like they are registering and I can see them listed on SO when SSH'd in in the list of registered agents. I am not sure why they are not working, even though they look like they have registered properly.</div>

**Comment by TOoSmOotH** [comment]
Please use the discussion post

**Comment by ll3N1GmAll** [comment]
Sorry, I used the link the duplicate it here because it was offered in the discussion on the right hand side and it has been nearly a day without any responses to the discussion post. Have you seen this behavior before?

**Comment by ll3N1GmAll** [comment]
That makes sense. I wasn't complaining about the time that passed. I was just explaining why I clicked the button provided to open an issue along with the discussion. Since it was provided on the page, I wasn't sure if that was supposed to be a part of the standard process or not. Sorry for opening a duplicate post. I just misunderstood the purpose behind having the "create an issue" button on the side of the discussion post. I just wanted to make sure I wasn't unnecessarily reducing visibility by not availing myself of the tools that were provided to me on the original discussion page.
