### ISSUE TITLE
FIX: Influxdb Elasticsearch cells showing duplicate data.

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion#10336]
Fixes for the following Influxdb cells:
 Elasticsearch Storage Size &  Elasticsearch Document Count

1. Add hostFilter statement to both queries:
```
hostFilter = (tables=<-) =>
  if v.Host != "(All)" then
    tables |> filter(fn: (r) => r["host"] == v.Host)
  else
    tables
```
2. Add the following filters to both queries: 
```
  |> filter(fn: (r) => r["host"] == r["node_name"])
  |> hostFilter()

```

**Comment by jertel** [comment]
Verified working correctly on 2.4/dev
