### ISSUE TITLE
Grafana/Telegraf - Dynamically read/update disk size

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#1034]
Looks like the disk size calculation for `/nsm` is only read/updated during install, and not update at any other point.  If the disk is expanded or modified in any way with regard to size, we should be able to pick up the value on the fly and calculate reliable metrics.

**Comment by TOoSmOotH** [comment]
We changed the graphs in 2.3.21 so this doesn't apply any more.
