### ISSUE TITLE
Move Wazuh to /nsm/wazuh

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1035]
Wazuh is currently in `/opt/so/wazuh`. If somebody has lots of Wazuh agents and logs, they might end up filling the root partition. We should consider moving Wazuh to `/nsm/wazuh`.

We might also consider having symlinks as follows:
```
/opt/so/rules/hids/ruleset --> /nsm/wazuh/ruleset/
/opt/so/rules/hids/local_rules.xml --> /nsm/wazuh/etc/rules/local_rules.xml
/opt/so/conf/wazuh --> /nsm/wazuh/etc/
```

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/1100/commits/958ee25f6db4c11124b2b2d3629b9ad4e3a9bded

TODO:

- [ ]  /opt/so/rules/hids/ruleset --> /nsm/wazuh/ruleset/
- [ ] /opt/so/rules/hids/local_rules.xml --> /nsm/wazuh/etc/rules/local_rules.xml
- [ ] /opt/so/conf/wazuh --> /nsm/wazuh/etc/

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/commit/88ffd0c17c0002a021f7d8c12e2d76ba7e974a97
