### ISSUE TITLE
UPGRADE: FleetDM 4.31.1

### ISSUE THREAD

**Issue by InfosecGoon** [Security-Onion-Solutions/securityonion#10379]
Issue to upgrade FleetDM, per @defensivedepth as a response to Discussions issue 10372.

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion-image/pull/394

**Comment by dougburks** [comment]
Tested and verified:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/19451e39-5e92-4ae5-9eae-3b1ff8c0c964)
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/43b4e11b-1e6e-4dec-8eec-b5067f121cb4)
