### ISSUE TITLE
so-import-pcap: use hostname in hyperlink when necessary

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1039]
Scenario:
- build a machine and choose to use hostname to access
- run so-import-pcap
- hyperlink at end of so-import-pcap will use IP address instead of hostname

Can so-import-pcap determine if the user chose to use hostname instead of IP and build the hyperlink appropriately?

**Comment by jertel** [comment]
I spoke with Mike on this and he stated that the BASEURL var that controls the external facing host/ip value is not available on the sensor node, which is where this script will be run. I'm assigning this to @m0duspwnens for this input, as an RC2 improvement.
