### ISSUE TITLE
FEATURE: Allow import of PCAP and EVTX via SOC UI

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#10413]
Currently the command line tool `so-import-pcap` and `so-import-evtx` allow you to import events after SSH'ing into the node. To make this easier for new users, allow files to be uploaded to the SOC web UI.

Some considerations:
- What will the max allowed file size be?
- Should the import be synchronous or async?
- Should the user get a report back showing how many events were import, how many failed, etc?
- Where at on the SOC UI will the user perform this operation?
- Will imports be re-importable, by retaining the uploaded file on the server and showing recently uploaded files to re-import?
- Import files will likely need to be cleaned up due to disk space concerns.
- Security to prevent bad file contents or filenames from doing something unexpected.

**Comment by dougburks** [comment]
Tested and verified with both pcap and evtx files:

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/e4cd8ae5-bc89-4789-9a07-8e3d0774420f)

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/da682bb9-8f8f-4cd7-822c-f558f9643ae6)
