### ISSUE TITLE
so-import-pcap: include tags in hyperlink query

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1043]
If you import a pcap from a day where we have live production data as well, then using the resulting hyperlink will show both import data and live data. We should update the so-import-pcap hyperlink so that it restricts the query to logs with `tags:"import"` as follows:
```
* AND tags:"import" | groupby event.module event.dataset
```

**Comment by dougburks** [comment]
Another issue that we might run into is importing multiple pcaps that have overlapping date ranges. So to take this a step further, we could add an additional tag on the initial import for the hash of the pcap and then have the hyperlink include that tag in the search. 

For example, if the pcap hash was `deadbeefdeadbeefdeadbeef`, all logs for that pcap would be tagged as both `import` and `deadbeefdeadbeefdeadbeef` and the resulting hyperlink might pass the following query to Hunt:
```
* AND tags:"deadbeefdeadbeefdeadbeef" | groupby event.module event.dataset
```

**Comment by jertel** [comment]
This is now implemented by using a default import hyperlink with the `import.id:<hash>` filter applied.
