### ISSUE TITLE
Add option to skip generating `root_pem` into osquery launcher.flags

### ISSUE THREAD

**Issue by lafriks** [Security-Onion-Solutions/securityonion#10487]
Currently there is no way to disable adding `root_pem` line into `launcher.flags` when osquery packages are generated.

We use custom so-nginx SSL certificate that is trusted but as generating packages for installation intca is anyway added in launcher.flags root_pem flag, osquery fails to connect to fleet

**Comment by defensivedepth** [comment]
2.3 is now EOL.
