### ISSUE TITLE
Support "Import PCAP" setup mode

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1049]
This is a new Setup mode for users to select when they only plan to use Import PCAP. This will be similar to eval but with the following changes:

- No running Zeek process
- No running Suricata process
- No running Stenographer process

The point is to minimize system requirements for users that have no intention of utilizing a big portion of Security Onion. Check with Doug to determine what else needs to be disabled. Ex:

- Playbook?
- TheHive?
- Cortex?
- Wazuh?
- Grafana/Influx/Telegraf?
- Strelka?
- Soctopus?
- Redis?
- Elastalert?
- MySQL?

Need to ensure so-status is updated, and document this mode so that users understand why the links in SOC aren't working for those disabled products.

**Comment by dougburks** [comment]
In 16.04, so-import-pcap-configure disables many services and minimizes the other services:
https://github.com/Security-Onion-Solutions/securityonion-elastic/blob/master/usr/sbin/so-import-pcap-configure
