### ISSUE TITLE
FIX: Setup re-runs when SSH'ing into a successfully installed minion node

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#10498]
I have a successfully connected manager + search + sensor grid. All functions are working as expected, and the grid is healthy across all nodes. I then SSH'd into the sensor and was told that setup appears to have been previously run.
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/16639611/7a3b05d3-88b7-4b55-8ff7-689f31c633c1)

The initial setup should prevent setup from running on subsequent logins.

**Comment by dougburks** [comment]
Semi-related:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/0c90a262-a182-4db9-af7f-682f78843676)

**Comment by dougburks** [comment]
Tested and verified.
