### ISSUE TITLE
Getting Trusted CA error when installing agent

### ISSUE THREAD

**Issue by OzzyKampha** [Security-Onion-Solutions/securityonion#10544]
Im getting not trusted CA when installing the agent using the downloaded package from SOC.
Is there an easy way to extract the CA cert from SOC to deploy it elsewhere.

Or maybe ship the CA cert with the packages, and install with the agent binary

**Comment by defensivedepth** [comment]
Dupe of https://github.com/Security-Onion-Solutions/securityonion/discussions/10529
