### ISSUE TITLE
FEATURE: Supported Integrations

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#10590]
First cut for out of box support for the following Elastic Integrations:

- [x] AWS
- [x] Azure
- [x] Cloudflare 
  - [x] regular
- [x] FIM
- [x] Github
- [x] Google Workspace
- [x] 1Password

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/10655
