### ISSUE TITLE
Ensure whiptail freeform inputs are validated

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1065]
- Ensure expected integers are indeed integers.
- Ensure min/max bounds checks are executed on numeric entries
- Ensure string min/max lengths are validated

**Comment by rwwiv** [comment]
Also include validation for:
* IP addresses / CIDR notation
* any other fields that need it

**Comment by rwwiv** [comment]
Candidate fields for validation:
- Manager IP address
- Suricata/Zeek processes (integer, more limits likely)
- Sniffing MTU
- New admin user
- Fleet user
- SOC/Fleet/TheHive user
- Fleet FQDN
- ES close threshold (days)
- Dockernet (/24 range without suffix)
- Helix API key
- Home subnet (comma separated CIDR notation) - manager/sensor
- Elasticsearch storage allocation (GB)
- DNS servers (comma separated single ip)
- DNS search domain
- Gateway
- IP address
- Subnet bit mask
- Manager host name (validation already in place, standardize?)
- ES cluster name
- ES heap size (<int>m)
- LS heap size (<int>m)
- LS pipeline workers (int <= number of cores)
- LS pipeline batch size (int, other limits possible?)
- LS input threads (int, possibly tied to core count)
- ET Pro/oinkcode (string)
- Patch schedule name
- Patch schedule import (would be nice to populate an array from the manager and present this as a radio list)
- Host name
- SOC access "OTHER" (hostname, ip, or FQDN)
- ES shard count (int, possibly other limits)
- so-allow (single ip or CIDR notation)

**Comment by jertel** [comment]
Consider:
- non-negative values
- freeform string max lengths

Try to break it!
