### ISSUE TITLE
Clean variables.txt from /tmp on ISO install

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#1067]
Due to how systemd now handles /tmp files,  the files don't get cleaned out after reboot. This leaves artifacts that contain user information and password for the box in a file called variables.txt.

**Comment by TOoSmOotH** [comment]
The install now removes the variables.txt at the end of the first stage install. For existing installs we are removing this file.

**Comment by TOoSmOotH** [comment]
https://github.com/Security-Onion-Solutions/securityonion/commit/74faab92ab7c786e8b93e1b1d7423efabc958f18

**Comment by TOoSmOotH** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/1069

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/07/security-update-for-security-onion-20.html
