### ISSUE TITLE
Remove temporary values from static.sls

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1068]

**Comment by TOoSmOotH** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/1069/commits/b9e6ddf7df5acba5e222b96fdcd8798686dbf38e

**Comment by TOoSmOotH** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/1069

**Comment by dougburks** [comment]
Published:
https://blog.securityonion.net/2020/07/security-update-for-security-onion-20.html
