### ISSUE TITLE
UPGRADE: so-registry docker image

### ISSUE THREAD

**Issue by albix** [Security-Onion-Solutions/securityonion#10727]
Hi folks,

I'm running SO version 2.3.260 and my CVE scanner trivy kindly reports some CVEs in the so-registry docker image. While digging into the issue, I found that `ghcr.io/security-onion-solutions/registry:latest` didn't get an update since "almost 2 years ago". As a workaround I replaced the image with the lastest version found on [docker hub](https://hub.docker.com/_/registry). But this isn't update safe and requires me extra work I'd like to avoid.

Is there a way that you ship the latest known release of https://hub.docker.com/_/registry with every new version you make?

Thanks for the awesome work!

Best, Christian

PS. some numbers
```
ghcr.io/security-onion-solutions/registry:latest (alpine 3.11.12)

Total: 21 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 18, CRITICAL: 1)
```

vs.

```
registry:latest (alpine 3.18.2)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

**Comment by TOoSmOotH** [comment]
Updated to latest
