### ISSUE TITLE
Fleetdm showing hosts as offline, including the manager

### ISSUE THREAD

**Issue by Pencat89** [Security-Onion-Solutions/securityonion#10733]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/10724

<div type='discussions-op-text'>

<sup>Originally posted by **Pencat89** July 10, 2023</sup>
I'm installing a new SO on ubuntu server 20.04.6 LTS.
Fleetdm was working to a point, then it stopped working shortly after I joined a search node in.
Looked at the documentation, checked the logs (sudo docker logs so-fleet), and not giving any information. Running SO 2.3.260.
Tried disabling ufw and made no difference.

Any ideas on where to start troubleshooting?</div>

**Comment by Pencat89** [comment]
I just reinstalled again and same problem. As soon as your reboot after install, it loses connection

**Comment by dougburks** [comment]
Please keep all discussion in Discussions.
