### ISSUE TITLE
FIX: Intermittent pcap retrieval

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#10750]
My normal workflow:
- go to our SOC Alerts page
- drill into an alert aggregation to see individual alerts
- pick an individual alert and click to get Action menu
- right-click PCAP and open in new tab
- while that PCAP is retrieving, go back to step 1

This allows me to investigate several alerts while PCAP retrieval happens in the background. However, most of the time, there will be at least one PCAP retrieval that hangs here:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/fc76cad9-cf7b-4ffa-b57d-f1cf4de78d31)

I've tried waiting many minutes but it never displays on its own. Refreshing the page usually results in the pcap displaying.

**Comment by coreyogburn** [comment]
This was caused by a race condition between when we request the job and when we subscribe to job updates sometimes letting those updates slip through. Manual testing was done to verify the completion of the ticket.

**Comment by dougburks** [comment]
Tested and verified.
