### ISSUE TITLE
Create thehive re-init script. 

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#1080]

**Comment by weslambert** [comment]
Script has been created and resides in common tools.  Needs testing.

**Comment by jertel** [comment]
With the changes in 2.3.30 to improve TheHive's installation stability, is this still needed?

**Comment by petiepooo** [comment]
I have a 2.3.21 install where thehive was not initialized correctly, and adding a user succeeds for soc but fails for thehive.  I'd like to try this, but cannot find the mentioned re-init script in any branch.  Can you point me towards it @TOoSmOotH?
