### ISSUE TITLE
Kernel consoleblank is causing whiptail progress screen to appear to hang

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#1084]

**Comment by dougburks** [comment]
Looks like we have `setterm -blank 0` here:
https://github.com/Security-Onion-Solutions/securityonion/blob/dev/setup/so-setup#L121-L123

```
if [ $automated == no ]; then
	setterm -blank 0 >> $setup_log 2>&1
fi
```

Perhaps the `if` is not matching correctly?  Do we even need the `if`? Does `setterm -blank 0` cause problems with automation?
