### ISSUE TITLE
FIX: Dashboards with multiple groupby charts always filter by the first chart's, first groupby field

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#10856]
Given a dashboard with the following query:

```
* | groupby -sankey event.dataset event.category* | groupby -pie event.category | groupby -bar event.module* | groupby event.dataset | groupby event.module* | groupby event.category | groupby observer.name | groupby source.ip | groupby destination.ip | groupby destination.port | groupby destination_geo.organization_name
```

Clicking one of the bars on the `event.module` bar chart brings up a Quick Action menu with links pre-populated with the wrong field. So if you click Include, it will add a filter for the `event.dataset` field instead of the `event.module` field.

The incorrect code is located in hunt.js::handleChartClick(), specifically this line that assumes to use the first field of the first graph:

```
            var chartGroupByField = this.groupBys[0].fields[0];
```

**Comment by dougburks** [comment]
Tested and verified:

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/770a7822-fbf1-4d61-9d9e-b308501c11a5)

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/9f471b5b-eaa4-4524-a806-c3b76c82526c)
