### ISSUE TITLE
FIX: Installation fails to properly identify NIC while running as container

### ISSUE THREAD

**Issue by daniel-widrick** [Security-Onion-Solutions/securityonion#10873]
The network devices on my LXC Ubuntu 20.04 container appear as follows:

```
root@security:~/securityonion# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
27: eth0@if28: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:51:aa:aa brd ff:ff:ff:ff:ff:ff link-netnsid 0
30: eth1@if31: <BROADCAST,NOARP,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc noqueue master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether 00:16:3e:e3:bb:bb brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

The existing functions in ```setup/so-setup``` includes the ```@if28``` part which breaks further detection and configuration.

**Comment by TOoSmOotH** [comment]
We do not support running SO in LXC containers.

**Comment by daniel-widrick** [comment]
Fair enough. The change would add support for proper detection of veth peers on ANY hardware.

Since SO fails to run in containerized environments, the use cases for veth peers rapidly disappears.

**Comment by chrislawso** [comment]
Anyone find or know of any method to workaround this issue? 

I am trying to install in lxc and installer fails when gathering the management ip. Shows
'device "eth0@if133" does not exist. '

/root/sosetup.log shows failing at
| INFO | Gathering the management IP. 
| INFO | ERROR: Could not determine MAINIP or MNIC_IP.

**Comment by daniel-widrick** [comment]
> Anyone find or know of any method to workaround this issue?

I had submitted a pill request for the nic issue. I was able to install in lxc but a bunch of other stuff was broken as well.

The changes I made were to the regex in the setup script. But identifying the nic was not the only unsupported thing under lxc. I gave up on the effort.

**Comment by chrislawso** [comment]
Ok thanks for reply. I was testing to see if any recent changes in lxc and proxmox would allow for successfully operating security onion in a container. I was unable to figure out how to get the PR working https://github.com/Security-Onion-Solutions/securityonion/pull/10874/commits/381348cfc7348cd51f58fe8cf0631f6072e836d9

If you happen to ever get security onion working in a lxc container please lmk. Thanks
