### ISSUE TITLE
FIX: Install Error: so-yara-download failed

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#10880]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/10879

<div type='discussions-op-text'>

<sup>Originally posted by **EddieN17** July 31, 2023</sup>
Hello,

Running SO 2.4.4 beta running the ISO image on a VMWare ESXi VM. I was installing the manager node and got an error after install. My setup has internet access but has to go through a proxy which appears to be the problem with the error. The error is:
```
[ERROR   ] Command '/usr/sbin/so-yara-download' failed with return code: 2
[ERROR   ] stderr: /usr/sbin/so-yara-download: line 8: syntax error near unexpected token `('
[ERROR   ] retcode: 2
[ERROR   ] {'pid': 40845, 'retcode': 2, 'stdout': '', 'stderr': "/usr/sbin/so-yara-download: line 8: syntax error near unexpected token `('\n/usr/sbin/so-yara-download: line 8: `export no_proxy= salt['pillar.get']('manager:no_proxy')'"}
      Result: False
```

Looking at the script in /usr/sbin/so-yara-download and /sbin/so-yara-download, the http_proxy and https_proxy was called for successfully but the no_proxy failed. With my webproxy configuration settings showing in the script.
(Snippet from script)
```
export http_proxy=http://webproxy.redacted:8080
export https_proxy=http://webproxy.redacted:8080
export no_proxy= salt['pillar.get']('manager:no_proxy')
```
 
I modified the script and set `no_proxy=$(salt-call pillar.get manager:no_proxy)` and after that ran `so-yara-download` and all worked well with that. But it would be nice if this script could be fixed through install.

Thanks for all the work with 2.4!</div>

**Comment by EddieN17** [comment]
Removing the space from the text doesn't fix the problem, still get this error:
```
[ERROR   ] Command '/usr/sbin/so-yara-download' failed with return code: 2
[ERROR   ] stderr: /usr/sbin/so-yara-download: line 8: syntax error near unexpected token `('
/usr/sbin/so-yara-download: line 8: `export no_proxy=salt['pillar.get']('manager:no_proxy')'
[ERROR   ] retcode: 2
[ERROR   ] {'pid': 783477, 'retcode': 2, 'stdout': '', 'stderr': "/usr/sbin/so-yara-download: line 8: syntax error near unexpected token `('\n/usr/sbin/so-yara-download: line 8: `export no_proxy=salt['pillar.get']('manager:no_proxy')'"}
```

So I added this to the three different scripts:
```
{%- set noProxy = salt['pillar.get']('manager:no_proxy') %}
export no_proxy="{{ noProxy }}"
```

This seems to fix it as no errors occur when I run  `salt-call state.highstate` (also manually ran `so-yara-download` and `so-rule-update` to confirm)

I had to add the quotes to {{ noProxy }} because without them I would get these messages running the scripts.

```
/sbin/so-yara-download: line 8: export: `127.0.0.1,': not a valid identifier
/sbin/so-yara-download: line 8: export: `172.**.**.**,': not a valid identifier
```

```
/sbin/so-rule-update: line 9: export: `127.0.0.1,': not a valid identifier
/sbin/so-rule-update: line 9: export: `172.**.**.**': not a valid identifier
```

Looking at the scripts in /sbin/ they're properly set in the script:
```
export http_proxy=http://webproxy.redacted:8080
export https_proxy=http://webproxy.redacted8080
export no_proxy="localhost, 127.0.0.1, 172.xx.xx.xxx, manager"
```

**Comment by TOoSmOotH** [comment]
I went ahead and updated the scripts to use the ""
