### ISSUE TITLE
FIX: syslog not working

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#10896]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/10895

<div type='discussions-op-text'>

<sup>Originally posted by **ByteAndBits** August  1, 2023</sup>
OS 2.4 Beta4
Installed from ISO (yeah)
Standalone

Syslog not working. Made the Firewall entry, but nothing happend or show in Dashboard or Elatic.

Its the same syslog source and Hypervisor like for OS 2.3 where it worked perfect.
Syslog sender is in the same network. 

</div>

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/10904

**Comment by dougburks** [comment]
Tested and verified.
