### ISSUE TITLE
Setup on non-manager nodes shouldn't tell the user to try to log into web interface

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1092]
This is from a Search Node installation via 2.0.2 ISO image:
![image](https://user-images.githubusercontent.com/1659467/88426217-d046c280-cdbe-11ea-9a65-0612cfa028d8.png)

Also seeing the same thing on sensor installations via 2.0.2 ISO image.

**Comment by jertel** [comment]
Pushed change.

![image](https://user-images.githubusercontent.com/16639611/90276809-83d92a80-de32-11ea-8a00-8c152698d7f7.png)
