### ISSUE TITLE
TheHive is showing Cortex AUTH_ERROR

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1094]
![image](https://user-images.githubusercontent.com/1659467/88434753-df357100-cdce-11ea-9dc4-17d7d77ff048.png)

**Comment by OzzyKampha** [comment]
Having the same issue

**Comment by presianbg** [comment]
The problem is that there is no `user` which can be used for the integration:
![image](https://user-images.githubusercontent.com/2163486/89302986-38758e00-d674-11ea-8201-77fee0f02b2e.png)

**Comment by weslambert** [comment]
Yes, the issue is that there is no user being added for the SecurityOnion organization (because of an issue with the cortex_init script).  We are working to address it.

**Comment by weslambert** [comment]
Fixed.
