### ISSUE TITLE
FEATURE: Auto-Upgrade Node Agents

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#10949]
Need a way to automatically upgrade Grid Node Elastic Agents during SOUP that has an Elastic upgrade.

**Comment by dougburks** [comment]
Tested and verified.

RC1 before soup:
![Screenshot 2023-08-09 at 2 32 19 PM](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/b8afc2cc-69d4-4b29-bea9-3333f32959a0)

After soup:
![Screenshot 2023-08-09 at 3 18 01 PM](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/46aeee12-e6a1-4d05-ad30-74add11121ef)

**Comment by defensivedepth** [comment]
Fixed with https://github.com/Security-Onion-Solutions/securityonion/pull/10994
