### ISSUE TITLE
FIX: Install screen - Firewall

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#10945]
Modify the whiptail screen for a minion install to point people to the SOC UI to setup firewall access for new minion install

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/954732/703a6351-d9bc-486b-b23d-97999f454035)

**Comment by dougburks** [comment]
Tested and verified:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/1eac2ef7-4283-4dac-8431-772746a14aff)
