### ISSUE TITLE
Not getting alerts in TheHive in distributed mode

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1095]
I'm getting alerts in TheHive in Standalone mode, but not in Distributed Mode.

**Comment by weslambert** [comment]
Need to ensure `suricata_thehive.yaml` and `wazuh_thehive.yaml` search across all clusters:

ex. `*:so-ids-*`

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/1096
