### ISSUE TITLE
FIX: soup may fail while trying to query Fleet server

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#10974]
Looks like ES/Kibana was not ready at that specific moment it tried to query for the needed info. Probably need to add a retry around it.

![Image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/7ed87eb9-c159-4aa3-afde-4c20eed86234)

**Comment by defensivedepth** [comment]
Fixed with https://github.com/Security-Onion-Solutions/securityonion/pull/10994
