### ISSUE TITLE
FIX: Elastic Agents won't upgrade without Internet connection

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#10981]

**Comment by defensivedepth** [comment]
Fixed with https://github.com/Security-Onion-Solutions/securityonion/pull/10994

**Comment by dougburks** [comment]
Tested and verified.

Airgap RC1 before soup:
![Screenshot 2023-08-10 at 9 33 39 AM](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/c9b4cfc3-b987-4cd1-bf04-c40ffe77f7e5)

After soup:
![Screenshot 2023-08-10 at 10 05 19 AM](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/95571cb4-cabf-4139-a479-40545e0eeacd)
