### ISSUE TITLE
Fix: Sysmon Events Table Field Rendering

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion#10985]
Modify windows.sysmon_operational section of the SOC defaults.yaml to render Windows Sysmon events.

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/10986

**Comment by dougburks** [comment]
Tested and verified:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/f0564db2-f889-49b0-92cb-cff68c88a3f3)
