### ISSUE TITLE
FIX: Remove OSSEC and add Playbook mappings for the SOC Alerts Event Table

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion#11015]
Suggest replacing OSSEC mappings with the following Playbook fields in SOC Alerts Event Table.
 
':playbook:':
    - soc_timestamp
    - rule.name
    - event.severity_label
    - event_data.event.module
    - event_data.event.category
    - event_data.process.executable
    - event_data.process.pid
    - event_data.winlog.computer_name

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/11139
