### ISSUE TITLE
FIX: Kibana Elastic Agent Dashboard 404

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#11018]
REF: https://github.com/Security-Onion-Solutions/securityonion/discussions/11017

**Comment by TOoSmOotH** [comment]
Issue in with Elastic

**Comment by James-AAL** [comment]
I am experiencing a similar thing. The agents added successfully but they do not show up in KIbana. They include Elastcic agents and Syslog agents such as the PFsene firewall. These were working well in 2.3.

**Comment by James-AAL** [comment]
Any workaround for now or something I may have not done right?

**Comment by defensivedepth** [comment]
hey there @James-AAL, please start a new Discussion, rather than posting on an Issue.  Thanks!

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/11289
