### ISSUE TITLE
ET PRO Ruleset

### ISSUE THREAD

**Issue by y0d4a** [Security-Onion-Solutions/securityonion#11147]
Hi, in latest version, i want to add etpro ruleset, in configuration i see that i need to enter registration code, ruleset and urls.
I am not aware what kind of URL i need to enter (https://rules.emergingthreatspro.com/$oinkcode/suricata-$version/etpro.rules.tar.gz
 ? )? i got OINK code only...

**Comment by dougburks** [comment]
Instead of creating an issue, please create a discussion:
https://securityonion.net/discuss
