### ISSUE TITLE
FIX: Pre-load Integration Templates

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#11146]
Preload the following integration packages:

auditd
barracuda
cisco_asa
crowdstrike
darktrace
f5_bigip
fortinet
gcp
http_endpoint
httpjson
juniper
juniper_srx
kafka_log
lastpass
m365_defender
microsoft_defender_endpoint
microsoft_dhcp
netflow
o365
okta
panw
pfsense
sentinel_one
sonicwall_firewall
symantec_endpoint
ti_abusech
ti_misp
ti_otx
ti_recordedfuture
zscaler_zia
zscaler_zpa

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/11153

**Comment by hoalex** [comment]
Any chance to add the Pulse Connect Secure integration as well? PCS handles VPN logins, and as such would make a perfect candidate for log ingestion in SO.
