### ISSUE TITLE
use a real-time log analysis & correlation engine in SecurityOnion

### ISSUE THREAD

**Issue by NRGLine4Sec** [Security-Onion-Solutions/securityonion#1116]
Hi,
It is in your roadmap to add the capability of correlation of log in SecurityOnion, with a tool like [Sagan](https://github.com/beave/sagan) ?

**Comment by dougburks** [comment]
Security Onion already includes Wazuh:
https://docs.securityonion.net/en/2.0/wazuh.html

**Comment by NRGLine4Sec** [comment]
But Wazuh is not a correlation engine ?

**Comment by dougburks** [comment]
Wazuh can do correlation via composite rules. For example:
https://documentation.wazuh.com/3.11/learning-wazuh/ssh-brute-force.html

You may also want to look at Playbook and Sigma rules, also already included in Security Onion 2.0:
https://docs.securityonion.net/en/2.0/playbook.html

**Comment by NRGLine4Sec** [comment]
At [log sources](https://docs.securityonion.net/en/2.0/playbook.html#log-sources) there are only osquery, network (via Zeek logs) and Windows Eventlogs + Sysmon (via osquery).
It isn't possible to do it from log from FluentD ?

**Comment by dougburks** [comment]
Security Onion does not include FluentD.

If you have further questions or problems, please post to the community forum:
https://docs.securityonion.net/en/2.0/community-support.html

Thanks!
