### ISSUE TITLE
FIX: so-playbook don't work with proxy environment variables

### ISSUE THREAD

**Issue by albix** [Security-Onion-Solutions/securityonion#11172]
Hi folks,

I'm running SO 2.3.260-20230620 in an environment were I'm forced to use proxy servers. While most tools work just fine with https_proxy and no_proxy settings, so-playbook fills the proxy log with requests.

After some debugging it turns out that the Redmine reverse proxy Passenger may be the root cause. In [passenger-nginx-config-template.erb](https://github.com/Security-Onion-Solutions/securityonion-image/blame/2.3.260/so-playbook/playbook/passenger-nginx-config-template.erb#L33) is `passenger_load_shell_envvars` set to `off`. In my understanding of this [setting](https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_load_shell_envvars) it must be set to `on` (the default). I was digging in your older repos for the reason why you disabled this in the past and had no luck.

It would be awesome to either enable `passenger_load_shell_envvars` or set `passenger_env_var` with `http_proxy`, `https_proxy` and `no_proxy` to make the proxy environment variables work in so-playbook.

Best regards, Christian

**Comment by dougburks** [comment]
We're currently working on a new version of Playbook and so this old Redmine architecture will go away.

If you have further questions or problems, please start a new discussion at https://securityonion.net/discuss
