### ISSUE TITLE
FIX: Elastic Agent - Installation "Not Accessible" Message

### ISSUE THREAD

**Issue by TomGilson** [Security-Onion-Solutions/securityonion#11191]
Elastic-Agent outputs misleading information during install.

OS: Windows 10
Installation Method: Ran Elastic-Agent executable from Powershell, no command options. 
Terminal Output: "Not Accessible" message for Fleet host/IP connection failures during install. Install completed using the 3rd host option.

**Comment by blockanz** [comment]
I have the same issue, but on Windows 11 but can't get a connection.

**Comment by defensivedepth** [comment]
@blockanz This issue is for changing the status message. Please create a Discussion with your issue and we can troubleshoot further.

Thanks!

**Comment by defensivedepth** [comment]
Fixed with https://github.com/Security-Onion-Solutions/securityonion-image/pull/452
