### ISSUE TITLE
facing issue when sending Zeek and IDS logs to another server host using filebeat

### ISSUE THREAD

**Issue by indrajitkalelkar** [Security-Onion-Solutions/securityonion#11194]
Dear Team,

when i was change the host setting and logs parsing setting in filebeat and restart docker container all setting will be revert to base. 

please help how can we edit the filebeat setting and it will be set as permanent.

**Comment by dougburks** [comment]
Instead of creating an issue, please start a new discussion at:
https://securityonion.net/discuss
