### ISSUE TITLE
Add Airgap features

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion#1127]
- [x] Prompt user during install if they are on an airgap network.  May want to place it in the same whiptail screen where the user is prompted if they want to update through the manager or directly from the internet. 
- [x] Acng - Set "Offlinemode: 1" in the acng.conf file on the airgap network
- [x] Acng - Compress the /opt/so/conf/aptcacher-ng/cache/ directory on internet connected manager.  Decompress on airgapped manager and restart so-acng container. 
- [x] IDS rule updates - Similar process as the current platform where it downloads the latest emerging.rules.tar.gz on the internet connected master the transfers the updated file to /opt/emergingthreats/ on the airgapped master and runs rule-update.  
- [x] Docker Registry - Allow users to save the docker images on the manager, transfer those images to the airgapped manager then push to the docker registry.

**Comment by TOoSmOotH** [comment]
ACNG doesn't get used in airgap as the repo is now local to the manager. Need to discuss rules.
