### ISSUE TITLE
UPGRADE: Zeek to 6.0

### ISSUE THREAD

**Issue by stondino00** [Security-Onion-Solutions/securityonion#11280]
https://github.com/zeek/zeek/releases/tag/v6.0.0

**Comment by TOoSmOotH** [comment]
We are already tracking this

**Comment by stondino00** [comment]
Sounds good.  6.0.1 has been released as well.  Thanks

**Comment by dougburks** [comment]
@stondino00 We receive notifications from the Zeek team for new releases (in most cases before the general public does), so there is no need for you to worry about notifying us in the future.
