### ISSUE TITLE
Hunt: Fix Intel groupby

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1131]
The Intel query in Hunt retrieves results but the groupby isn't rendering.

**Comment by dougburks** [comment]
Related to the Kibana Intel additions here:
https://github.com/Security-Onion-Solutions/securityonion/issues/875#issuecomment-667659800

**Comment by jertel** [comment]
Per conversation with Doug this issue reflects the need to update the groupby clause of the hunt query, and does not need changes to the Hunt application.
