### ISSUE TITLE
FIX: so-import-evtx incorrect dates

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#11332]
For some EVTX files, so-import-evtx is swapping the From: and To: dates. Also, even after manually swapping the dates to the proper order, no events are shown in SOC. It appears that the imported EVTX events have the current date stamp instead of the original date stamp.

One example is the EVTX at https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES/blob/master/Execution/rogue_msi_url_1040_1042.evtx:

```
so-import-evtx rogue_msi_url_1040_1042.evtx 
Processing Import: /root/rogue_msi_url_1040_1042.evtx
- assigning unique identifier to import: 92c2e38e2ccb6f94120c44db2f6e61b9
- importing logs to Elasticsearch...

Import complete!

Use the following hyperlink to view the imported data. Triple-click to quickly highlight the entire hyperlink and then copy it into a browser:

https://nachoso/#/dashboards?q=import.id:92c2e38e2ccb6f94120c44db2f6e61b9%20%7C%20groupby%20-sankey%20event.dataset%20event.category%2a%20%7C%20groupby%20-pie%20event.category%20%7C%20groupby%20-bar%20event.module%20%7C%20groupby%20event.dataset%20%7C%20groupby%20event.module%20%7C%20groupby%20event.category%20%7C%20groupby%20observer.name%20%7C%20groupby%20source.ip%20%7C%20groupby%20destination.ip%20%7C%20groupby%20destination.port&t=2019%2F10%2F31%2000%3A00%3A00%20AM%20-%202019%2F03%2F20%2000%3A00%3A00%20AM&z=UTC

or, manually set the Time Range to be (in UTC):

From: 2019-10-31    To: 2019-03-20

Note: It can take 30 seconds or more for events to appear in Security Onion Console.
```

### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/11322

<div type='discussions-op-text'>

<sup>Originally posted by **jwmasekre** September 14, 2023</sup>
### Version

2.4.10

### Installation Method

Security Onion ISO image

### Description

other (please provide detail below)

### Installation Type

Distributed

### Location

on-prem with Internet access

### Hardware Specs

Exceeds minimum requirements

### CPU

8

### RAM

24

### Storage for /

65

### Storage for /nsm

126

### Network Traffic Collection

other (please provide detail below)

### Network Traffic Speeds

1Gbps to 10Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

No, there are no failures

### Logs

No, there are no additional clues

### Detail

Discovered that when importing an EVTX to the manager via the grid page, the date range is swapped on the URL that's generated:
![image001 (5)](https://github.com/Security-Onion-Solutions/securityonion/assets/47164372/0170e033-96e2-4ba9-a6cd-94c12be09ae2)

Does this need to be submitted as an issue? it's minor but should probably be fixed for more junior users.

### Guidelines

- [X] I have read the above statement and can confirm my post is relevant to Security Onion 2.4.</div>

**Comment by dougburks** [comment]
@jwmasekre This may be dependent on the EVTX file itself perhaps due to invalid data in the EVTX file. 

Any chance you are able to share the EVTX file that caused this? 

Also, did you just try to import it once or did you try to import it multiple times? 

Finally, can you try importing https://github.com/sbousseaden/EVTX-ATTACK-SAMPLES/blob/master/Execution/exec_sysmon_1_ftp.evtx and verify that it works as expected?

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/11352
