### ISSUE TITLE
Security onion stuck at "Running post installation scripts

### ISSUE THREAD

**Issue by Raycoug22** [Security-Onion-Solutions/securityonion#11347]
I am trying to install Security onion 2.4 iso file in a virtual machine in workstation pro 17. Whenever it says "running post installation scripts" it stays stuck there and I do not know why.
![3f32fd278c384cb38e2f467d63b071ed](https://github.com/Security-Onion-Solutions/securityonion/assets/145325718/e85db365-95f7-4aa0-901d-28469063fb26)

**Comment by dougburks** [comment]
Instead of creating an issue, please start a new discussion at https://github.com/Security-Onion-Solutions/securityonion/discussions/categories/2-4.
