### ISSUE TITLE
Remove legacy code from soctopus

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1135]

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion-image/pull/24

**Comment by jertel** [comment]
While the primary Strelka-scan logic was removed, Wes believes there might be more code to remove so leaving open.

**Comment by dougburks** [comment]
Remaining code is lower priority, so created https://github.com/Security-Onion-Solutions/securityonion/issues/1214 for that to be removed in RC3.
