### ISSUE TITLE
Allow the use of VPN with setup

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#1139]
The tun interface gets removed during setup. This prevents it from connecting over the VPN connection to register the agent.

**Comment by B3DTech** [comment]
This also applies to gre tunnels and monitor interfaces created for ERSPAN.  If NICs are there, they really shouldn't be touched without approval of the user.  Maybe a screen that pops up asking to select the NICs that are unused and should be disabled?

**Comment by TOoSmOotH** [comment]
Disabling NICs at the end can cause issues for certain VPN types

**Comment by TOoSmOotH** [comment]
This feature will allow Forward nodes to use wireguard to connect to the manager and send events. The wireguard setup will need to be manual and must be set up before running setup.

**Comment by TOoSmOotH** [comment]
Wireguard will only work on Ubuntu. Investigating using openvpn.

**Comment by TOoSmOotH** [comment]
so-setup will now allow you to use VPN starting in 2.3.30

**Comment by petiepooo** [comment]
How does one recover from this?  Both my tun1 and wg0 interfaces were apparently wiped out during install, and I've lost contact with the deployed sensor.  Assuming I can connect via SSH to the admin interface, what will it take to make sure my VPN interfaces are active?  Is a reboot sufficient?

**Comment by EchoGangster** [comment]
This seems to still be an issue.  Had 2.3.40 and upgraded to 2.3.50 last week.  Now trying to setup VPN tunnel for remote sensors and the routes are deleted and new interface is created with he so-setup.  Seems like the script needs a few tweaks.

**Comment by petiepooo** [comment]
@EchoGangster What VPN technology are you using and what were your VPN interfaces named?  They've hard-coded the scripts for iface names starting with 'wg' or 'tun' for now...
