### ISSUE TITLE
FIX: so-salt-minion-check not rendering as jinja

### ISSUE THREAD

**Issue by lnxtxyz** [Security-Onion-Solutions/securityonion#11390]
Hi

The problem, standard 2.4/main manual installation[1]:
every 5 minutes I have got email with error from the `so-salt-minion-check` script:
```
# so-salt-minion-check -q
so-salt-minion-check: line 1: {%: command not found
so-salt-minion-check: line 29: {{SALT_MINION_DEFAULTS.salt.minion.check_threshold}}: syntax error: operand expected (error token is "{{SALT_MINION_DEFAULTS.salt.minion.check_threshold}}")
so-salt-minion-check: line 81: [: -le: unary operator expected
date: invalid date ‘@’
```

I think `so-salt-minion-check` should be in
`salt/common/tools/sbin_jinja/so-salt-minion-check`
directory.

Not:
~`salt/common/tools/sbin/so-salt-minion-check`~
.

[1] https://docs.securityonion.net/en/2.4/installation.html#manual-installation-via-other-iso-image

**Comment by m0duspwnens** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/11393
