### ISSUE TITLE
UPGRADE: NetworkMiner 2.8.1

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#11457]
https://www.netresec.com/?page=Blog&month=2023-10&post=NetworkMiner-2-8-1-Released

**Comment by erik4711** [comment]
Let me know if there's anything I can do to facilitate getting new NetworkMiner releases into SO.

**Comment by dougburks** [comment]
Thanks @erik4711 and congrats on the new release! I'm excited to try out the new extraction features!

**Comment by erik4711** [comment]
@dougburks I wasn't able to find the code for the `securityonion-networkminer` package in this repo.

**Comment by dougburks** [comment]
@erik4711 We'll take care of it, thanks!
