### ISSUE TITLE
FIX: The values for specific nodes in zeek.config.local.load are being populated incorrectly

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion#11472]
When making node-specific changes to zeek.config.local.load settings, the changes are being pushed to the correct minion pillar file but the settings are being populated by the soc_zeek.sls or default pillar values. For example, if I remove a script from the current grid value and refresh the page, the values for the specific node(s) inherit those changes. It does not actually change the minion pillar values, just what is displayed in SOC.

**Comment by m0duspwnens** [comment]
This was fixed for 2.4.20
