### ISSUE TITLE
Grafana - Total Threads always increasing on Standalone

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1147]
On a Standalone deployment, Grafana Total Threads seems to always increase:
![image](https://user-images.githubusercontent.com/1659467/89524669-f7d05e80-d7b2-11ea-9e90-00e0f45611bd.png)

Compare that to a full distributed deployment where Total Threads fluctuates up and down:
![image](https://user-images.githubusercontent.com/1659467/89524784-277f6680-d7b3-11ea-803d-1a5488124f72.png)
![image](https://user-images.githubusercontent.com/1659467/89524798-3108ce80-d7b3-11ea-9bee-5597ba599636.png)
![image](https://user-images.githubusercontent.com/1659467/89524823-39610980-d7b3-11ea-893b-9b226da19993.png)

**Comment by dougburks** [comment]
This may be related to https://www.reddit.com/r/securityonion/comments/iaor6m/20_lots_of_defunct_surilosssh/ and https://github.com/Security-Onion-Solutions/securityonion/issues/31.

**Comment by TOoSmOotH** [comment]
#1229 fixes this. It is related to the reddit issue. I moved it to RC2 since this breaks sensors after running a while.
