### ISSUE TITLE
FEATURE: Additional Supported Integrations

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#11513]
- auth0
- carbonblack_cloud (removing because of semver issue)
- carbonblack_edr
- cisco_duo
- cisco_meraki
- cisco_umbrella
- fireeye
- mimecast
- pulse_connect_secure
- snyk
- sophos
- sophos_central
- tenable_sc

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/11570

**Comment by OzzyKampha** [comment]
Any chance to add check point to that list also?
