### ISSUE TITLE
FEATURE: Additional threat intel support

### ISSUE THREAD

**Issue by hammerrw** [Security-Onion-Solutions/securityonion#11523]
Can you add support for the additional threat intelligence options in the Elastic Agent? 

Anomali
Cybersixgill
Maltiverse
Mimecast
ThreatQuotient

**Comment by weslambert** [comment]
I began tracking the next installment of additional integrations here:

https://github.com/Security-Onion-Solutions/securityonion/issues/11958

**Comment by weslambert** [comment]
Tracking in other issue.
