### ISSUE TITLE
Feature Request: Add "None" as filter option under Fleet/Agents/Tags 

### ISSUE THREAD

**Issue by kvkamin** [Security-Onion-Solutions/securityonion#11577]
After pushing out lots of Elastic Agents to many disparate companies and places, it was easy to find windows hosts to assign policy to by just sorting on endpoints-initial and assigning new policy any hosts found, but when applying Tags, it would be helpful if there was a "None" to find machines that have not been Tagged.

**Comment by dougburks** [comment]
If you're requesting a feature in Elastic Fleet (Kibana), then you should probably submit that to the Elastic Fleet or Kibana teams.

**Comment by defensivedepth** [comment]
@kvkamin You can also run the following query in the KQL query box in the Fleet Management interface. This query pulls up hosts that do not have any Tags.

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/954732/33f6764d-c62a-4410-81ba-88abb45155cf)

**Comment by kvkamin** [comment]
Perfect, thanks!

~K
