### ISSUE TITLE
Web interface keeps on taking too long to respond in Security Onion 2.4

### ISSUE THREAD

**Issue by mjombanorman** [Security-Onion-Solutions/securityonion#11627]
I've noticed that I must restart the Firewalld for Web UI access every time I need to access it. System checks show no issues, but the Web UI remains inaccessible. Any solutions or tips for this?

**Comment by dougburks** [comment]
Instead of creating an issue, please start a new discussion at https://github.com/Security-Onion-Solutions/securityonion/discussions/categories/2-4
