### ISSUE TITLE
navigator calls out to external resources

### ISSUE THREAD

**Issue by jtgreen-cse** [Security-Onion-Solutions/securityonion#1162]
Running 2.0.3-rc.1 airgapped.

Navigator tries to get external resources which makes it fail to load. Understandably you'd want the latest json definitions from Mitre. Perhaps these can be updated using the future offline soup process. I see those resources are already variables in salt, so I imagine you've already envisioned this.

![image](https://user-images.githubusercontent.com/67059096/90041461-5146fa80-dc97-11ea-885d-029ce6906915.png)

**Comment by defensivedepth** [comment]
Closed with https://github.com/Security-Onion-Solutions/securityonion/pull/7362
