### ISSUE TITLE
Introduce RBAC controls to SOC

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1172]
There should be access levels in SOC so that we can restrict access to certain API calls for some users.

As part of this, sensors should be limited to performing a small subset of operations.

**Comment by rwaight** [comment]
Is there still a plan to introduce RBAC to the Security Onion Console (SOC)?  If so, would that also include leveraging RBAC within Kibana/Elasticsearch as well?  

I would be interested to see at least an _analyst_ role and an _administrator_ role, if possible.  I noticed that the [`so-user` script](https://github.com/Security-Onion-Solutions/securityonion/blob/master/salt/common/tools/sbin/so-user#L183-L193) grants every user the `superuser` Elastic role any time a new user is created.  If it makes a difference, I would be interested in helping out with this.

**Comment by jertel** [comment]
Closed in favor of 5614
