### ISSUE TITLE
Assign unique authorization keys per sensor

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1173]
Sensors currently share a single API key when communicating with the SOC API. For an improved security posture there should be a unique key assigned per sensor. This would make it easier to track down which remote sensor may have been compromised, and provide an ability to quickly lock out the compromised sensor instead of locking all sensors out.

It's not yet determined how these keys would be assigned and managed across SOC and the sensors themselves.

**Comment by TOoSmOotH** [comment]
RBAC
