### ISSUE TITLE
FEATURE:  Playbook preview

### ISSUE THREAD

**Issue by Mav1814** [Security-Onion-Solutions/securityonion#11797]
It would be fantastic to have a preview of the playbooks, without having to constantly edit and save to see the preview, or check in activity to see the preview..

Its just a suggestion...

cheers guys!

**Comment by Taraskobilskiy** [comment]
Do you have an idea of the approximate timeframe for the implementation of the new playbook? 1st half of 2024?

**Comment by dougburks** [comment]
@Taraskobilskiy We are hoping for the first half but we can't make any promises. If you have further questions or problems, please start a new discussion at https://securityonion.net/discuss
