### ISSUE TITLE
FEATURE: Carve out the cert_chain_fps value from SSL traffic

### ISSUE THREAD

**Issue by j-bernal** [Security-Onion-Solutions/securityonion#11806]
The cert_chain_fps value can be used to pivot from the SSL dataset to the X.509 dataset. This allows an analyst to view and carve out the certificate from the session. The cert_chain_fps key:value pairing can currently be found in the message field in the ssl dataset.
![ssl dataset message field](https://github.com/Security-Onion-Solutions/securityonion/assets/59663876/7ff490f7-7597-4649-81ee-1144357f01c7)

**Comment by weslambert** [comment]
SSL: 
 - cert_chain_fps -> ssl.certificate.fingerprint|tls.server.hash.sha256|hash.sha256
 - client_cert_chain_fps -> ssl.certificate.fingerprint|tls.client.hash.sha256|hash.sha256

X509: 
 - fingerprint -> x509.certificate.fingerprint|tls.server.hash.sha256|hash.sha256

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/11896
