### ISSUE TITLE
FIX: Update SSL cert to avoid Google Chrome error (2.4)

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#11824]
From https://support.google.com/chrome/a/answer/10314655#117&zippy=%2Cchrome:
> X.509 certificates used for HTTPS should contain a key usage extension that declares how the key in a certificate may be used. Such instructions ensure certificates are not used in an unintended context, which protects against a class of cross-protocol attacks on HTTPS and other protocols. For this to work, HTTPS clients must check that server certificates match the connection's TLS parameters, specifically that the key usage flag for “digitalSignature” and possibly “keyEncipherment” (depending on TLS ciphers in use) are asserted when using RSA.

**Comment by dougburks** [comment]
Tested and verified.

Before:

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/10c85102-3a7e-450c-b4a0-b4458f6534c6)

After:

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/df970dba-539f-4aef-a55e-2e49dcdd97f2)

**Comment by bioteseo** [comment]
Also SO 2.3.270 is affected from this issue

**Comment by ross-tsc** [comment]
@dougburks is this going to be patched into the current 2.3 branch? Not sure how long you're planning on continuing 2.3 hotfix/patches currently? From a brief look if seems like a simple change in one file, so I assume I could patch it myself if needs be?

**Comment by defensivedepth** [comment]
@bioteseo @ross-tsc Yes, this will be fixed in 2.3:

https://github.com/Security-Onion-Solutions/securityonion/issues/11825

**Comment by bicfordio** [comment]
I just upgraded to 2.3.280 and notice the error is still present. Any suggestions for someone dumb like me to patch myself @ross-tsc ? I must not be seeing something obvious in those release notes to make the connection of what specifically I need to change to remediate

**Comment by dougburks** [comment]
@bicfordio This fix was backported to 2.3.280:
https://github.com/Security-Onion-Solutions/securityonion/issues/11825

I verified that it worked in my test deployment without any manual intervention.

If you would like to troubleshoot further, please start a new discussion at https://securityonion.net/discuss and provide detailed information about your deployment and what exactly you're seeing.
