### ISSUE TITLE
FEATURE: Add server reboot notification to SOC 

### ISSUE THREAD

**Issue by cm-ops** [Security-Onion-Solutions/securityonion#11852]
Currently CLI MOTD displays servers needing reboot. Add notification to SOC GUI for servers requiring a reboot.

**Comment by jertel** [comment]
Implemented for next release:

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/16639611/f28a5397-e6a6-4291-bfa1-34d8845d7872)
