### ISSUE TITLE
FIX: Choosing Desktop or IDH from ISO GRUB menu results in failure

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#11865]
Booting the latest 2.4.30 ISO image and choosing the GRUB menu option for either Desktop or IDH results in failure:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/d2221c5d-49fa-4c25-8c83-7e7e5e528c34)

Both of these options reference the `@desktop` package group.

**Comment by dougburks** [comment]
Here's where it fails installing the `@desktop` package group:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/f8e3f4dd-0e2d-4e6d-bca6-88a91edc762a)

**Comment by dougburks** [comment]
Commits:
https://github.com/Security-Onion-Solutions/securityonion-repo/commit/363e1561a2e13d75c872aed4029e9b3e6dc7995f
https://github.com/Security-Onion-Solutions/securityonion-repo/commit/8fb9e92bfc38b6bc48a5ed2e3f5e6128387cf376
https://github.com/Security-Onion-Solutions/securityonion-repo/commit/0864a1c12add0ba61883032fbfb6cd6e07db29c0
https://github.com/Security-Onion-Solutions/securityonion-repo/commit/67f07c7d7d96ab56b84a9c4d8c2e7f946755b87a

**Comment by weslambert** [comment]
Confirmed working for both options with the latest changes.
