### ISSUE TITLE
FIX: Pre-compile YARA rules

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#11914]
Consider using something like yara.compile() to pre-compile YARA rules before providing them to Strelka to prevent issues with bad rules.

https://github.com/target/strelka/issues/410#issuecomment-1835061158

**Comment by derfel1989** [comment]
> I'm not sure if you are asking if Strelka is currently integrated with Security Onion or if the compilation will happen on the Security Onion machine. Just in case, the answer is yes to both questions. 😄
> 
> https://docs.securityonion.net/en/2.4/strelka.html#strelka

Good to know! 😀

**Comment by weslambert** [comment]
The pre-compilation is not included yet, but it will be included in a future release.

**Comment by weslambert** [comment]
This is implemented in [Detections](https://docs.securityonion.net/en/2.4/detections.html).
