### ISSUE TITLE
Additional Supported Integrations #2

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#11958]
- Anomali
- Cybersixgill
- ~~Maltiverse~~ (removed because of issue with installation)
- Snort
- ThreatQuotient

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion-image/pull/492
https://github.com/Security-Onion-Solutions/securityonion-image/pull/495
https://github.com/Security-Onion-Solutions/securityonion/pull/12000

**Comment by larry1788** [comment]
Hope to add Nginx and Modsecurity Integration。

Thank You！

**Comment by dougburks** [comment]
@larry1788 We will take a look at additional integrations as time allows. Preference is given to integration requests from paid customers.
