### ISSUE TITLE
Hunt - QUERY_INVALID__GROUP_NOT_STARTED

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#1199]
The following query yields this error: `QUERY_INVALID__GROUP_NOT_STARTED`

`((event.code:"1" AND winlog.channel:"Microsoft\-Windows\-Sysmon\/Operational") AND (process.executable.keyword:*\\whoami.exe OR process.pe.original_file_name:"whoami.exe"))`

**Comment by jertel** [comment]
Improved query parsing to handle embedded parenthesis.
