### ISSUE TITLE
cortex and thehive not running on standalone

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion#1202]
docker logs for cortex
`
[warn] application - application.conf @ file:/opt/cortex/conf/application.conf: 114: analyzer.path is deprecated, use analyzer.urls instead
[warn] o.t.c.s.JobRunnerSrv - The package cortexutils for python hasn't been found
[warn] o.t.c.s.JobRunnerSrv - The package cortexutils for python hasn't been found
[warn] o.t.c.s.JobRunnerSrv - The package cortexutils for python2 hasn't been found
[warn] o.t.c.s.JobRunnerSrv - The package cortexutils for python2 hasn't been found
Oops, cannot start the server.
Configuration error: Configuration error[
The application secret has not been set, and we are in prod mode. Your application is not secure.
To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
`

docker logs for the hive
`
Oops, cannot start the server.
Configuration error: Configuration error[
The application secret has not been set, and we are in prod mode. Your application is not secure.
To set the application secret, please read http://playframework.com/documentation/latest/ApplicationSecret
`

**Comment by weslambert** [comment]
Need to migrate config values for `hiveplaysecret` and `cortexplaysecret` when running soup.
