### ISSUE TITLE
Grid Members Acceptance fails

### ISSUE THREAD

**Issue by gitgoodgod** [Security-Onion-Solutions/securityonion#12093]
Hi.

So we did an upgrade on our security onion setup from 2.3 to 2.4.
The manager runs and can be logged into and so on.

But, the Grid only shows the manager, and not all the other nodes we have in out distributed env.
So i went into:
Administration -> Configuration -> Allow Search Nodes to connect to Manager.
put in the IP on one of the search nodes. then after a sync it shows up in pending members, and ready to be accepted.
So i press on (Review) and Accept. after a couple of seconds i get this error and nothing happens.
`
Timed out waiting for result. This does not necessarily indicate that the command has failed, as a timeout is often caused by a salt high-state running on the manager. Refresh the browser after a couple of minutes to see if the operation succeeded. If not, try the operation again. If the timeout persists, there may be a problem within the cluster.
See the Help section of the Security Onion documentation for additional troubleshooting guidance. 
The Hunt interface may contain additional log messages to further diagnose the issue.`

I see it says something about it being salt high-state running on the manager. But i do not think thats the issue, as i dont see it runnning when this problem appears.

Anyone that had any similar problems with this?
OBS. when i go into Hunt i see the sensors, just not in the Grid, and we do get data.

**Comment by dougburks** [comment]
@gitgoodgod Instead of creating an issue, please start a new discussion at https://github.com/Security-Onion-Solutions/securityonion/discussions/categories/2-4
