### ISSUE TITLE
Zeek Import Pcap

### ISSUE THREAD

**Issue by solftclone** [Security-Onion-Solutions/securityonion#12277]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/12276

<div type='discussions-op-text'>

<sup>Originally posted by **solftclone** January 30, 2024</sup>
Hi, I have one pcap captured in last month . I want that pcap packets to be processed by so-zeek container and generate notice logs on kibana dashboard whenever I will import that pcap.

I have tried tcpreplay and changing timestamp of pcap packets to current timestamp of Security onion But no notice logs were generated. 

I have my custom zeek script placed at proper location. Whenever I have imported pcap using so-import-pcap. Able to to notice logs on hunt dashboard for that particular timestamp when that pcap was captured. 

But i want the notice logs to be generated on kibana dashboard like logs will generate for live network traffic.

Can someone please help me with that as soon as possible.
</div>

**Comment by TOoSmOotH** [comment]
There is already a discussion for this.
