### ISSUE TITLE
400 error code during event esclation for analyst user

### ISSUE THREAD

**Issue by dgmyr** [Security-Onion-Solutions/securityonion#12362]
Hello we`ve encountered 400 errors code during events escalation to cases for users with analyst role. These problem is not permanent and sometimes SOC console signals to user that the event is already attached to case and event don't become acknowledged . When we assign superuser role problem no more repeats.
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/116648539/5129cb28-121f-4263-8711-117415f71e4a)
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/116648539/296d5dfd-3383-46f2-8bc4-e9f222fbfccf)

**Comment by jertel** [comment]
A discussion needs to be submitted before an issue is opened. Please follow the instructions on the Discussions section, and provide all the requested information when opening a 2.4 discussion. Include sensoroni-server.log snippets (redacted for privacy) showing the lines surrounding the 400 response.
