### ISSUE TITLE
Error so-filebeat. 

### ISSUE THREAD

**Issue by suricatalfon** [Security-Onion-Solutions/securityonion#1244]
Hello,

          ID: so-filebeat
    Function: docker_container.running
      Result: False
     Comment: Created container 'so-filebeat'. Failed to start container 'so-filebeat': 'Error 500: driver failed programming external connectivity on endpoint so-filebeat (05f8fc1dab8555336336e34d835e433433a5f118a2738d6ea3ad28ca1e8a402e): Bind for 0.0.0.0:514 failed: port is already allocated'.
     Started: 10:43:30.111746
    Duration: 1824.222 ms
     Changes:   
              ----------
              container_id:
                  ----------
                  added:
                      d3f098b6768e6de722ec81c1b5d2edcc0e42a6172a26ba3043da19365d049198

Tanks,

**Comment by dougburks** [comment]
What kind of installation was this?  ISO or network install?

Do you have some other process listening on port 514?

**Comment by suricatalfon** [comment]
Hello,

From USB booteable ISO.

**Comment by dougburks** [comment]
Did you use our Security Onion ISO image or standard CentOS/Ubuntu?

Do you have some other process listening on port 514?

**Comment by suricatalfon** [comment]
Hi,

Thank you. It is fixed.
Now I just have to fix cortex

   so-cortex ------------------------------------------------------------- [ ERROR ]  

so-cortex-start:

![Captura de pantalla de 2020-08-26 07-26-32](https://user-images.githubusercontent.com/59991902/91258807-86f6e380-e76d-11ea-9063-894c7214567f.png)

**Comment by dougburks** [comment]
Since you've resolved your filebeat issue, I'm closing this issue.

If you have further questions or problems, please use our community support forum:
https://docs.securityonion.net/en/2.1/community-support.html

Thanks!

**Comment by suricatalfon** [comment]
> Since you've resolved your filebeat issue, I'm closing this issue.

Ok. Thanks ;-)
