### ISSUE TITLE
Case Insensitivty for elastalert playbook rules

### ISSUE THREAD

**Issue by syst3m10** [Security-Onion-Solutions/securityonion#1247]
Hello - exciting work so far on the project, keep up the great work!

the  playbook rules/elastalert arent case sensitive, which makes bypassing the rulesets too easy. 

An example would be the SIGMA rule for "New RUN Key Pointing to Suspicious Folder". If we make a run registry key pointing to C:\Temp\file.exe, an alert will be flagged. However, a rule to c:\temp\file.exe will not be flagged.

**Comment by defensivedepth** [comment]
Thanks for testing and the feedback!

We have been working to address this - Our next release will include a new field subfield (`.security`) based on the new analyzer (https://github.com/neu5ron/es_stk) from @neu5ron - 

Playbook/Elastalert will be configured to use this new field, which will be case insensitive.

**Comment by syst3m10** [comment]
Perfect, thanks for the response

cheers

**Comment by defensivedepth** [comment]
Support for the new subfield (`.security`) has been merged  - https://github.com/Security-Onion-Solutions/securityonion/pull/1250
