### ISSUE TITLE
hosts file overwritten and manager node removed during install attempt

### ISSUE THREAD

**Issue by BustedSec** [Security-Onion-Solutions/securityonion#1249]
I have a manager node defined in my hosts file at 10.8.0.1 and the minion is 10.8.0.2. When install starts, after it asks for the host name of the manager to connect to - it goes and edits the hosts file and removes the IP address entry for that manager. Then install stalls out at about 16 percent during the salt checkin.

**Comment by BustedSec** [comment]
Let met provide more feedback - so in my install case I have the manager sitting across a vpn tunnel and name resolution doesn't work by default so I have to make an entry for my manager in the hosts file to get it to resolve. The install script removed the IP address from the hosts file for the manager node and leaves the host name in the hosts file. I do not know why it does this. It breaks install.

**Comment by BustedSec** [comment]
also at the end of setup it goes "disabling unused nics" can we turn this off? or have an install switch to not have this happen as it breaks stuff.

**Comment by TOoSmOotH** [comment]
We have #1139 for this. I will add the disabling nics to it.
