### ISSUE TITLE
Security Onion 2.4.50 - Installing from ISO - Hyper-V - Error @ the End

### ISSUE THREAD

**Issue by NeoLife-iT** [Security-Onion-Solutions/securityonion#12522]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/12384

<div type='discussions-op-text'>

<sup>Originally posted by **dougburks** February 20, 2024</sup>
https://blog.securityonion.net/2024/02/security-onion-2450-now-available.html

![51_dashboards](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/af72bf53-af70-4475-9b2e-d4c8efe1ccbf)
</div>

I am eval sOs  - installed from ISO on Hyper-V - VM on Dell - R420 Server 128G RAM - 32G Allocate to VM - After 10 times it all failed at the End - same error

-Trying 2 prior Release version 12/2023 - 3 tries - all failed 

So now I am just became an un-official beta tester now for ISO installation on Hyper-V - I just want a version of the release that actually work on the Hyper-V.

The error screenshot is below on Dell WorkStation T5080 : 2 Socket 12 Cores - 32 Gig Ram
![3-6-2024 4-57-06 PM](https://github.com/Security-Onion-Solutions/securityonion/assets/36971330/fe9c450a-f30c-4232-b3b9-ea187a8b48b0)

Screen short below is on Dell R420 - 2 Socket - 12 Cores - 128 Gig RAM -

![3-7-2024 10-13-59 AM](https://github.com/Security-Onion-Solutions/securityonion/assets/36971330/fadf5f14-a303-4730-b71b-3e065c522632)

-Re-installing 4 times @ the moment - Option Standard - Direct Connect - Expected Failed Again - Will post screenshot

**Comment by TOoSmOotH** [comment]
Please use discussions
