### ISSUE TITLE
FIX: mapping conflict with field http.response.status_code

### ISSUE THREAD

**Issue by cm-ops** [Security-Onion-Solutions/securityonion#12543]
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/63416267/4efefed0-e190-4ff6-971e-adb95d82b311)

`.ds-logs-soc-so-*` logs are getting the data type `keyword`, when the ecs data type is` long`

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/12650
