### ISSUE TITLE
FIX: Accept Uppercase emails

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#12559]

**Comment by jertel** [comment]
Verified:

![Image](https://github.com/Security-Onion-Solutions/securityonion/assets/16639611/98847092-de07-40ef-816d-a08339f4c4b2)



![Image](https://github.com/Security-Onion-Solutions/securityonion/assets/16639611/991d5eb8-0f08-49a5-8a77-92a074a2e5d3)
