### ISSUE TITLE
Sigma Rule Pull Overwriting Modifications

### ISSUE THREAD

**Issue by syst3m10** [Security-Onion-Solutions/securityonion#1256]
Hello

I see under the playbook backlog there are plans to implement a way to add exceptions. In the meantime, ive been making adjustments to the actual sigma files within playbook to add exceptions.  I believe playbook is syncing the sigma repository daily, which overwrites the sigma files which in turn modifies the elastalert yamls so the exceptions are lost. Is it possible to modify the sigma pulls to only pull new rules? 

I couldnt find where this sync was happening under /opt/so or the playbook and elastalert containers. If you could point me the right direction, and i could look into making this modification?

**Comment by defensivedepth** [comment]
Yes, you are correct on what is happening. 

I am not sure of how to best handle this functionality and am interested in hearing your perspective on it:

If you disable updating of the current sigma rules and only pull in new sigma rules, you will be missing out on updates to rules - many updates include tuning enhancements, etc. But there are definitely cases where you need to edit a particular sigma rule for your environment.

Thoughts?

The rule update script is in the SOCtopus container, `playbook_bulk-update.py`:

https://github.com/Security-Onion-Solutions/securityonion-image/blob/master/so-soctopus/so-soctopus/playbook_bulk-update.py#L45

Any changes to this would be temporary as it would revert back when the container is replaced (ie when `so-soctopus-restart` is run)

**Comment by syst3m10** [comment]
Thanks for the response!

For a short term solution, maybe it would be possible to allow a checkbox on a play to make it "custom" or "read-only". Once in this state, the sigma is placed in a custom folder. At the end of playbook_bulk-update.py, the custom sigma is copied from the custom folder to the sigma folder (over-writing the one from the bulk update).

This is an issue i (and many others) have struggled with running sigma based alerting in larger prod environments. Its great keeping up to date with the repository, but for functionality, its more important (at least in my experience) to be able to have your environment based modifications to make the rule usable.  

The long term would be best of both worlds (easier said than done).  One way this may be possible is to allow a "filter" section within a play. You would have premade fields to select from in the filter section ("TargetUserName, SourceIP etc) and then would fill in a comma separated data.  These filters would be placed into a database.

For example -> Field:UserName: Data:User1, User2

The play will also have a field that extracts the current "condition" of the sigma. The user is able to modify this and the changed condition is stored into the database

A python script would be made that is run after the bulk update script. The repository would be downloaded, and then the filters would be grabbed from the database and "injected" into the sigma file.  The filter would be 'injected' before the condition, and then the condition would be replaced with the user modified condition.

For example - Below is the detection and condition for whoami execution

detection:
    selection:
        Image: '*\whoami.exe'
    selection2:
        OriginalFileName: 'whoami.exe'
    condition: selection or selection2

After filter injection and condition change:

detection:
    selection:
        Image: '*\whoami.exe'
    selection2:
        OriginalFileName: 'whoami.exe'
   customfilter1:
        UserName: 
          - User1
          - User2
    condition: (selection or selection2) and not customfilter1

Just a few thoughts!

**Comment by TOoSmOotH** [comment]
Closing for now. Will reopen when this starts getting worked.
