### ISSUE TITLE
Docker fails to install during heavy node setup on ubuntu 16.04

### ISSUE THREAD

**Issue by BustedSec** [Security-Onion-Solutions/securityonion#1263]
Attached is my install log. 

[sosetup.log](https://github.com/Security-Onion-Solutions/securityonion/files/5138669/sosetup.log)

**Comment by BustedSec** [comment]
Docker fails to load due to the presence of the tun0 Interface. It  Manually creating the docker0 network interface as described here https://github.com/moby/moby/issues/31546 seems to mostly fix the issue. Will let you know if install works out now.

**Comment by BustedSec** [comment]
nope, now it can't find the manifest files on port 5000 of my server towards the end of the setup...... one step closer though.

**Comment by TOoSmOotH** [comment]
16.04 is no longer supported for SO 2
