### ISSUE TITLE
Hunt - improve third magnifying glass workflow

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1265]
### Overview

We recently updated Hunt to include a third magnifying glass for each field value that starts a new search (https://github.com/Security-Onion-Solutions/securityonion/issues/655). That new search is currently similar to the other 2 magnifying glasses in that it includes the field name and field value in the new search. We typically want to cast a wider net here, so we should make the 3rd magnifying glass just search for the field value itself in ANY field. It would also be nice to be able to right-click and open in a new tab so that we can spin off multiple searches.

### Example

Suppose we do a search and find a few alerts that indicate that the following source IP addresses might be compromised:
192.168.1.2
192.168.1.3
192.168.1.4

If we click the 3rd magnifying glass for 192.168.1.2, we'll get a query like `source.ip:"192.168.1.2"` but what we probably want is a wider query like `"192.168.1.2"` to see everything relating to that IP address whether it shows up in source.ip, destination.ip, or any other field.

In this example, we might also like the ability to right-click the 3rd magnifying glass for 192.168.1.2 and open in a new tab and then do the same for 192.168.1.3 and 192.168.1.4 to start new investigations for each IP address.

**Comment by jertel** [comment]
Both changes are implemented for RC3.
