### ISSUE TITLE
so is not working after changing the Network

### ISSUE THREAD

**Issue by Gogomine** [Security-Onion-Solutions/securityonion#1268]
Hi there,

Recently i have changed my network.

Then i was running my hybrid hunter in DHCP mode it's not working after changing the Home Network.
even enabled the so-allow with new ip address .

It's not working

**Comment by dougburks** [comment]
It looks like you also posted here:
https://groups.google.com/u/1/g/security-onion/c/yXr-DnVhevs

Please see the warning from https://docs.securityonion.net/en/2.1/configuration.html:
> If you use DHCP and your IP address changes, this can cause problems. If you want to use DHCP, make sure that you have a DHCP reservation so that your IP address does not change. Otherwise, use a static IP address to be safe.

Also see:
https://github.com/Security-Onion-Solutions/securityonion/issues/67
