### ISSUE TITLE
FIX: Elasticsearch annotation file for ILM index settings

### ISSUE THREAD

**Issue by cm-ops** [Security-Onion-Solutions/securityonion#12726]
`salt/elasticsearch/soc_elasticsearch.yaml`

Under `global_overrides > policy > phases` The description for warm and cold for `min_age` are the same specifically `This determines when the index should be moved to the cold tier` Warm should be `warm tier`.

Under so-logs index settings, the warm description for `min_age` is `Minimum age of index. This determines when the index should be moved to the hot tier.` This should be `warm tier`.

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/12844
https://github.com/Security-Onion-Solutions/securityonion/pull/12848
