### ISSUE TITLE
FIX: Add the write privilege to the analyst and limited-analyst roles to enable acking of alerts

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#12770]
Allow write access to the logs-* and legacy indices to allow the analyst role to acknowledge events.

**Comment by dougburks** [comment]
fix for analyst role:
https://github.com/Security-Onion-Solutions/securityonion/pull/12769

fix for limited-analyst role:
https://github.com/Security-Onion-Solutions/securityonion/pull/12810

**Comment by dougburks** [comment]
Tested and verified that analyst can acknowledge:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/01af2312-20e8-46ae-ba8e-d7897390aab5)

**Comment by dougburks** [comment]
Tested and verified that limited-analyst can acknowledge:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/3fbadc87-e03a-4552-9eb4-f38277fd2355)
