### ISSUE TITLE
How to correctly use Fortigate elastic agent integration with Security Onion?

### ISSUE THREAD

**Issue by soceng** [Security-Onion-Solutions/securityonion#12797]
Hello,

I am running a standalone on-prem deployment, version 2.4.30 installed from the ISO image, and I am trying to get syslogs sent from my Fortigates firewalls to appear in Kibana. 

First i will share my installation info

Installation Mode : Standalone 
Managment IP : 10.240.x.y
Airgap : True 
Proxy :NA
Allowed IP or subnet ( Sniffing Interface ) : 10.240.0.0/24 ( i have tried to assign specific IP like 10.240.0.204 but when i tried to access it via web from my workstation i couldn't  only from machine from the same subnet 10.240.0x.x so i assigned it this full subnet )

on my Fortigate on syslog server menu i added 10.240.0.0 and port number 9004  as UDP
is this configuration correct or shoud i add single IP which is the sniffing interface of SO ?
then i I have added the fortigate integration to the "so-grid-nodes_general" agent policy

 I have created a custom host group and custom port group with my fortigate IPs and the port 9004 respectively, (I've also assigned the custom port group to the custom host group)

here is the  tcpdump output taken from the standalone node , only events sourced from my devices is shown on the output 
<img width="678" alt="image" src="https://github.com/Security-Onion-Solutions/securityonion/assets/57097556/7251caff-faa5-48c2-baae-d6dc0d1df967">

Here is the contet of logstash.log

[logstach.txt](https://github.com/Security-Onion-Solutions/securityonion/files/14987262/logstach.txt)

Here is the output for sudo so-status
<img width="667" alt="image" src="https://github.com/Security-Onion-Solutions/securityonion/assets/57097556/ad42dfa9-1922-4720-bf13-63509b54cae0">

The issue is first want to check if my security onion installation is correct with the above specifications specifically the sniffer IF IP ?
then till now i didn't see any alerts or got any event's on standalone nodes as the output of tcpdum is  show only my devices event's ( SSH event  of my connection to the standalone node )
Thanks 
i appreciate  the assistance  from all specifically from  @soad20000  as he did this integration .

**Comment by TOoSmOotH** [comment]
@soceng Please start a new discussion.
