### ISSUE TITLE
Fix: Update OpenSSH from 8.7p1 to 9.6 or later

### ISSUE THREAD

**Issue by jollysig** [Security-Onion-Solutions/securityonion#12818]
OpenSSH is on version 8.7p1. There are multiple critical and high CVEs associated with versions prior to 9.6. 

https://www.cvedetails.com/vulnerability-list/vendor_id-97/product_id-585/Openbsd-Openssh.html

**Comment by TOoSmOotH** [comment]
openssh-server-8.7p1-34.el9_3.3.x86_64.rpm is the latest version as of this reply and includes all the proper back ported patches for current CVEs.
