### ISSUE TITLE
How to integrate Fortigate (or FortiAnalyzer ) with security onion? 

### ISSUE THREAD

**Issue by soceng** [Security-Onion-Solutions/securityonion#12813]
Hello,

I am running a standalone on-prem deployment, version 2.4.30 installed from the ISO image, and I am trying to get syslogs sent from my Fortigates firewalls to appear in Kibana.

First i will share my installation info

Installation Mode : Standalone
Managment IP : 10.240.x.y
Airgap : True
Proxy :NA
Allowed IP or subnet ( Sniffing Interface ) : 10.240.0.0/24 ( i have tried to assign specific IP like 10.240.0.204 but when i tried to access it via web from my workstation i couldn't only from machine from the same subnet 10.240.0x.x so i assigned it this full subnet )

on my Fortigate on syslog server menu i added 10.240.0.0 and port number 9004 as UDP
is this configuration correct or shoud i add single IP which is the sniffing interface of SO ?
then i I have added the fortigate integration to the "so-grid-nodes_general" agent policy

I have created a custom host group and custom port group with my fortigate IPs and the port 9004 respectively, (I've also assigned the custom port group to the custom host group)

here is the tcpdump output taken from the standalone node , only events sourced from my devices is shown on the output

<img width="880" alt="image" src="https://github.com/Security-Onion-Solutions/securityonion/assets/57097556/c80d3796-457f-4678-ab8c-8c59cdb7f1a4">

Here is the contet of logstash.log

[logstach.txt](https://github.com/Security-Onion-Solutions/securityonion/files/14987262/logstach.txt)

Here is the output for sudo so-status
<img width="608" alt="image" src="https://github.com/Security-Onion-Solutions/securityonion/assets/57097556/99bbdb06-a72b-4c62-8646-c9a5689f88a3">

The issue is first want to check if my security onion installation is correct with the above specifications specifically the sniffer IF IP ?
then till now i didn't see any alerts or got any event's on standalone nodes as the output of tcpdum is show only my devices event's ( SSH event of my connection to the standalone node )
Thanks
i appreciate the assistance

**Comment by dougburks** [comment]
@soceng You recently created a similar issue at https://github.com/Security-Onion-Solutions/securityonion/issues/12797.

As Mike requested at https://github.com/Security-Onion-Solutions/securityonion/issues/12797#issuecomment-2059035457, please stop creating ISSUES and instead start a new DISCUSSION. 

You can use the Discussions link at the top of this page or use this link: https://securityonion.com/discuss.

Thanks.

**Comment by soceng** [comment]
Already got message to create New issue and I did .
