### ISSUE TITLE
FIX: so-verify detects rare false error

### ISSUE THREAD

**Issue by petiepooo** [Security-Onion-Solutions/securityonion#12811]
During an installation of 2.4.60, when it detects a prior installation, there's an uncommon issue with the so-setup script reporting an error when there is none.

Specifically, the call to systemctl at https://github.com/Security-Onion-Solutions/securityonion/blob/3854620bcddff8a91ec9f3d312ae45cb9b6d8dfb/setup/so-functions#L1587 returns the text "Failed to stop salt-minion.service: Unit salt-minion.service not loaded."  Because of the "Failed" keyword, this gets detected during the call to so-verify as a setup error, resulting in in this warning:

> WARNING: Errors detected during setup.
--------- ERRORS ---------
Failed to stop salt-minion.service: Unit salt-minion.service not loaded.
--------------------------.

This appears for me when most of the 2.3.300 files are still on the system during a network install of 2.4.60 on Ubuntu 22.04.  While prepping for the in-place OS upgrade, I uninstall all salt packages.  Despite the warning, the upgrade was successful.

This cannot be duplicated on a fresh installation (ISO or network) due to it only happening on a reinstall where the minion has already been stopped, and possibly only on Debian/Ubuntu systems.

To duplicate, you could start with 2.3.300 on Ubuntu 20.04, remove the salt-* packages and all non-Ubuntu repositories, and run do-release-upgrade to install 22.04.  Then run so-setup-network so that it detects the previous install while salt-minion is not installed or running.  That's a lot of setup for a minor error, but is how I found it.

It also may be possible to duplicate this with a stock 2.4 install (network or iso) by removing the salt-minion package (or possibly just stopping it) prior to running so-setup-network a second time.

The failure message triggering this could be avoided by calling check_service_status() first and only attempting to stop the minion if it's present and running.  Alternatively, it may be as simple as redirecting that command's output to /dev/null.  I hesitate to suggest filtering out all instances of the string within so-verify, as there are other cases where it could indicate a valid error condition.

I understand Ubuntu is not a supported OS, and I appreciate the fact that you no longer expressly block so-setup from running if it's detected.  For that reason, I do what I can to make it easy for you to continue allowing its unsupported use.  If you're amenable, I can submit a PR; just let me know your preference for how to fix it.

**Comment by TOoSmOotH** [comment]
I think the check the status is the cleaner way. I agree filtering it or dropping it to /dev/null would be too big of a hammer to fix this.

**Comment by TOoSmOotH** [comment]
Merged
