### ISSUE TITLE
asking for username and password for authentication why ?

### ISSUE THREAD

**Issue by muhammad-nouman5** [Security-Onion-Solutions/securityonion#12829]
PLEASE STOP AND READ THIS INFORMATION!

If you are creating an issue just to ask a question, you will likely get faster and better responses by posting to our discussions forum instead:
https://securityonion.net/discuss

If you think you have found a possible bug or are observing a behavior that you weren't expecting, use the discussion forum to start a conversation about it instead of creating an issue.

If you are very familiar with the latest version of the product and are confident you have found a bug in Security Onion, you can continue with creating an issue here, but please make sure you have done the following:
- duplicated the issue on a fresh installation of the latest version
- provide information about your system and how you installed Security Onion
- include relevant log files
- include reproduction steps

**Comment by muhammad-nouman5** [comment]
it's asking for username and password for authentication

**Comment by dougburks** [comment]
@muhammad-nouman5 As shown above, instead of creating an ISSUE here please start a new DISCUSSION at https://securityonion.net/discuss. When you start that new DISCUSSION, please provide sufficient detail.
