### ISSUE TITLE
so-zeek docker libmaxminddb support issue

### ISSUE THREAD

**Issue by mayukandale96** [Security-Onion-Solutions/securityonion#12831]
Hi,
I am using security onion 170 .
There I have zeek 4.2 version installed.
I am writing zeek script which will get asn information of IP coming in network packets using lookup_asn function.
For this script I am getting error as:
**Zeek was not configured for GeoIP ASN support (lookup_asn(AnomalousDNS::a))**

As per documentation of so-zeek I have installed libmaxminddb library in my setup. with below command-

sudo apt-get install libmaxminddb-dev

Still that error is there. This error is observed inside reporter.log file of zeek docker.

I need to resolve this issue as soon as possible.
Can someone please help me as soon as possible.

**Comment by TOoSmOotH** [comment]
Please start a discussion. Note that 2.3 is not longer supported.
