### ISSUE TITLE
FEATURE: Enable license checks for enterprise features

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#12839]

**Comment by jertel** [comment]
Working as expected. Confirmed by Jorge:

> STIG state scheduled remediate job fails as expected with this in the /opt/so/log/salt/minion log
```
2024-04-24 16:56:47,987 [salt.utils.schedule:1792][INFO    ][99152] Running scheduled job: stig_remediate_schedule with jid 20240424165647987122
2024-04-24 16:56:53,124 [salt.state       :1297][INFO    ][557514] Loading fresh modules for state activity
2024-04-24 16:56:53,749 [salt.state       :2295][INFO    ][557514] Running state [stig.enabled_no_license_detected] at time 16:56:53.749521
2024-04-24 16:56:53,749 [salt.state       :2326][INFO    ][557514] Executing state test.fail_without_changes for [stig.enabled_no_license_detected]
2024-04-24 16:56:53,750 [salt.state       :323 ][ERROR   ][557514] ['The application of STIGs is a feature supported only for customers with a valid license. Contact Security Onion Solutions, LLC via our website at https://securityonionsolutions.com/ for more information about purchasing a license to enable this feature.']
2024-04-24 16:56:53,750 [salt.state       :2493][INFO    ][557514] Completed state [stig.enabled_no_license_detected] at time 16:56:53.750462 (duration_in_ms=0.942)
```

**Comment by jertel** [comment]
![Image](https://github.com/Security-Onion-Solutions/securityonion/assets/16639611/ad7f0694-1043-443b-9548-ea66f8a79903)

**Comment by BigMacCat** [comment]
> ![Image](https://private-user-images.githubusercontent.com/16639611/326042381-ad7f0694-1043-443b-9548-ea66f8a79903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMTU0NzAsIm5iZiI6MTcxNDIxNTE3MCwicGF0aCI6Ii8xNjYzOTYxMS8zMjYwNDIzODEtYWQ3ZjA2OTQtMTA0My00NDNiLTk1NDgtZWE2NmY4YTc5OTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDEwNTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZTUzZDQwMjc4YjgzZDY1NDM4Y2ZhMzM3ZTFjZmM3NTI3MjFmYzFmNGQ1NTk2ZTRlM2E4NjI2ZGU2ODY5NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-JUrDDD9lQkq0rZOiB9Ijq9J00wDX6oF7V1NyZVvCwI)

Hi guys.
I see in the screenshot that now we will need to purchase unlimited status. For example, the number of nodes or users. That is, if we compare it with what is now and with what will happen, will there appear limits and the functionality of the free version will be limited? I used to think that the enterprise license would only add some interesting features (for example, multi-tenancy) without limiting the current functionality..

**Comment by TOoSmOotH** [comment]
The license only pertains to the features listed. If you don't need OIDC or case time tracking for instance you don't need a license. There are no plans to limit the current free offerings and not all new functionality will be part of the pro license. For example 2.4.70 will have a new feature called "Detections" which we have invested a lot of time and resources into and it will be part of the free product. To reiterate, there is no node or user limits to the free product and no plans to take a free feature and move it to a pro feature.

**Comment by BigMacCat** [comment]
> The license only pertains to the features listed. If you don't need OIDC or case time tracking for instance you don't need a license. There are no plans to limit the current free offerings and not all new functionality will be part of the pro license. For example 2.4.70 will have a new feature called "Detections" which we have invested a lot of time and resources into and it will be part of the free product. To reiterate, there is no node or user limits to the free product and no plans to take a free feature and move it to a pro feature.

Hi. This is exactly what I wanted to know. I felt a little calmer. In any case, we will be interested in enterprise features. Thank you so much for your answer!
