### ISSUE TITLE
FIX: Elasticsearch cleanup script should avoid Suricata alerts

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#12855]
We should exclude the suricata indices by changing these 2 lines:
https://github.com/Security-Onion-Solutions/securityonion/blob/2.4/dev/salt/elasticsearch/tools/sbin_jinja/so-elasticsearch-indices-delete-delete#L37-L38

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/12864
