### ISSUE TITLE
FIX: Change Elasticsearch min_age setting for cold phase

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#12890]
Currently, our default for `warm` min_age is 30d and `cold` min_age is the same 30d:
https://github.com/Security-Onion-Solutions/securityonion/blob/2.4/dev/salt/elasticsearch/defaults.yaml#L149-L172

We should change the `cold` min_age to something else like 60d perhaps.

We should make this change in the global_overrides section and in each of the individual index sections. 

We should also change the `ex. 30d` in the description at:
https://github.com/Security-Onion-Solutions/securityonion/blob/2.4/dev/salt/elasticsearch/soc_elasticsearch.yaml#L123
and
https://github.com/Security-Onion-Solutions/securityonion/blob/2.4/dev/salt/elasticsearch/soc_elasticsearch.yaml#L305

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/12900
