### ISSUE TITLE
Sensor so-setup-network: pre-configured bond interfaces not showing up among available management/monitor interfaces

### ISSUE THREAD

**Issue by firion4ik** [Security-Onion-Solutions/securityonion#1289]
Hello,

when performing a network setup on a sensor with pre-configured **bond0** interface as management interface and **bond1** as monitoring interface, they were not present in the list when it asked to choose a management interface and monitor interfaces.
Also, when I chose two monitoring interfaces it automatically tried to bond them as **bond0**, which was already configured in the system, resulting in very messy and not working interface configuration.

It would be great if the script could check for existing bond interfaces, allow the user to pick bond interfaces for management and for monitor interfaces, as well as assign correct name for the automatically created monitoring bond interfaces (when user picks only physical NICs).

Thanks a lot in advance!

**Comment by TOoSmOotH** [comment]
bond0 is taken by the sensor interface. Management can use bond1 and above.
