### ISSUE TITLE
Mine can get corrupted

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion#1291]
If the mine.p file gets corrupted, it can cause issues with the ssl state since the CA is pulled from the mine.

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/1298

**Comment by Leche671** [comment]
I am experiencing this issue on a distributed deployment running 2.3.21. I tried running the "salt-call state.apply ca", but the "salt-call state.highstate" still fails on all the remote systems." The mine.p exists on the master. Do I need to copy that to the senor systems?
