### ISSUE TITLE
Remove Suricata version numbers from Setup screens

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1300]
Setup currently shows an inconsistent Suricata version number:

![image](https://user-images.githubusercontent.com/1659467/92608133-f9de7f00-f282-11ea-9aec-22bdb62beb00.png)

![image](https://user-images.githubusercontent.com/1659467/92608174-07940480-f283-11ea-81de-737d4e89518d.png)

We should remove the Suricata version number from Setup screens so that it is consistent and doesn't have to be changed in the future.

**Comment by defensivedepth** [comment]
@dougburks Also need to change the word `meta data` to `metadata`

**Comment by dougburks** [comment]
Agreed!

**Comment by weslambert** [comment]
So meta...
