### ISSUE TITLE
Soup failed with error 1: Unhandled error Unhandled error occured, please check /root/soup.log for details.

### ISSUE THREAD

**Issue by dpr1nce** [Security-Onion-Solutions/securityonion#13113]
running soup on 2.4.60 get the following message:
Enabling highstate.
local:
    ----------
    msg:
        Info: highstate state already enabled.
    res:
        True

Soup failed with error 1: Unhandled error
Unhandled error occured, please check /root/soup.log for details.

and that is the root/soup.log entry...cruising through the current issues in github didn't see anything on this from this year...am I missing something?

**Comment by dougburks** [comment]
Instead of creating an issue here, please start a new discussion at https://securityonion.com/discuss. Thanks!
