### ISSUE TITLE
FEATURE: Create Detection - Preload Rule Templates 

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#13152]

**Comment by coreyogburn** [comment]
This was merged in during commit https://github.com/security-onion-solutions/securityonion/commit/3a861d029f937d44882915001bc7718f3a9a66a8

**Comment by defensivedepth** [comment]
Validation check:

The `license` field should be changed to a dropdown list with the option for a custom entry. 

Preloaded values should be formatted according to https://spdx.org/licenses/:
- Apache-2.0
- AGPL-3.0-only
- BSD-3-Clause
- DRL-1.1
- GPL-2.0-only
- GPL-3.0-only
- MIT

**Comment by defensivedepth** [comment]
Validated as completed.
