### ISSUE TITLE
Having the same issues, was this ever resolved Grid days sensor faulted, so-status says 5x5

### ISSUE THREAD

**Issue by tone6740** [Security-Onion-Solutions/securityonion#13191]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/8417

<div type='discussions-op-text'>

<sup>Originally posted by **sempervictus** July 31, 2022</sup>
Grid says that the process status on a sensor is unknown, sensor shows all green on `so-status`; no idea how the stack interprets the latter into the former (or if its even using `so-status` in the new hotness) but it seems incongruent:
![image](https://user-images.githubusercontent.com/1331084/182024471-3b68cc54-ad29-47c8-a228-83dde40b24f9.png)
![image](https://user-images.githubusercontent.com/1331084/182024500-78ab29dd-e225-4620-9e9c-41a338ba1a9c.png)
The head-end showed this same thing for about a day, didnt show the sensor at all for the first few hours after joining, now shows the sensor as faulted without much reasoning.</div>

**Comment by dougburks** [comment]
Instead of creating an issue here, please start a new discussion at https://securityonion.com/discuss. Thanks!
