### ISSUE TITLE
Allowing a easy way to add more analyzers and responders Cortex

### ISSUE THREAD

**Issue by OzzyKampha** [Security-Onion-Solutions/securityonion#1319]
I would love to be avle to add more analyzers and responders to cortex. Could you make a way to expose a volume and make it presistant on update?

**Comment by weslambert** [comment]
You can already add custom analyzers/responders to `/opt/so/conf/cortex/custom-analyzers` and `/opt/so/conf/cortex/custom-responders`.  Please try this and confirm if it does or does not work for you.

**Comment by 00willo** [comment]
I just attempted this, and I'm getting an error on a missing dependency.  We'd need an easy way to get the python dependencies into the PYTHONPATH when that instance of the responders python file is executed in the so-cortex container.

**Comment by jertel** [comment]
Closing since Cortex is no longer in the product.
