### ISSUE TITLE
Detections- Unable to add a Sigma rule receive a 400 error

### ISSUE THREAD

**Issue by Huntanalyst** [Security-Onion-Solutions/securityonion#13229]
We are using Security Onion version 2.4.6. We are unable to upload custom Sigma rules. When selecting create we receive a 400 error message. When selecting convert we receive a 500 error message.

**Comment by TOoSmOotH** [comment]
Please start a new discussion.

**Comment by Huntanalyst** [comment]
> Please start a new discussion.

Will do, new discussion was created.
