### ISSUE TITLE
Plan for SOAR capability?

### ISSUE THREAD

**Issue by OzzyKampha** [Security-Onion-Solutions/securityonion#1323]
Is there any plan for adding SOAR capability in the stack? 
Shuffle is an ongoing open source project that could help with automation

**Comment by dougburks** [comment]
If you're looking for a place to ask questions, please see:
https://www.reddit.com/r/securityonion/

**Comment by dougburks** [comment]
Asked at https://www.reddit.com/r/securityonion/comments/iqok3p/soar_capability/, so closing this issue.
