### ISSUE TITLE
Implement Elastalert index pruning

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1326]
Two options:
- Modify Elastalert to support time-based indexes. PR exists already: https://github.com/Yelp/elastalert/pull/945/files
- Write a script to periodically delete docs from the single elastalert index: https://github.com/Yelp/elastalert/issues/178#issuecomment-121411315

**Comment by TOoSmOotH** [comment]
ILM will cover this

**Comment by PrometheusYu** [comment]
When will be ILM released?

**Comment by dougburks** [comment]
@PrometheusYu 

ILM is part of Elasticsearch:
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html

If you have further questions or problems, please start a new discussion at https://securityonion.net/discuss rather than replying to this old issue.
