### ISSUE TITLE
so-steno uses an older version of stenographer, which includes bugs fixed upstream

### ISSUE THREAD

**Issue by jtgreen-cse** [Security-Onion-Solutions/securityonion#1327]
Based on:

https://github.com/Security-Onion-Solutions/securityonion-image/blob/6735ccbbe448b4944184684255a4dbfef7608f49/so-steno/Dockerfile#L34

I think this means this bug is included, which I have seen on my grid:

https://github.com/google/stenographer/issues/189

**Comment by TOoSmOotH** [comment]
Will make sure this gets updated for the GA release.

**Comment by TOoSmOotH** [comment]
Latest and greatest tested.
