### ISSUE TITLE
ElastAlert dosen't send mails

### ISSUE THREAD

**Issue by mohasmr** [Security-Onion-Solutions/securityonion#13280]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/13257

<div type='discussions-op-text'>

<sup>Originally posted by **mohasmr** June 25, 2024</sup>
### Version

2.4.70

### Installation Method

Security Onion ISO image

### Description

configuration

### Installation Type

Distributed

### Location

airgap

### Hardware Specs

Meets minimum requirements

### CPU

8

### RAM

32

### Storage for /

300GB

### Storage for /nsm

137

### Network Traffic Collection

tap

### Network Traffic Speeds

Less than 1Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

No, there are no failures

### Logs

No, there are no additional clues

### Detail

i configured alert on manager in **/opt/so/rules/elastalert/email-alert.yaml** and there is not any mail recived on my mailbox after i test the rule with the command so-elastalert-test the test seems healthy
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/135219197/b172d34d-d58d-4443-819a-60f1a0b1e035)

even i choose ET POLICY Reserved Internal IP Traffic that occured each minute in my network 
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/135219197/367a6d37-7b96-4143-8b60-f82b375b7161)

i'm i miss a configuration or something 

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.</div>

**Comment by jertel** [comment]
Issues are intended for the development team to track and organize work on the product. They are not used for requesting or providing community support.

You have already opened a discussion for this question, and there's no need to ask the question multiple times. As noted in #1720, community support is best effort. If you need more urgent support then consider a support plan offered by Security Onion Solutions.
