### ISSUE TITLE
Update to 2.4.80 from 2.4.60 fails

### ISSUE THREAD

**Issue by M-Struck** [Security-Onion-Solutions/securityonion#13300]
I have attempted to upgrade to 2.4.80 from 2.4.60 twice, each time the upgrade fails.  This is standalone setup for evaluation/testing.  I am able to get things backup and running after restoring the VM from a one time backup.  For certain items, I see errors - see errors.txt.  If I run so-status after the update, there are missing components - see so-status.txt.  I'm not sure what else information would be helpful or if I should not update for now.
[so-status.txt](https://github.com/user-attachments/files/16085826/so-status.txt)
[errors.txt](https://github.com/user-attachments/files/16085827/errors.txt)

**Comment by TOoSmOotH** [comment]
Please start a new discussion.
