### ISSUE TITLE
FIX: ERROR Failed to add job patch_os_schedule to schedule

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1333]
I'm seeing the following error on Eval and Standalone installations:
```
[ERROR ] Failed to add job patch_os_schedule to schedule.
```
![image](https://user-images.githubusercontent.com/1659467/92994507-baa16f80-f4c8-11ea-8acf-42b10324b5f0.png)

**Comment by dougburks** [comment]
### Summary
This issue seems to be related to VMware Fusion (versions 11 and 12), Fusion's internal DNS server, and reverse lookups of IPv6 addresses. Configuring the VM to bypass VMware Fusion DNS and go directly to an upstream DNS server appears to avoid the issue.

### End-User Workarounds
To prevent the issue from happening before running Setup, configure the VM to bypass VMware Fusion DNS and go directly to an upstream DNS server.

If Setup has already been run and this is the only ERROR in sosetup.log, then simply reboot the box and it should be fine.

### Potential Code Workarounds
Potential workarounds are as follows:
1.  Add logic to setup to see if `Failed to add job patch_os_schedule to schedule.` is the only ERROR in sosetup.log. If so, there is no need to prompt the user.
2.  Run the following early in Setup to disable IPv6:
```
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
```

**Comment by m0duspwnens** [comment]
The merged pr will prevent salt from trying to add the job if the salt-minion service isn't running, but if they minion service is stopped after the jinja is rendered then this error can still possibly occur.
