### ISSUE TITLE
Expose thehive api

### ISSUE THREAD

**Issue by OzzyKampha** [Security-Onion-Solutions/securityonion#1334]
It would be nice if you could add a way to expose and interact with thehive api for more integrations

**Comment by weslambert** [comment]
I'm not sure, what you mean by this -- it is already exposed.  Is there anything you are having difficulty with?  In the future, please pose your question/issue to the mailing list/Reddit, before creating an issue, as we use these issues for tracking purposes, mainly after we've confirmed an actual issue/feature request.
