### ISSUE TITLE
Security Onion Change management interface after installation

### ISSUE THREAD

**Issue by hadi-d99** [Security-Onion-Solutions/securityonion#13359]
sec onion version : latest 2.4.80
type: standalone
cpu 8 ram 32 storage 500gb

Dear All,

i am preparing a security onion and exported it as vmdk to put it directly in other environment 
However i am searching for a way to change the management interface as in each login it show the ip set previously in the first installation

**Comment by dougburks** [comment]
Instead of creating an ISSUE here, please start a new DISCUSSION at https://securityonion.com/discuss.
