### ISSUE TITLE
dublicated ID on sigma rule so_idh_ssh.yml and so_idh_redis.yml

### ISSUE THREAD

**Issue by marco847** [Security-Onion-Solutions/securityonion#13371]
Hy
on the security onion IDH detection ruleset is an ID conflict:
the so_idh_redis.yml rule has the same ID as the original rule so_idh_ssh.yml:
 - so_idh_redis.yml: https://github.com/Security-Onion-Solutions/securityonion-resources/blob/main/sigma/stable/idh/so_idh_redis.ymll
 - so_idh_ssh.yml: https://github.com/Security-Onion-Solutions/securityonion-resources/blob/main/sigma/stable/idh/so_idh_ssh.yml

**Comment by defensivedepth** [comment]
This has been fixed: https://github.com/Security-Onion-Solutions/securityonion-resources/pull/3
