### ISSUE TITLE
Web Server is not accessible on manager

### ISSUE THREAD

**Issue by BustedSec** [Security-Onion-Solutions/securityonion#1340]
I just did a fresh install on my ESX box of a manager node in a distributed setup from the most recent install .ISO file. After the install I setup a second VM to act as a heavynode minion and forward packets on the same network. I selected to make the web interface accessible via hostname during the install. When accessing http://ATS-LOCAL-SEC and https://ATS-LOCAL-SEC I get nothing. I try the same with the IP address instead, still nothing. I nmap scan the box. Only port 22 is open. From the box I do a netstat -tulpn | grep :443 and it's only listening on ipv6. We have previously spoken about the ipv6 binding issue and Doug came to the conclusion that despite it binding only on iv6 it would still be accessible on the ipv4 address. It clearly isn't accessible. Please advice

**Comment by dougburks** [comment]
Hi @BustedSec ,

I assume you're referring to the previous discussion at https://www.reddit.com/r/securityonion/comments/ignhlv/security_onion_210_rc2_manager_binding_to_443_on/?

Per that discussion, have you tried running `so-allow` and allowing your IP address to connect?

https://docs.securityonion.net/en/2.1/so-allow.html

**Comment by BustedSec** [comment]
Hi doug, 

Thanks for the quick reply. My mistake. I did not remember to do that this time. Sorry. I can access it now.
