### ISSUE TITLE
Updated geoip documentation 2.4

### ISSUE THREAD

**Issue by Carlos-mb** [Security-Onion-Solutions/securityonion#13450]
According to documentation, the way to enable GeoIp is this:

Elasticsearch 8 no longer includes GeoIP databases by default. We include GeoIP databases for Elasticsearch so that all users will have GeoIP functionality. If your search nodes have Internet access and can reach geoip.elastic.co and storage.googleapis.com, then you can opt-in to database updates if you want more recent information. To do this, add the following to your Elasticsearch [Salt](https://docs.securityonion.net/en/2.4/salt.html#salt) config:

config:
  ingest:
    geoip:
      downloader:
        enabled: true

But I'm not able to find how to do this change. 

I'd like any help because I have found other posts talking about this, but they are related to older SO versions and the files and paths are not present in 2.4

Thanks.

**Comment by dougburks** [comment]
Instead of creating an ISSUE here, please start a new DISCUSSION at https://securityonion.com/discuss. Thanks!
