### ISSUE TITLE
Migration process error on 2.3.1

### ISSUE THREAD

**Issue by th3-insider** [Security-Onion-Solutions/securityonion#13479]
sudo soup  gives me: Succeeded: 735 (changed=22)
Failed:    4

ID: query_playbookdbuser_grants
ID: query_updatwebhooks
ID: query_updatename
ID: query_updatepluginurls

**Comment by dougburks** [comment]
Instead of creating an ISSUE here, please start a new DISCUSSION at https://securityonion.net/discuss and provide detailed information about your system. Thanks!
