### ISSUE TITLE
UPGRADE: so-strelka base images

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#13504]
https://github.com/Security-Onion-Solutions/securityonion-image/pull/572 upgrades the following images:
so-strelka-filestream
so-strelka-frontend
so-strelka-manager

https://github.com/Security-Onion-Solutions/securityonion-image/pull/577 upgrades the following image:
so-strelka-backend

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion-image/pull/572
https://github.com/Security-Onion-Solutions/securityonion-image/pull/577
