### ISSUE TITLE
FEATURE: Handle Custom Integration Policy Upgrades

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#13560]
Need to think through how to handle the integration policy upgrades for integrations that people have added.

![image](https://github.com/user-attachments/assets/770404fb-15aa-4a01-9e7d-f2034ea5be37)

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/13651

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/13651

Before: 

![Image](https://github.com/user-attachments/assets/89c2897f-12bb-4b57-ae8f-44f9fd646d96)


After:

![Image](https://github.com/user-attachments/assets/ff2b0ac4-58b2-4105-a0d1-be56bd7ce470)
