### ISSUE TITLE
Consider adding nomodeset kernel option to ISO

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1360]
Certain display adapters may require the `nomodeset` option passed to the kernel.

From https://www.reddit.com/r/securityonion/comments/iu27tk/21_iso_installer_needs_to_add_nomodeset_to_kernel/:
> On certain video hardware, the installer boots to a black screen. This seems to be a known issue with some video cards (it's AMD APU graphics in this case, FWIW), and requires the nomodeset kernel option. Since we are not installing a GUI, it seems appropriate to add this kernel option by default. At the very least, maybe add it to the installer's trouble-shooting splash page?

Also see:
https://docs.securityonion.net/en/2.2/trouble-booting.html
https://unix.stackexchange.com/questions/353896/linux-install-goes-to-blank-screen

**Comment by TOoSmOotH** [comment]
@dougburks The user can simply hit "Tab" and tack on nomodeset if needed. Can we address this with Documentation?

**Comment by dougburks** [comment]
@TOoSmOotH 

I had already updated the documentation. From https://docs.securityonion.net/en/2.2/trouble-booting.html:
```
Certain display adapters may require the nomodeset option passed to the kernel (see https://unix.stackexchange.com/questions/353896/linux-install-goes-to-blank-screen).
```

The default CentOS 7 ISO image includes an `Install CentOS 7 in basic graphics mode` option under the `Troubleshooting` menu:
![image](https://user-images.githubusercontent.com/1659467/93801897-bbe14380-fc10-11ea-97bc-055a3d679cf2.png)

I'm wondering if that can easily by adapted into our ISO image.

**Comment by TOoSmOotH** [comment]
ok I added it to the boot screen. So there are 3 options now.

**Comment by dougburks** [comment]
Thanks @TOoSmOotH !
