### ISSUE TITLE
Trying to install SO for Eval or Standalone hangs for hours

### ISSUE THREAD

**Issue by gilesco** [Security-Onion-Solutions/securityonion#13611]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/13609

<div type='discussions-op-text'>

<sup>Originally posted by **gilesco** September  4, 2024</sup>
Trying the 2.4.100 iso for testing in a Virtualbox VM. I *know* that my hard disk is not likely to be fast enough in this, but I need to get a bit hands-on with the tool before moving to production equipment.

Installs get as far as "Executing command 'so-elasticsearch-wait' in directory '/root'

Then it just hangs for hours. This is a quick eval as we want to get some hardware provisioned, but is this step supposed to take a long time?</div>

**Comment by dougburks** [comment]
You've already created a discussion at https://github.com/Security-Onion-Solutions/securityonion/discussions/13609 and that's the proper place to discuss this. Please be patient and somebody will respond to that discussion as time allows.
