### ISSUE TITLE
ens32 is unmanaged by Network Manager

### ISSUE THREAD

**Issue by BustedSec** [Security-Onion-Solutions/securityonion#1364]
this is a fresh ubuntu install, no config changes, everything default for the cloud-image install from the mini.iso for 18.04

During SO setup I get this error

![image](https://user-images.githubusercontent.com/7432967/93523986-d7dba100-f901-11ea-8424-f40911f4f39c.png)

**Comment by TOoSmOotH** [comment]
Remove the interface from netplan and reboot. Then re-run setup.
