### ISSUE TITLE
Collect as ISO image

### ISSUE THREAD

**Issue by umlumpa** [Security-Onion-Solutions/securityonion#13672]
Hi guys thnx for your product very useful! I want collect ISO image with custom docker images how can i do it?

Because i have got problem internet while downloading images! And i want change something in so-soc image and collect with this image as ISO? can you help me please?

**Comment by dougburks** [comment]
We only support our standard ISO image and our standard docker images. We cannot provide any support for modifying our ISO image or docker images. If you have further questions or problems, please start a new DISCUSSION at https://securityonion.net/discuss rather than creating an ISSUE here.
