### ISSUE TITLE
BPF Issues 2.4.9

### ISSUE THREAD

**Issue by Ncgodwod** [Security-Onion-Solutions/securityonion#13684]
Security Onion 2.4.9
BPF filter is not working for Zeek at all. 
I have confirmed syntax is correct and tested it against tcpdump for further testing.

Zeek will show the rule being added, but doesnt filter on the rule.

**Comment by dougburks** [comment]
Instead of creating an ISSUE here, please start a new DISCUSSION at https://securityonion.com/discuss. Thanks!
