### ISSUE TITLE
SO Sensor Showing Fault in Grid

### ISSUE THREAD

**Issue by jgiuliano2024** [Security-Onion-Solutions/securityonion#13699]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/13691

<div type='discussions-op-text'>

<sup>Originally posted by **jgiuliano2024** September 18, 2024</sup>
### Version

2.4.100

### Installation Method

Security Onion ISO image

### Description

other (please provide detail below)

### Installation Type

Distributed

### Location

on-prem with Internet access

### Hardware Specs

Exceeds minimum requirements

### CPU

2 x Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz

### RAM

96.00 GB

### Storage for /

1022M

### Storage for /nsm

3.4T

### Network Traffic Collection

span port

### Network Traffic Speeds

1Gbps to 10Gbps

### Status

No, one or more services are failed (please provide detail below)

### Salt Status

No, there are no failures

### Logs

No, there are no additional clues

### Detail

I have 4 sensors running. 1 shows fault in Grid view no metrics showing and cpu at 100%. The node can reach the master on all ports that are needed. The node is sending data to the master. Everything about the node shows it's working as it should. Netstat shows the following ports have established connections to the master 443, 8220, 4505, 8086, 4506, 5055. I have removed the node from grid and fleet rebooted no change. I removed it from both again and reinstalled the node from scratch no change.

![image](https://github.com/user-attachments/assets/89d1d3b8-3ede-44d8-8f00-ec5ab4a7695b)

All other sensor nodes are fine and showing metrics for the hardware. The sensor is a bare metal server. Dell R430 
If anyone has had this issue and a fix I would love to hear from you. Not sure what else to try at this point?
From the sensor
~~~
so-status

                  Security Onion Status
              Container │ Status  │               Details
────────────────────────┼─────────┼───────────────────────
           so-sensoroni │ running │           Up 14 hours
               so-steno │ running │           Up 14 hours
     so-strelka-backend │ running │           Up 14 hours
 so-strelka-coordinator │ running │           Up 14 hours
  so-strelka-filestream │ running │           Up 14 hours
    so-strelka-frontend │ running │           Up 14 hours
  so-strelka-gatekeeper │ running │           Up 14 hours
     so-strelka-manager │ running │           Up 14 hours
            so-suricata │ running │            Up 7 hours
            so-telegraf │ running │           Up 14 hours
                so-zeek │ running │ Up 14 hours (healthy)
~~~

In fleet it shows healthy
![image](https://github.com/user-attachments/assets/c45de6ac-cf10-4447-88b1-069d934c6563)

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.</div>

**Comment by dougburks** [comment]
@jgiuliano2024 You've already created a discussion at https://github.com/Security-Onion-Solutions/securityonion/discussions/13691. There is no need to create an additional issue here. Please be patient and somebody will respond to your discussion as time allows.
