### ISSUE TITLE
so-analyst future improvements

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1372]
First, see so-analyst immediate improvements here:
https://github.com/Security-Onion-Solutions/securityonion/issues/1371

Here are a few additional ideas for consideration:

- Once we've switched to NetworkMiner 2.6 (https://github.com/Security-Onion-Solutions/securityonion/issues/1290), include all RPMs in ISO image and support airgap deployments

- The main Setup script should include a new option for `ANALYST` mode which does network configuration if necessary and then calls `so-analyst`.

**Comment by TOoSmOotH** [comment]
This was in 2.3.21

**Comment by dougburks** [comment]
Are you sure this was in 2.3.21?

**Comment by TOoSmOotH** [comment]
Going to address the airgap component of this in #3160 

All the other items are complete.
