### ISSUE TITLE
FIX: Since OIDC emails can have uppercase, force lowercase prior to server side dispatch

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#13730]

**Comment by Ncgodwod** [comment]
Sweet! Thanks for fixing this so quick.

**Comment by jertel** [comment]
MR verified mixed case user can login via Azure. Superuser can then assign a role. User can then perform hunt queries and login to Kibana. Note that Kibana login will require the email written in lower case on the login form. Mixed case InfluxDB logins are not supported.
