### ISSUE TITLE
2.2 <= RC3: Install fails if all drives are removable

### ISSUE THREAD

**Issue by gebhard73** [Security-Onion-Solutions/securityonion#1376]
Hi,

the kickstarter script will fail if all drives in a system are removable, e.g. `/sys/block/sd[a,b,c]/removable` is `1` for all HDDs.

This is true e.g. for HP Z640 when using the two 3,5" HDD bays (the remaining drive is the USB thumb drive).
Details: https://www.reddit.com/r/securityonion/comments/ix3w7n/22_rc3_installation_error_pane_is_dead_unable_to/ 

Can you pls have a look? Tnx.

**Comment by TOoSmOotH** [comment]
The only solution here would be to use either the CentOS Minimal install or Ubuntu 18.04. We use the removable flag to try and identify the USB drive. I will look into a way to override this setting but for now I would just do a network install.

**Comment by gebhard73** [comment]
Hi, thanks for the explanation. 
Suggestion for finding out the installation boot device: 
`mount | grep repo | cut -d " " -f 1`

**Comment by TOoSmOotH** [comment]
Ok I will keep this issue open and see if we can improve this post GA.
