### ISSUE TITLE
[Custom Logstash Config (Parsing)]: Add Hint to Docs for Deleting / Moving Config Files

### ISSUE THREAD

**Issue by gebhard73** [Security-Onion-Solutions/securityonion#1378]
Hi,

when working with custom logstash configs for parsing in `/etc/logstash/custom` , I've stumbled upon the following issue:
If you create a config file and later on rename or delete it, then the old config won't be deleted in the `/etc/logstash/conf.d*` directories by the rsync command in `/usr/sbin/so-logstash-start` 
I don't have a quick idea nor solution for this but a hint should IMHO be added to the documentation here: https://docs.securityonion.net/en/16.04/logstash.html#parsing
e.g.:
**Caution:** When deleting (or renaming) config files in `/etc/logstash/custom` you have to manually delete the old files in the `/etc/logstash/conf.d*` directories. Otherwise the old config files would remain in `/etc/logstash/conf.d*` and still be parsed and obeyed for the actual logstash configuration.

Thanks :-)

**Comment by dougburks** [comment]
Done:
https://github.com/Security-Onion-Solutions/securityonion-docs/commit/0b56fa5e1db1f89be4e6c121f37482423b5fcbcc#diff-79d27bbe2d7735a1f374664e7e604e2f
