### ISSUE TITLE
Redis maxmemory not set overwrite

### ISSUE THREAD

**Issue by shipler** [Security-Onion-Solutions/securityonion#1380]
As stated here - https://docs.securityonion.net/en/2.2/redis.html#tuning
When you modify the /opt/so/conf/redis/etc/redis.conf file it should change the docker configuration, but after so-restart redis the file gets rewrite with the old value. 

I had to modify /opt/so/saltstack/default/salt/redis/etc/redis.conf for the changes to persist

**Comment by shipler** [comment]
I had to modify /opt/so/saltstack/default/salt/redis/etc/redis.conf for the changes to persist

**Comment by TOoSmOotH** [comment]
Issue confirmed. Will add some pillar settings. For now you can copy the file from default to local. Local will take precedence.

**Comment by TOoSmOotH** [comment]
https://docs.securityonion.net/en/2.3/redis.html

**Comment by TOoSmOotH** [comment]
tested and pushed. Will work in GA
