### ISSUE TITLE
Salt is not updating logstash lb_input_threads

### ISSUE THREAD

**Issue by shipler** [Security-Onion-Solutions/securityonion#1382]
After updating the ls_input_threads value in 

> /opt/so/saltstack/local/pillar/minions/hh-datanodexx.sls

Upon logstash restart the pipeline.workers field in the data node is not updating the

>  /opt/so/conf/logstash/etc/logstash.yml

**Comment by TOoSmOotH** [comment]
"logstash_settings:"\
		"  ls_pipeline_batch_size: 125"\
		"  ls_input_threads: 1"\
		"  ls_batch_count: 125"\
		"  lsheap: $LS_HEAP_SIZE"\
		"  ls_pipeline_workers: $num_cpu_cores"\

You need to change ls_pipeline_workers if you want workers to change

**Comment by shipler** [comment]
In which file? the minions sls not containing ls_pipeline_workers  only:

> "logstash_settings:"
> " ls_pipeline_batch_size: 125"
> " ls_input_threads: 1"
> " ls_batch_count: 125"
> " lsheap: XXXXX"

so i tried changing the ls_input_threads

**Comment by TOoSmOotH** [comment]
Was this upgraded from an earlier release candidate? logstash_settings is in the minion pillar below elasticsearch:

**Comment by TOoSmOotH** [comment]
closing I cannot recreate this
