### ISSUE TITLE
Installation Issue on a MacBook with M2 through both Parallel and virtualbox

### ISSUE THREAD

**Issue by Akin-Omoge** [Security-Onion-Solutions/securityonion#13844]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/13809

<div type='discussions-op-text'>

<sup>Originally posted by **kennedybot** October 11, 2024</sup>
### Version

2.4.100

### Installation Method

Security Onion ISO image

### Description

installation

### Installation Type

Import

### Location

airgap

### Hardware Specs

Exceeds minimum requirements

### CPU

8

### RAM

32

### Storage for /

1TB

### Storage for /nsm

200

### Network Traffic Collection

tap

### Network Traffic Speeds

more than 10Gbps

### Status

Yes, all services on all nodes are running OK

### Salt Status

No, there are no failures

### Logs

No, there are no additional clues

### Detail

I installed security onion and after installation, i was shown this screen. what do I do next, I am abit confused.

<img width="959" alt="Screenshot 2024-10-11 085240" src="https://github.com/user-attachments/assets/c04ecb94-cc30-4383-8af5-267a0ab7be3d">

### Guidelines

- [X] I have read the discussion guidelines at https://github.com/Security-Onion-Solutions/securityonion/discussions/1720 and assert that I have followed the guidelines.</div>

**Comment by dougburks** [comment]
It looks like you've created a discussion at https://github.com/Security-Onion-Solutions/securityonion/discussions/13845 and that is the proper place to discuss this. Closing this issue.
