### ISSUE TITLE
FIX: Salt Repo has moved

### ISSUE THREAD

**Issue by ross-tsc** [Security-Onion-Solutions/securityonion#13898]
Issue: Observed when undertaking an unrelated log review on a Manager node (v.2.4.110) in a Distributed grid running Rocky Linux 9 ($is_supported will be unset.) Salt repo no longer exists at repo.saltproject.io.
- Log file - /var/log/dnf.log
- Log line - `DEBUG error: Curl error (6): Couldn't resolve host name for https://repo.saltproject.io/salt/py3/redhat/9/x86_64/minor/3006.9/repodata/repomd.xml [Could not resolve host: repo.saltproject.io] (https://repo.saltproject.io/salt/py3/redhat/9/x86_64/minor/3006.9/repodata/repomd.xml).`

Research: Checked [here](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-rpm.html). Configured repo uses a different baseurl than is currently correct for salt. Repo in [/setup/so-functions](https://github.com/Security-Onion-Solutions/securityonion/blob/6ab05e7c057de15746329cff64f9af41c0d60027/setup/so-functions#L1845) will fail.
- Configured - `https://repo.saltproject.io/salt/py3/redhat/9/$basearch/minor/3006.9/`
- Correct (from updated installation instructions - `https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/linux-rpm.html`

Mitigation: Pull request to `dev` incoming

**Comment by TOoSmOotH** [comment]
Broadcom gave a full 3 day heads up on the change.

**Comment by ross-tsc** [comment]
Broadcom doing Broadcom things. Hopefully I did my PR process correctly for you guys :crossed_fingers:

**Comment by m0duspwnens** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/13900
