### ISSUE TITLE
[2.x]: Suggestion: If import-pcap is used, allow WiFi management interface

### ISSUE THREAD

**Issue by gebhard73** [Security-Onion-Solutions/securityonion#1391]
Hi,

if we install a non-production system, e.g. an import-pcap-system, it should be possible to have a WiFi NIC be the management NIC. So e.g. function "filter_unused_nics" could be extended to have a separate filtered_nic command for this.

Thanks!

**Comment by dougburks** [comment]
Could this be considered a duplicate of https://github.com/Security-Onion-Solutions/securityonion/issues/763?

**Comment by gebhard73** [comment]
Yes, I'm fine closing it because in #763 further down network install is mentioned, and in nw install all NICs should already have been configured so the special WiFi stuff doesn't matter. It's up to the team to allow WiFi for production mode or not ... ;-)
