### ISSUE TITLE
Salt repo change

### ISSUE THREAD

**Issue by alex-dev1** [Security-Onion-Solutions/securityonion#14008]
Hi,

for the network installation of security onion on ubuntu 22.04, I encontered the following error,
**The salt repo no longer exist**, 
broadcom recently released a breaking change which migrated the packages from repo.saltproject.io will be migrated to packages.broadcom.com
https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/

This can be fixed by updating the so-functions file.

**Comment by jertel** [comment]
See https://github.com/Security-Onion-Solutions/securityonion/issues/13898.
