### ISSUE TITLE
Unable to Access Security Onion Web Interface Post Installation via VPN

### ISSUE THREAD

**Issue by SankaGamage** [Security-Onion-Solutions/securityonion#14034]
**Issue Description:**
I installed Security Onion (network installation) on an Oracle Linux VM. The installation completed successfully, and I can connect to the VM using OpenVPN. However, I cannot access the web interface (https://192.168.1.xxx) from my browser.

**Environment Details:**
- Wi-Fi IP: 192.168.1.xxx
- VPN IP: 172.27.xx.xx
- Web Interface IP: 192.168.1.xxx
- Allowed Range (Configured): 172.27.xx.xx/xx

**Steps Taken:**
- Allowed VPN range for web access during installation (172.27.xx.xx/xx).
- Verified Security Onion services are running (so-status).
- Checked network interfaces and ensured IP addresses are correct (ip a).
- Used so-allow to confirm allowed IP ranges.

**Expected Behavior:**
- Web interface (https://192.168.1.xxx) should be accessible via VPN.

**Request for Help:**
1. Are additional post-installation steps required for web access?
2. How to troubleshoot this connectivity issue?

**Comment by dougburks** [comment]
It looks like you've created a discussion for this and that is the proper place to discuss it:
https://github.com/Security-Onion-Solutions/securityonion/discussions/14035

Closing this issue.
