### ISSUE TITLE
salt <node> so.status fails

### ISSUE THREAD

**Issue by jtgreen-cse** [Security-Onion-Solutions/securityonion#1404]
Pretty sure it's because

https://github.com/Security-Onion-Solutions/securityonion/blob/bafb13fd6d9f83a4f4af8ee9a79e7034dbf1379a/salt/_modules/so.py#L4

but

https://github.com/Security-Onion-Solutions/securityonion/blob/bafb13fd6d9f83a4f4af8ee9a79e7034dbf1379a/salt/common/init.sls#L154

**Comment by dougburks** [comment]
This works correctly for me, but I'm on CentOS 7 which symlinks `/sbin` to `/usr/sbin` by default. I'm assuming you're on Ubuntu 18.04?

**Comment by jtgreen-cse** [comment]
Yessir, `Ubuntu 18.04.5`
