### ISSUE TITLE
Anaconda reinstall error - Partitions exists

### ISSUE THREAD

**Issue by shipler** [Security-Onion-Solutions/securityonion#1435]
When trying to reinstall physical server from ISO anaconda is facing an error that relates to the /nsm mounted disk (different disk than / )
 I suspect that due to the fact the partitions/volumes already exists with the same name the install is getting an error. I do not have the exact error but after i wiped the disk, deleting all the partitions if fixed this.

**Comment by shipler** [comment]
Error - 

NewVG - name already in use, it is required to delete all existing volume groups using anaconda on the selected mount drives (in case VG with same name already exists) or ask user to confirm...

**Comment by TOoSmOotH** [comment]
Usually means you have to try installing again. The other option is to break out to a shell with alt+f2 and delete the partition and run setup again.
