### ISSUE TITLE
Disable SOC Escalate icon if TheHive is disabled

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1439]
If TheHive is disabled and we click the Escalate icon, then we get an error. Can we remove the Escalate icon if TheHive is disabled?
![image](https://user-images.githubusercontent.com/1659467/94946167-b950da80-04a9-11eb-8611-9c4558b08bc7.png)

**Comment by jertel** [comment]
Implemented as requested.

**Comment by dougburks** [comment]
Confirmed:
![image (11)](https://user-images.githubusercontent.com/1659467/95112330-c7ebfb80-070e-11eb-859a-bad6276ccdb5.png)
