### ISSUE TITLE
Logstash cant handle redis queue - Salt not applying config

### ISSUE THREAD

**Issue by shipler** [Security-Onion-Solutions/securityonion#1444]
I'm running an high performance install of HH, the master server have 32GB allocated for the Redis queue, but the problem is that no matter what i change the logstash running on the es node is not using even 3% of the available resources to get those logs from Redis. 

I created a fresh install of HH distributed architecture, on the **master** - I modified the **searchnode.sls** to the following config:

> ls_pipeline_batch_size: 30000
> ls_input_threads: 10
> ls_batch_count: 20000
> lsheap: 4000m

but on the **search node**:
I opened the /opt/so/conf/logstash/etc/logstash file and only 2 lines were appended:

> pipeline.workers: 1
> pipeline.batch.size: 30000

Trying to override the pipeline.workers manually and the salt process reinitiate it with the value 1. (Not sure how much it's related to logstash performance)

### Where i think the issue is:

Further exploring the logstash redis pipeline - the redis input is not specifying the batch_count value.
I manually updated the **/opt/so/conf/logstash/pipelines/search/0900_input_redis.conf** to specify the batch_count field, but salt is overriding it with line being completely removed. 

The file is not taking the batch_count value from the sls
https://github.com/Security-Onion-Solutions/securityonion/blob/bc6eb74af2576e1078339a5a0c3acadbb3a1d270/salt/logstash/pipelines/config/so/0900_input_redis.conf.jinja

**Comment by shipler** [comment]
I Edited the master's  0900_input_redis.conf.jinja file to be as following and it looks like it works...


```
{%- set MANAGER = salt['grains.get']('master') %}
{%- set THREADS = salt['pillar.get']('logstash_settings:ls_input_threads', '') %}
{%- set BATCH_COUNT= salt['pillar.get']('logstash_settings:ls_batch_count', '') %}


input {
	redis {
		host => '{{ MANAGER }}'
		port => 9696
		ssl => true
		data_type => 'list'
		key => 'logstash:unparsed'
		type => 'redis-input'
		threads => {{ THREADS }}
		batch_count => {{ BATCH_COUNT }}

	}
}

```

**Comment by m0duspwnens** [comment]
Thanks for the bug report.

The variable ls_batch_count was deprecated and since removed. It was replaced with logstash_settings:ls_pipeline_batch_size. We have updated the code now to reflect this.

Update your /opt/so/saltstack/default/salt/logstash/pipelines/config/so/0900_input_redis.conf.jinja to reflect the change on the following file: https://github.com/Security-Onion-Solutions/securityonion/blob/dev/salt/logstash/pipelines/config/so/0900_input_redis.conf.jinja

To change the input batch size, then update logstash_settings:ls_pipeline_batch_size pillar value in the minion sls file under /opt/so/saltstack/local/pillar/minions/<searchnode>.sls

For output, update the value logstash_settings:ls_pipeline_batch_size under /opt/so/saltstack/local/pillar/minions/<manager>.sls

**Comment by m0duspwnens** [comment]
https://github.com/Security-Onion-Solutions/securityonion/commit/faf5e7a64310848d5e331577fa9d8ada2b10b074

**Comment by shipler** [comment]
Aren't batch size and batch count different? 
batch size referring to how many events to collect before filter execution and batch count is referring to how much to query from redis? https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html#plugins-inputs-redis-options

**Comment by TOoSmOotH** [comment]
`{%- set MANAGER = salt['grains.get']('master') %}
{%- set THREADS = salt['pillar.get']('logstash_settings:ls_input_threads', '') %}
{% set BATCH = salt['pillar.get']('logstash_settings:ls_pipeline_batch_size', 125) %}

input {
	redis {
		host => '{{ MANAGER }}'
		port => 9696
		ssl => true
		data_type => 'list'
		key => 'logstash:unparsed'
		type => 'redis-input'
		threads => {{ THREADS }}
		batch_count => {{ BATCH }}
	}
}
`
threads are only used in the input plugin and defined in the pillar as logstash_settings:ls_input_threads
batch_count defines the batch of REDIS events that get pulled by each thread from REDIS. 

Although you can tweak the amount of threads, we recommend messing with the logstash_settings:ls_pipeline_batch_size value before touching the threads. logstash_settings:ls_pipeline_batch_size is also used in the REDIS output plugin as the batch size to commit to the REDIS queue.
