### ISSUE TITLE
VMWare Advanced Disk Options

### ISSUE THREAD

**Issue by cyberpika2** [Security-Onion-Solutions/securityonion#1480]
ISO install fails when using newer disk controllers and disk type.
Stops just after mapping, blinking cursor only.
May be related to #1376

VMWare Pro Version: 15
Options: Paravirtualized SCSI, NVMe

Problem is not present for default I/O controller type.
Options: LSI Logic, SCSI disk

**Comment by TOoSmOotH** [comment]
Can you pop onto another terminal (alt + f2) and run a couple of commands?

lsblk
cat /sys/block/$DEV/removable

**Comment by cyberpika2** [comment]
Yes, I can do that and get back with you today.

**Comment by cyberpika2** [comment]
`[anaconda root@localhost /]#lsblk
NAME                     MAJ:MIN    RM      SIZE    RO    TYPE    MOUNTPOINT
sr0                             11:0          1         6.8G      0      rom     /run/install/repo
loop0                          7:0           0    432.4M      1     loop
loop1                          7:1           0           2G      1     loop
|-live-rw                  253:0           0           2G      0     dm    /
\`-live-base              253:0           0           2G      1     dm
loop2                          7:2           0      512M      0     loop
\`-live-rw                  253:0           0           2G      0     dm    /
nvme0n1                259:0           0       250G       0    disk`

`cat /sys/$DEV/removable
/sys/block//removable: No such file or directory


cat /sys/block/*/removable
dm-0        0
dm-1         0
loop0         0
loop1         0
loop2         0
nvme0n1    0
sr0              1`

**Comment by cyberpika2** [comment]
Paravirtualized SCSI, SATA works too.
It is specific to the NVMe controller option.

**Comment by TOoSmOotH** [comment]
This has been fixed in 2.3.30
