### ISSUE TITLE
SO-Manager Backup Documentation

### ISSUE THREAD

**Issue by darth-drew** [Security-Onion-Solutions/securityonion#1561]
"Documentation still needs to be updated around backups but you could restore from backup on a new server with the same name/IP. You will at least need the following directories:

/opt/so/saltstack
/etc/salt
/etc/pki

You will lose any custom Kibana dashboards unless you backed up the ES data as well." 
-Mike Reeves in response to Discussion: Hypothetical Scenario: Critical Manager Failure #1558

**Comment by dougburks** [comment]
Documentation is here:
https://docs.securityonion.net/en/2.3/backups.html
