### ISSUE TITLE
acng docker should not show up in so-status when open is selected for updates on a manager type

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#1573]
If I chose "OPEN" to the question "How would you like to download OS package updates for your grid?" during installing, the aptcacherng won't be installed.
But so-status shows so-aptcacherng is missing.
Can you fix this?

Install type. STANDALONE

_Originally posted by @Masaya-A in https://github.com/Security-Onion-Solutions/securityonion/discussions/1572_

**Comment by m0duspwnens** [comment]
https://github.com/Security-Onion-Solutions/securityonion/discussions/1572
