### ISSUE TITLE
FEATURE: Pivot from SOC PCAP to CyberChef

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#1596]
Would love to be able to have Hunt-esque pivots on arbitrary data fields in PCAP transcripts to CyberChef - 

For instance, be able to pivot on this base64 value over to CyberChef to decode:

![image](https://user-images.githubusercontent.com/954732/96793288-16b1ba80-13ca-11eb-80ac-2f69deb824ae.png)

**Comment by dougburks** [comment]
Both pull requests have been merged and I've tested the latest `dev` installation in a local VM to verify everything is working as intended.
