### ISSUE TITLE
Add Wazuh Agent to Downloads

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#1609]
All,

How do I see what version of Wazuh is running to ensure I download the correct Wazuh agents?  The new documentation is great and makes it clear that the agent and server needs to be running the same version but it doesn't spell out how to check the version of Wazuh that is running.   

Also, it's great that the team added osquery downloads directly into SOC.  Is there a reason you decided against adding Wazuh agents there as well?  It definitely makes the airgap install easier.

Absolutely amazed the work that was put into SO 2!!!  Great job!
Matt

_Originally posted by @gr8matt in https://github.com/Security-Onion-Solutions/securityonion/discussions/1606_

**Comment by DashCarlos** [comment]
Maybe this can help you to find the version: (tested in 2.3.10)
sudo docker exec -it so-wazuh dpkg -l | grep wazuh

btw, what is the reason why there is no direct wazuh download in the SOC

**Comment by jertel** [comment]
Adding Wazuh link to the downloads page is already covered by issue #1390. Closing this duplicate issue.
