### ISSUE TITLE
Grafana admin password missing from pillar.get secrets

### ISSUE THREAD

**Issue by B3DTech** [Security-Onion-Solutions/securityonion#1632]
According to the documentation: https://docs.securityonion.net/en/2.3/grafana.html?highlight=grafana

To log into grafana, you have to do "sudo salt-call pillar.get secrets", except this doesn't return a grafana secret.  Only fleet, fleet_enroll-secret, fleet_jwt, mysql, and playbook_db.

**Comment by TOoSmOotH** [comment]
Was this a fresh install or an upgrade?

**Comment by B3DTech** [comment]
Upgrade

**Comment by TOoSmOotH** [comment]
admin:augusta
