### ISSUE TITLE
Passwords with $ not completing the initial installation.

### ISSUE THREAD

**Issue by deathnmind** [Security-Onion-Solutions/securityonion#1639]
When installing Security Onion and the user for the installation has a password that contains $ unable to proceed with installation after first reboot.  The user cannot log in for step 2 because unable to authenticate.  Tested this a few times and it is repeatable.  

This may also be a problem with creating the user for the web login, the install failed with errors when the web user's password contained a $.  Tried again without a $ and the installation completed. Tested once.

These errors were experienced with an offline installation as a VM on eSXI on version Security Onion version 2.3.0.iso

**Comment by jertel** [comment]
In the next planned release, dollar signs ($) will be prevented from being used in passwords during setup. Users can still change their passwords to values that include these special characters via the SOC UI, Fleet UI, and TheHive UI, if desired.
