### ISSUE TITLE
FEATURE: SOC should only display links to tools that are enabled

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1643]
If I don't install or later disabled TheHive, for example, the link should be disappeared from the SoC's menu.
(Or options to toggle on/off the links)

_Originally posted by @Masaya-A in https://github.com/Security-Onion-Solutions/securityonion/discussions/1571_

**Comment by jertel** [comment]
Grafana, Playbook, Fleet, and TheHive links will no longer appear on the SOC UI if those components were not installed.
