### ISSUE TITLE
Production installation Stopped Ubuntu 18 Network manager Error #1645

### ISSUE THREAD

**Issue by mnunez021** [Security-Onion-Solutions/securityonion#1646]
When I try to start the GitHub installation of SecurityOnion 2 StandAlone, but I received an error for my monitoring port "enp0s25 is unmanaged by Network Manager. Please remove it from other network management tools then re-run setup" I've tried to remove it numerous times with no luck. maybe I am inputting the wrong command but I am lost. please help

**Comment by dougburks** [comment]
Looks like you've already created a discussion over here:
https://github.com/Security-Onion-Solutions/securityonion/discussions/1645

Closing this issue.
