### ISSUE TITLE
SOCtopus: Allow for case template selection when pushing events to TheHive from Kibana

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#1671]
If there is no case_template field present in the record, then allow the user to select an appropriate template/template id before sending the event to SOC to have a case created, or allow for the use of a default template.

**Comment by jhildreth** [comment]
This would be extremely helpful! Would this affect pushing events from the Alerts interface as well?

**Comment by weslambert** [comment]
TMK, events pushed from the Alerts interface will follow a similar procedure, but more details will be available soon.
