### ISSUE TITLE
Strelka: Only extract most common keys from scan.exiftool

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#1676]
We need to focus on the avoidance of mapping explosion, but with exifdata having an undetermined amount of keys, we should extract the most common/important, then leave the rest under scan.exiftool, unparsed to avoid indexing too many fields.

**Comment by dougburks** [comment]
Please keep `scan.exiftool.FileType` as we have a default Hunt query for it:
```
event.module:strelka | groupby scan.exiftool.FileType
```
