### ISSUE TITLE
Standardize default usernames & passwords

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#168]
-~Grafana~ no longer uses built in auth
-Playbook

**Comment by dougburks** [comment]
Playbook: https://github.com/Security-Onion-Solutions/securityonion/issues/930

**Comment by dougburks** [comment]
Grafana: https://github.com/Security-Onion-Solutions/securityonion/issues/929

**Comment by rwwiv** [comment]
Playbook is now using the anonymous user
