### ISSUE TITLE
Adding Wazuh agents.

### ISSUE THREAD

**Issue by shapesh** [Security-Onion-Solutions/securityonion#1693]
Am trying to add wazuh agents but am getting just to options unlike the previous version 16.
[root@securityonion ~]# sudo /var/ossec/bin/manage_agents

****************************************
* Wazuh v3.13.1 Agent manager.         *
* The following options are available: *
****************************************
   (I)mport key from the server (I).
   (Q)uit.
Choose your action: I or Q:

**Comment by dougburks** [comment]
Have you tried the following?
```
sudo docker exec -it so-wazuh /var/ossec/bin/manage_agents
```

For more information, please see:
https://docs.securityonion.net/en/2.3/wazuh.html#usage
