### ISSUE TITLE
Change Hunt Strelka query

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1703]
Currently, the Strelka query is:
```
event.module:strelka | groupby scan.exiftool.FileType
```
But `scan.exiftool.FileType` might be going away soon via https://github.com/Security-Onion-Solutions/securityonion/issues/1676.

One option would be to change to:
```
event.module:strelka | groupby file.mime_type
```

**Comment by jertel** [comment]
Also updated default Strelka fields.
