### ISSUE TITLE
Consider adding a script to improve ssh config

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1724]
Consider a phased approach:
1. create an idempotent shell script called something like `so-ssh-harden` with the appropriate commands in it from https://docs.securityonion.net/en/2.3/ssh.html so that users can run it manually
2. have setup automatically run that shell script for new installations
3. after lots of testing, a later release might have `soup` run that shell script for existing installations

**Comment by TOoSmOotH** [comment]
Add the script for phase 1 for 2.3.10

**Comment by rwwiv** [comment]
Closing this issue with new issues created for items 2(#1932) & 3(#1933)
