### ISSUE TITLE
Security Onion Compatibility with Preexisting nodes & Multiple Master Nodes

### ISSUE THREAD

**Issue by ryguy-vt** [Security-Onion-Solutions/securityonion#1731]
Dear Security Onion Team & Community, 
We are looking to see if security onion is compatible with our current system or possibly move to a security onion architecture, as such we have a few questions:
Our wazuh cluster utilizes port 1514 to send data from the agents to the master node, is the security onion compatible for this type of system or can another port be utilized. In short can security onion connect to a preexisting wazuh cluster? Could the wazuh worker nodes send data to the security onion master node?
Additionally, could the security onion architecture allow for two master nodes? In case of a failure scenario we would like redundancy on our systems. 
Similarly, are we able to send logs, such as system logs, from the master node to a different server?
Best,
Ryan

**Comment by dougburks** [comment]
Hi Ryan,

It looks like you've already created this as a Discussion:
https://github.com/Security-Onion-Solutions/securityonion/discussions/1730

That's the correct place to discuss.

Thanks!
