### ISSUE TITLE
FIX: Alerts severity sort order

### ISSUE THREAD

**Issue by darth-drew** [Security-Onion-Solutions/securityonion#1741]
Alert dashboard event.severity_label seems to be sorting by alphabetical order. Can this get changed from (high, low, medium) to (high, medium, low)?

**Comment by jertel** [comment]
The next planned release will correct the default sorting issues to have groups of alerts sorted by descending count, and individual alerts sorted by descending timestamp. Sorting by severity is not planned at the moment, but depending on more feedback we can revisit it.
