### ISSUE TITLE
Centralised logs

### ISSUE THREAD

**Issue by greatestfen** [Security-Onion-Solutions/securityonion#1761]
Hello!
We have placed several sensors throughout the network and would like to consolidate all events on the master, and then send the logs to an external server. According to the documentation, this can be done with syslog-ng, however, there is also a condition that sguild is installed. There is no such service on the master server and no sguild-related directories and I suspect the documentation is from an early SO version.
Any ideas?
Please assist.

**Comment by dougburks** [comment]
It looks like you've already created a Discussion for this and that's the proper place to discuss:
https://github.com/Security-Onion-Solutions/securityonion/discussions/1760

Closing this issue.
