### ISSUE TITLE
so-status should show "starting up..." instead of "error" if uptime is less than 5mi

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#1764]

**Comment by dougburks** [comment]
Here's what we do in 16.04:
https://github.com/Security-Onion-Solutions/securityonion-elastic/blob/master/usr/sbin/so-elasticsearch-status#L25

**Comment by m0duspwnens** [comment]
If a container is not OK or DISABLED, so-status will now show WAIT_START if a highstate has not completed since system start and there isn't a highstate currently running. it will show STARTING  if a highstate has not completed since system start and a highstate is currently running.
