### ISSUE TITLE
Allow user to change web interface cert

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#1766]
How do I change the web cert on Security Onion 2? 
I knew how to do it on the Ubuntu/apache version but am not having much luck with the new hotness.

_Originally posted by @chromefinch in https://github.com/Security-Onion-Solutions/securityonion/discussions/1758_

**Comment by trocade** [comment]
I did this which seems to work just fine:

Replace the /etc/pki/managerssl.* with my real certificate and key once the installation fully done and I verified it was up and running.

This is the file that is mounted by the docker image. I have not seen any issues doing this.

**Comment by BustedSec** [comment]
These are my notes on this for anyone who runs across this.

#Kill the webserver listening on port 80

#either do:
netstat -tulpn | grep :80
kill -9 process

#or do: 
sudo so-nginx-stop

#Open up the box to the internet
#flush all IPtables Rules
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

#install certbox with 
apt install certbot (ubuntu host)
or yum install certbot (centos 7)
run sudo certbot certonly --standalone
from the /ect/letsencrypt/live/yoursitename/ folder
cp fullchain.pem /etc/pki/managerssl.crt
cp privkey.pem /etc/pki/managerssl.key

restart machine to wipe temporary iptables rules
do a so-status to make sure nginx is running

**Comment by petiepooo** [comment]
@BustedSec you shouldn't need to restart after updating the managerssl.* files that way.  A `salt-call state.apply nginx && salt-call state.apply firewall` should suffice (or just a `salt-call state.apply` if you're willing to sort through more output)..

@TOoSmOotH what would be even more awesome is if one could use an existing certificate on install if it were dropped in the right location on disk.  Or is that already possible just by dropping the appropriate files into the /etc/pki/ directory?  Reviewing the ssl/init.sls file, it looks like it might be.

Also, in reviewing the ssl/init.sls file, it may be wise to only replace the cert as it nears expiration if it was created by salt using the local CA.  People that go to the trouble of using their own cert may be surprised when it's suddenly replaced with a self-signed one...

**Comment by TOoSmOotH** [comment]
This is in 2.4

**Comment by amorphys** [comment]
Hi all, 
I did this install the new SSL certificate (wildcard SSL cert from SSL provider and i was copy the SSL cert  in location : 
 /etc/pki/managerssl.crt and managerssl.key files for my certificate restart the docker nginx everything ok ! But Fleet agents appear offline after that ? ! Everyone see this or maybe I miss something ?

Thanks

**Comment by Maro-MJ** [comment]
Hi all, 
After installing Security Onion 2.4, i try to change the default ssl certificate and use a custom one. I do steps descripted bellow and i changed the .crt and .key default with the new ones and then i restart nginx. But, when i reboot the machine, i found the .crt file is overrided and changed with the default hostname selfsigned cert. 
Any help please?

**Comment by TOoSmOotH** [comment]
@Maro-MJ  @BustedSec For 2.4 you do not replace any files. You pasted the contents of the certificate into the appropriate fields via the web interface.
