### ISSUE TITLE
Processes not starting

### ISSUE THREAD

**Issue by mamba143** [Security-Onion-Solutions/securityonion#1770]
So.kratos,  so-steno, so-mysql,  so-cortex & so-filebeat not starting, stays in error mode

**Comment by m0duspwnens** [comment]
@mamba143 

Which OS and type of node install is this? Was it a fresh install or an upgrade?

Do the containers stay in error mode for beyond a 15 minute system uptime? 

Can you run a `salt-call state.highstate` from the node that is having this issue and report any errors here?

Are there any errors in the log files for each container under the appropriate directory under /opt/so/logs?

**Comment by mamba143** [comment]
Hi Josh,


The processes did stay in error state far beyond the 15 minute mark..
however I checked after 4 hours and they are all started and set as ok.
