### ISSUE TITLE
stenoloss.sh should not run if there is already one running

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#1777]
2.3.2 upgraded by soup each step from 2.3.0. Standalone install. 

Threads are steadily increasing. ps -aux shows a hell of a lot of this:

root     65508  0.0  0.0      0     0 ?        Z    Oct23   0:00 [stenoloss.sh] <defunct>
root     65509  0.0  0.0      0     0 ?        Z    Oct27   0:00 [stenoloss.sh] <defunct>
root     65513  0.0  0.0      0     0 ?        Z    Oct29   0:00 [stenoloss.sh] <defunct>
root     65517  0.0  0.0      0     0 ?        Z    Oct23   0:00 [stenoloss.sh] <defunct>
root     65520  0.0  0.0      0     0 ?        Z    Oct26   0:00 [stenoloss.sh] <defunct>
root     65525  0.0  0.0      0     0 ?        Z    Oct23   0:00 [stenoloss.sh] <defunct>
root     65526  0.0  0.0      0     0 ?        Z    Oct29   0:00 [stenoloss.sh] <defunct>

![sothreads](https://user-images.githubusercontent.com/8947638/97655394-1c3d8d80-1ab9-11eb-9c05-5727e96a26e0.PNG)

The blip on the graph is the upgrade to 2.3.2.

_Originally posted by @greatapoc in https://github.com/Security-Onion-Solutions/securityonion/discussions/1745_

**Comment by TOoSmOotH** [comment]
Also check other telegraf scripts to add the same feature.

**Comment by TOoSmOotH** [comment]
fixed in 2.3.10

**Comment by rwwiv** [comment]
Fully resolved in 2.3.30, see #2293 for more details on the fix.
