### ISSUE TITLE
Navigator: Layers not loading correctly

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#1798]
https://github.com/Security-Onion-Solutions/securityonion/discussions/1786#discussion-29711

**Comment by ghefary** [comment]
Same issue here , but it was ok in V 2.3.0

**Comment by OzzyKampha** [comment]
Same here

**Comment by stijnpieters** [comment]
Same issue. According to logs it tries to create plays using anonymous user, therefore returns a 401.
In /opt/so/saltstack/local/pillar/global.sls I see a "playbook api_key" variable, but it's not set.

**Comment by weslambert** [comment]
@rwwiv [bumped this to 3.1](https://github.com/Security-Onion-Solutions/securityonion-image/commit/87f8c6d47131cac745c5cb2d829ee25b48694596#diff-f9f483b998941a04229f58989b81be932ea6c7beeb9d6240f0bc96d9c6ae43c4) and seems to be performing like it should, aside from introduction of sub-technique support:

![image](https://user-images.githubusercontent.com/16829864/98556530-2279f980-2271-11eb-8841-2e1f8e6621ca.png)

Thoughts @defensivedepth ?

**Comment by defensivedepth** [comment]
Looks good to me
