### ISSUE TITLE
Snort 3.0 initial integration

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#181]

**Comment by dougburks** [comment]
https://blog.snort.org/2020/04/snort-beta-available-now.html

**Comment by TOoSmOotH** [comment]
Going to close this out for now. If this ever reaches production we will re-visit.

**Comment by petiepooo** [comment]
@TOoSmOotH Snort v3 is GA.. is it time yet to revisit this issue?  Or at least get it on the roadmap for SO2?
I'm one of the unlucky ones that has a TALOS subscription, and have to disable all shared-object rules while running under suricata.  That's a significant portion of the ruleset, so I'm not getting the full value until I can run under snort...
