### ISSUE TITLE
Support xvda devices in ISO install

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#1819]
Thanks for the very quick response, Mike.

Here's what CentOS Minimal install and a lsblk displays on the same VM:

![2](https://user-images.githubusercontent.com/47314874/98059401-ea0ea000-1eab-11eb-9898-be5f723fd966.JPG)

_Originally posted by @krullos in https://github.com/Security-Onion-Solutions/securityonion/discussions/1812#discussioncomment-120840_

**Comment by krullos** [comment]
Confirmed as resolved - XCP-ng VMs will now boot from Security Onion 2.3.30 iso.
Thanks for your work!
