### ISSUE TITLE
filebeat potentially losing track of zeek files because of rotation out of scope

### ISSUE THREAD

**Issue by jtgreen-cse** [Security-Onion-Solutions/securityonion#1821]
2.3.2
network install
Ubuntu 18.04
distributed: manager, 4 x sensor, 4 x search
so-status all OK
no failures running salt-call state.highstate

I've had issues with the sensor nodes progressively slowing down sending zeek logs, to the point where they only trickle in. I can watch the logstash traffic on the manager slowly taper off. Logs do still come in, but not anywhere near the number of events being generated in the zeek log files.

I have a theory about what is going on.

I believe this is due to the filebeat config. When the zeek logs get rotated every hour, the zeek process moves them temporarily before compressing them. Filebeat tracks the log files by inode, when zeek moves the file, filebeat no longer has it in scope (since `path` is set to look at the individual log file, and not the folder) and it's registry waits to see that inode again. These inodes that are never to be seen again build up in the registry, and aren't cleared. Maybe this leads to inode reuse issues? I've tried to fix this and have made progress by adding `file_identity.path: ~` based on: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html This seems to allow filebeat to properly and consistently follow the log files after they rotate.

Has anyone run into this? Is my logic flawed? I'd love to hear about the technical reasons for the decisions made with the current config.

**Comment by TOoSmOotH** [comment]
We will look into this.

**Comment by dougburks** [comment]
@weslambert mentioned the following:
https://www.elastic.co/guide/en/beats/filebeat/current/inode-reuse-issue.html
https://www.elastic.co/guide/en/beats/filebeat/current/file-log-rotation.html

**Comment by weslambert** [comment]
@jtgreen-cse can you please try the following?

Remove/remark the `file_identity.path: ~ ` option.

For the Zeek log prospector, please add/change the following option:

`clean_removed: true`

Please let me know if you observe proper behavior with this option.

**Comment by jtgreen-cse** [comment]
I've made the change, I'll let it run for a week and report back with the results.

**Comment by jtgreen-cse** [comment]
Update: The issue is fixed with `clean_removed: true`. After 7 days, logs stay at the expected rate. The baseline rate stayed up during the night over the course of the 7 days. Without `clean_removed: true` logs would taper off over the course of 7 days,

**Comment by dougburks** [comment]
That's great news, thanks @jtgreen-cse !

@weslambert committed https://github.com/Security-Onion-Solutions/securityonion/commit/6b4af30fc1ff11b5736b45e5f72e99a1541456ff yesterday, so this fix should be in the next release.
