### ISSUE TITLE
Improve error messaging on kickstart when no drives are present.

### ISSUE THREAD

**Issue by sdanieru** [Security-Onion-Solutions/securityonion#1825]
When I boot the ISO, the media check runs successfully and then I see brief text saying 'starting installer, one moment' after this there is some text that flashes on the screen too quickly to see, and then I see a blinking cursor....forever.

When I hit Alt+F1, I see:

```
anaconda x.y.z for CentOS 7 started.
...
...
The following problem occurred on line 0 of the kickstart file:
Unable to open input kickstart file: curl#37 - "Couldn't open file /tmp/part-include"
```

Please let me know if there are particular logs I can grab that would be helpful. I noticed that I can hit Alt+Tab to get to a prompt and poke around on the fileystem.

**Comment by sdanieru** [comment]
I've flashed another USB flash drive with the ISO and get the exact same result. I'm using Balena Etcher for flashing if that's relevant. Can anyone else reproduce this problem with the 2.3.2 ISO?

**Comment by sdanieru** [comment]
I just successfully ran the install inside a Virtualbox VM so my next guess is that the installation distro isn't compatible with my server hardware. It's a Thinkmate (re-branded supermicro) [RAX XS4-11E2-SH](https://www.thinkmate.com/system/rax-xs4-11e2-sh) which appears to have [this](https://www.supermicro.com/en/products/motherboard/X11SCM-F) motherboard.

/etc/centos-release tells me:
CentOS Linux release 7.8.2003 (Core)

...which looks like the second to last CentOS release.

Does anyone have suggestions on the best route forward here? Is there a way to provide a newer kernel/drivers to the install? If it is indeed a problem w/ too new hardware, then falling back to the previous security onion release probably isn't going to help the situation.

**Comment by sdanieru** [comment]
Here are some of the logs in /tmp:
![Screenshot from 2020-11-06 10-15-43](https://user-images.githubusercontent.com/18471926/98396725-6d9acf00-201b-11eb-9a89-ac1dbe68a504.png)

Perhaps the most notable item in there is the syntax error in the ks-script:

`line 63: /3: syntax error: operand expected (error token is "/3")`

which is this line:

`ROOTSIZE=$(($GB/3))`

...perhaps `ROOTSIZE` wasn't properly given a value and is empty?

**Comment by sdanieru** [comment]
OK, I think I've gotten to the bottom of this. It looks like the script is assuming that any NVMe drives will have a symlink in `/sys/block` named `nvme` but in my hardware case, the kernel has named the symlink `/sys/block/nvme0n1`.

Since the `for` loop right after `# Ask some basic questions` never evaluates true since it never matches `nvme`, `NUMDRIVES` is never incremented, but the script proceeds with the assumption that it's been incremented at least once, the logic that populates `GB` and `SIZE` never runs because there are no `DEV` values it ever matches on, and then it finally crashes when it tries to set a value for `ROOTSIZE` since GB has no value.

As near as I can tell, that's more or less what's happening. 

Could this issue get some love from the developers? It would be great to get this fixed so we can get Security Onion up and running.

**Comment by sdanieru** [comment]
@TOoSmOotH this appears to be a case where the ks script isn't properly handling NVMe storage device names; do you know who on your team would be best suited to look into this?

**Comment by dylangerdaly** [comment]
I can confirm I'm receiving the same error.

There there a quick workaround? I wanted to install SO on a Laptop I have kicking around.

**Comment by lo0pback** [comment]
Receiving the same error on a xenserver box.

**Comment by Mic-Pod** [comment]
I have the same problem on Odyssey x86j4105 using SO 2.3.21.

**Comment by Mic-Pod** [comment]
OK, I have found the solution for Odyssey x86j4105. I tried to install SO on the eMMC (device mmcblk1) which is only ~58GB (less than required >99GB). After connecting additional disk, installation completed successfully.

**Comment by TOoSmOotH** [comment]
NVME installs should work properly now starting in 2.3.30

**Comment by MacroPolo** [comment]
These symptoms can also been seen when attempting a virtualised installation on a disk using the LsiLogic SCSI controller driver. Centos 7.X does not support LsiLogic or BugLogic drivers which is documented up to [7.4](https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7.1708). No mention of that limitation on the 7.6 release notes (applicable to SO installer) strangely enough, but the issue seems to remain.

Came across this with libvirt/KVM which defaults to `lsilogic` when using a SCSI controller and will likely also affect VMware. In my case, changing to `virtio-scsi` fixed the issue, allowing the virtual disk to be seen by the installer.

**Comment by TOoSmOotH** [comment]
This error occurs when it is unable to find a hard disk to install on. Going to try and improve the messaging to address confusion.

**Comment by ITfromHell** [comment]
Hey, I have the same problem with 2.1.3.140-20220729 at [Lenovo P350 Workstation (ThinkStation) - Type 30E3](https://pcsupport.lenovo.com/de/de/products/workstations/thinkstation-p-series-workstations/thinkstation-p350/30e3/30e3009age/pc2apjnb) , GRUB seems not to recognize the NVME. At UEFI bios, SATA is set to ACPI (instead of Intel RST), secure boot is disabled.
You can select, which install procedure you want to start, after hiting ENTER, menu disappears ant nothing happens. An installed Ubuntu tells me "/dev/nvme0n1pX" as device name.
Also testes 2.3.130.

**Comment by CX-MW2022** [comment]
@TOoSmOotH So could it maybe be that there still an issue with NVME drives and like i wrote in my previous comment maybe with the model of my RAID controller? I nearly tried everything to install Security Onion on that machine and had no success, the last thing i maybe try is install it via pxe, but that would be pretty time-consuming and i am not sure if it makes any difference if i just change the way i'm delivering the installation medium.

**Comment by ITfromHell** [comment]
I resolved this topic via installing Ubuntu 20.04 and installing Security Onion there. Works great.

**Comment by CX-MW2022** [comment]
Thanks! This wouldn't be my favourite solution, but i'll give it a try as soon as i've got some time for testing.

**Comment by ccpaasmyser** [comment]
We are having the same issues with NVMe drives a dell 740xd with the same situation and everything. Is there any resolution beyond installing security onion manually overtop another distro?

**Comment by ITfromHell** [comment]
> We are having the same issues with NVMe drives on a dell 740xd with the same situation and everything. Is there any resolution beyond installing security onion manually overtop another distro?

Yes, Ubuntu as I did https://github.com/Security-Onion-Solutions/securityonion/issues/1825#issuecomment-1211717061 , see also https://docs.securityonion.net/en/2.3/installation.html

**Comment by mehransafari** [comment]
i am on dell with vmware workstation. i changed my virtual disk type from scsci to sata and problem solved.

**Comment by TOoSmOotH** [comment]
This issue should be addressed with the new Oracle 9 based ISO image.

**Comment by AhmadAbdElHakim** [comment]
> i am on dell with vmware workstation. i changed my virtual disk type from scsci to sata and problem solved.

Thank you, much appreciated
