### ISSUE TITLE
Create root certificate according to choice in config

### ISSUE THREAD

**Issue by stijnpieters** [Security-Onion-Solutions/securityonion#1833]
When configuring your server you get the option to let the server listen on IP, hostname or custom (e.g. FQDN).

My suggestion is to create the root certificate according to the choice in this question, allowing osquery to work out of the box when installing in any setup.

**Comment by TOoSmOotH** [comment]
In 2.4 the certificate can be replaced via the UI. Elastic Agent replaces osquery.
