### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1847]
We should add a contributing.md file:
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors

and include our requirements like:
- PRs should go to dev
- commits must be signed

**Comment by codrcodz** [comment]
Hi @dougburks. I'd really like to contribute to the project. I've seen a few minor code quality tweaks that could be made to some of the bash parts of the codebase, but I'm not sure what your bash coding standards are, if any, besides just following the more obvious conventions already in place, like indentation.

In lieu of a `CONTRIBUTING.MD`, do you have any advice for someone wanting to contribute some minor code quality improvements? Is there a test suite I should run to validate that my changes haven't broken anything?
