### ISSUE TITLE
arp turned of on all interfaces except ens192

### ISSUE THREAD

**Issue by maseron** [Security-Onion-Solutions/securityonion#1875]
Took me some time to find why the network on second interface is not working...

And the problem was in this script:
/etc/NetworkManager/dispatcher.d/pre-up.d/99-so-checksum-offload-disable
```
#!/bin/bash
if [[ "$DEVICE_IFACE" != "ens192" && "$DEVICE_IFACE" != *"docker"* ]]; then
	for i in rx tx sg tso ufo gso gro lro; do
		ethtool -K "$DEVICE_IFACE" "$i" off;
  	done
	ip link set dev "$DEVICE_IFACE" arp off multicast off allmulticast off promisc on
```

So it do not meter which interface is selected for monitoring, the script disables arp for all interfaces except ens192.
I think it needs to disable arp only for interfaces which are selected for monitoring.... the ones which are added to bond0

**Comment by TOoSmOotH** [comment]
We will add this to the todo list to tighten this up a bit.
