### ISSUE TITLE
Install using FQDN instead of IP or hostname breaks Fleet

### ISSUE THREAD

**Issue by stijnpieters** [Security-Onion-Solutions/securityonion#1899]
Did a clean install of a manager node, where I chose to access the webinterface through FQDN instead of hostname or IP.
A certificate is then generated for Fleet that has CN=hostname instead of full FQDN. This makes it so that the flags provider by the Kolide launcher installer have FQDN in them, but a certificate that's signed for hostname.

Kolide launcher then tries to connect to FQDN but cannot verify certificate as it's signed for hostname, resulting in an error.

A temporary fix was to change fleet_custom_hostname manually in global.sls and regenerating the installers. But this means Fleet does not work out of the box.

Suggestion to self-sign certificates using result from option IP/hostname/FQDN... instead of just hostname/IP

**Comment by jtgreen-cse** [comment]
I ran into parts of this issue, here's a link to the discussion:

https://github.com/Security-Onion-Solutions/securityonion/discussions/1530#discussion-25182

I think the generation of the cert does need to be a bit smarted about the various combinations of IP/hostname/FQDN.

**Comment by stijnpieters** [comment]
Your discussion is how I found the temporary fix ;-)

**Comment by defensivedepth** [comment]
Yep, this is on the list thanks @stijnpieters @jtgreen-cse

**Comment by stijnpieters** [comment]
Suggestion: Maybe add prompt to fill in /etc/salt/minion.d/signing_policies.conf with custom cert details? Like C={{ variable }} ST={{ variable }} etc.

file for reference:
[signing_policies.conf.txt](https://github.com/Security-Onion-Solutions/securityonion/files/5530698/signing_policies.conf.txt)
