### ISSUE TITLE
partition usage reached 100% in Security Onion 2

### ISSUE THREAD

**Issue by demronan22** [Security-Onion-Solutions/securityonion#1928]
Hi Doug/Team,

Good Day everyone

We executed the Security Onion in our environment last Friday, Nov 13. However, after several days, we encountered an error stating "partition usage reached 100" this via wazuh email notification. 

We tried to fix it by running so-elastic-clear to clean up the disk space. However, in running this command the kibana still don't work properly together with its services.

We tried to search any related issue in the community but still the same error. Please help us in this issue.

Thank you,
Dem

**Comment by dougburks** [comment]
It looks like you've already created a Discussion for this:
https://github.com/Security-Onion-Solutions/securityonion/discussions/1929

Closing this issue.

**Comment by demronan22** [comment]
Sorry Doug just to test my other account.
