### ISSUE TITLE
2.3.2 installer fails when bios is in UEFI mode

### ISSUE THREAD

**Issue by sdanieru** [Security-Onion-Solutions/securityonion#1940]
When attempting to install from the 2.3.2 ISO onto a system in UEFI mode, the installer fails with:

storage configuration failed: Failed to find a suitable stage1 device: EFI System Partition cannot be of type xfs.; EFI System Partition must be mounted on one of /boot/efi.; EFI System Partition cannot be of type lvmpv.; EFI System Partition cannot be of type biosboot.

My storage situation is:
sda - 240GB SATA SSD (for OS)
sdb - 1.9TB SATA SSD (for NSM)

if I switch the bios to legacy, I can proceed with the installation w/ no issue.

**Comment by alkampfergit** [comment]
Same for me, everything is perfect in Hyper-V generation 1 machine and the very same error using generation 2, machine with UEFI.

**Comment by TOoSmOotH** [comment]
This is now fixed in 2.3.10
