### ISSUE TITLE
PCAP loses color coding when opening multiple tabs

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#1964]
### Summary
If I'm in Alerts or Hunt and I open a PCAP transcript in a new tab, it renders correctly. If I then open a second PCAP transcript in a new tab, the second PCAP tab renders correctly, but the first PCAP tab loses its color coding and font styling.

### Example
First PCAP tab:
![image](https://user-images.githubusercontent.com/1659467/99452067-133e2000-28f1-11eb-81a1-71755b186083.png)

Second PCAP tab:
![image](https://user-images.githubusercontent.com/1659467/99452114-251fc300-28f1-11eb-8c26-dbc519799c15.png)

Back to first PCAP tab:
![image](https://user-images.githubusercontent.com/1659467/99452135-2c46d100-28f1-11eb-8ed2-f51f3e55f387.png)

**Comment by jertel** [comment]
Resolved by filtering job publication events upon reception.
