### ISSUE TITLE
FEATURE: check manager services (salt-master, so-status) during setup on a node

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#1978]
We should check to ensure necessary services are running on the manager node before attempting to join a node to the grid.

**Comment by jertel** [comment]
Consider adjusting `so-status` to return an exit code of 0 if all is green, 1 if green or pending/starting, or 2 if at least one is missing/error. Additionally a -q flag could skip the output to stdout.

Then, before joining a node to the manager first ssh into the manager and exec so-status. Any result other than 0 show a prompt to the user on the new node stating that the manager isn't ready. Then retry a 3 times with a 30 second interval, and finally show a whiptail prompt allowing the user to retry or cancel setup.
