### ISSUE TITLE
Import node so-status should not show ERROR for zeek, steno processes

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1998]
Should say pending instead of ERROR:

![image](https://user-images.githubusercontent.com/16639611/99691044-c96f4a00-2a56-11eb-8eba-bd8acd20575c.png)

**Comment by jertel** [comment]
I'm showing that is currently shows DISABLED, which is sufficient. Based on that I think you can close this @m0duspwnens .

**Comment by m0duspwnens** [comment]
looks like this was taken care of in December and not closed: https://github.com/Security-Onion-Solutions/securityonion/commit/96b72d46be65d8becd1346c649bcd50355249e7e#diff-ca99a3ca7c43195ef7d865d3923b96098b184947608f1227f13db8dccdeccc09
