### ISSUE TITLE
Do not allow so-setup to run if apt/yum is already running in the background

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#2000]
If so-setup starts soon after an Ubuntu machine is started then apt could still be updating in the background. Setup should detect this and exit with an error and advise the user to retry.

Look for similar changes that might be needed in CentOS for Yum.

**Comment by defensivedepth** [comment]
https://github.com/Security-Onion-Solutions/securityonion/issues/735

**Comment by jertel** [comment]
Closing this duplicate issue.
