### ISSUE TITLE
Make SOUP proxy aware

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#2019]
I have security onion setup in a lab environment. When I try to upgrade to 2.3.10, I get the follow error.

Downloading so-acng
Error response from daemon: Get https://quay.io/v2/: remote error: tls: handshake failure
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   543  100   543    0     0   1034      0 --:--:-- --:--:-- --:--:--  1036
There is a problem downloading the so-acng:2.3.10 image. Details:

gpg: Signature made Thu 12 Nov 2020 09:49:04 PM UTC using RSA key ID FE507013 gpg: BAD signature from "Security Onion Solutions, LLC <info@securityonionsolutions.com>"

In my lab, everything runs through an SSL/TLS intercept proxy (outside of my lab) before going to the internet. To try to resolve some of the ssl/tls error because of the intercept proxy, I have setup another proxy inside that lab. If tls/ssl breaks, I send through my proxy which does not get intercepted by the SSL/TLS intercept proxy. 

However, when I setup the proxy config in Security Onion, it doesn't look like soup is honoring the proxy settings when trying to update docker containers. Is there an additional setting that I need to send the container updates through my proxy?

Joe

_Originally posted by @joeb1kenobe in https://github.com/Security-Onion-Solutions/securityonion/discussions/2017_

**Comment by abs0248** [comment]
> I have security onion setup in a lab environment. When I try to upgrade to 2.3.10, I get the follow error.
> 
> Downloading so-acng
> Error response from daemon: Get https://quay.io/v2/: remote error: tls: handshake failure
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 100 543 100 543 0 0 1034 0 --:--:-- --:--:-- --:--:-- 1036
> There is a problem downloading the so-acng:2.3.10 image. Details:
> 
> gpg: Signature made Thu 12 Nov 2020 09:49:04 PM UTC using RSA key ID FE507013 gpg: BAD signature from "Security Onion Solutions, LLC [info@securityonionsolutions.com](mailto:info@securityonionsolutions.com)"
> 
> In my lab, everything runs through an SSL/TLS intercept proxy (outside of my lab) before going to the internet. To try to resolve some of the ssl/tls error because of the intercept proxy, I have setup another proxy inside that lab. If tls/ssl breaks, I send through my proxy which does not get intercepted by the SSL/TLS intercept proxy.
> 
> However, when I setup the proxy config in Security Onion, it doesn't look like soup is honoring the proxy settings when trying to update docker containers. Is there an additional setting that I need to send the container updates through my proxy?
> 
> Joe
> 
> _Originally posted by @joeb1kenobe in #2017_

Hi.i used proxy on SO for a long time and it was so challenging. First the proxy setting on `/etc/environment` or using `export HTTP_PROXY ` only let native package manger (YUM/APT) aware of the proxy setting.as most SO packages are now docker images , you need to make docker aware of proxy setting. The SO howto-docs page about how to make docker aware of proxy setting is wrong or at least didn't worked for me both on SO-16.0.4 and the new SO-2.x . to make the docker update images via proxy : 

sudo mkdir /etc/systemd/system/docker.service.d/

sudo vi  /etc/systemd/system/docker.service.d/http-proxy.conf

# add the following lines to the http-proxy.conf file 

Environment="HTTP_PROXY=http://x.x.x.:3128/" "NO_PROXY=localhost,127.0.0.0/8,172.16.0.0/12"

sudo systemctl daemon-reload
sudo systemctl restart docker
sudo systemctl status  docker

some tips : you motioned that your are using some sort of TLS inspection in your env.if you are using MITM for TLS-Decryption , becuase the CERT will replaced by your proxy , no update will work as the cert is different .

**Comment by petiepooo** [comment]
I haven't needed to deploy SO2 behind a squid proxy yet, but expect to need to soon, as I have installed SO-16.04 (and SO-14.04) on several such systems in the past.  I don't think this is extraordinarily uncommon, as limiting outbound connections from servers is a fairly common IT practice, especially for security gear.

If your developers/QA group has the bandwidth, please test an install where the node has no direct internet access, and requires a proxy server for all outbound connections (other than DNS).

**Comment by dougburks** [comment]
Initial proxy support was added in 2.3.40 and improved in 2.3.50.  For more information, please see:
https://docs.securityonion.net/en/2.3/release-notes.html
https://docs.securityonion.net/en/2.3/proxy.html
