### ISSUE TITLE
SOC Alerts - "Refresh" button

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#2021]
Add a `Refresh` or `Update` button to SOC Alerts.

**Comment by greatapoc** [comment]
Would it be possible to also have a real-time view to view alerts as the come in?

**Comment by jertel** [comment]
> Would it be possible to also have a real-time view to view alerts as the come in?

Real-time views is something we're thinking through, but no ETA at this time.
