### ISSUE TITLE
Updates: Document External IPs/URLs for Whitelisting

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#2046]
We are using a proxy to connect our grit to the internet and are trying to update to 2.3.10.
The last time we updates our system half of the installation went fine but the other half couldn´t be downloaded. So we´ve got an broken installation and reinstalled our grit.

Which sites or IPs do I have to whitelist in our proxy/firewall that running `soup `or` so-rule-update` works properly?

_Originally posted by @martin8615 in https://github.com/Security-Onion-Solutions/securityonion/discussions/2042_

**Comment by dougburks** [comment]
Documented here:
https://docs.securityonion.net/en/2.3/faq.html#what-connectivity-does-security-onion-need-to-stay-up-to-date
