### ISSUE TITLE
Telegraf hardcoded to use https and is not aware of elasticsearch features

### ISSUE THREAD

**Issue by trocade** [Security-Onion-Solutions/securityonion#2061]
When running so-features-enable the configuration of telegraf is not changed and it continues to try to communicate via https to elasticsearch:

`2020-11-24T09:43:00Z E! [inputs.elasticsearch]: Error in plugin: Get https://elasticsearch:9200/_nodes/stats: http: server gave HTTP response to HTTPS client`

https is hardcoded as it seems here:
`/opt/so/saltstack/default/salt/telegraf/etc/telegraf.conf`

```
{% elif grains['role'] in ['so-node', 'so-hotnode', 'so-warmnode', 'so-heavynode']  %}
 [[inputs.elasticsearch]]
   servers = ["https://{{ NODEIP }}:9200"]
   insecure_skip_verify = true
{% endif %}

```

A suggestion would be to perhaps have this code
```
{% elif grains['role'] in ['so-node', 'so-hotnode', 'so-warmnode', 'so-heavynode']  %}
 [[inputs.elasticsearch]]
{%- if FEATURES is sameas false %}
   servers = ["https://{{ NODEIP }}:9200"]
   insecure_skip_verify = true
{%- else %}
   servers = ["http://{{ NODEIP }}:9200"]
{% endif %}
{% endif %}

```

SO version: 2.3.10
Running on: Ubuntu 18.04 LTS
Installed via so-network-install

**Comment by TOoSmOotH** [comment]
Starting in 2.3.40 there is no more features.
