### ISSUE TITLE
Docs: Document Node to Manager Port Communication Reqs

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#2198]
Ex.

All nodes to manager:

- 3142 (Apt-cacher-ng) (if manager proxy enabled)
- 5000 (Docker registry)
- 8086 (influxdb)
- 4505 (Salt)
- 4506 (Salt)
- 5644 (Filebeat -> Manager)
- 443 (Sensoroni)
- 8080 (Osquery) (if OSQ enabled)

Search nodes from/to manager:

- 9300 (ES node-to-node for nodes running Elasticsearch)
- 9696 (Redis)

**Comment by dougburks** [comment]
Documented here:
https://docs.securityonion.net/en/2.3/firewall.html
