### ISSUE TITLE
Suricata 6

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#2199]
https://suricata-ids.org/2020/10/08/suricata-6-0-0-released/

https://www.openinfosecfoundation.org/download/suricata-6.0.0.tar.gz

**Comment by dougburks** [comment]
https://forum.suricata.io/t/suricata-6-0-1-5-0-5-and-4-1-10-released/883

https://www.openinfosecfoundation.org/download/suricata-6.0.1.tar.gz

**Comment by TOoSmOotH** [comment]
[suricata.yaml.gz](https://github.com/Security-Onion-Solutions/securityonion/files/5771885/suricata.yaml.gz)
