### ISSUE TITLE
Integrate evtx into Import Node

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#2206]

**Comment by commandline-be** [comment]
can specifics as to what this issue is about be shared ? also what the current state of things is ?

does it makes sense to import .evtx converted to text or xml into elastic at all at this point ?

**Comment by defensivedepth** [comment]
@commandline-be this should give you some context - let me know if you have any other questions:

https://github.com/Security-Onion-Solutions/securityonion/discussions/2194#discussioncomment-147111

**Comment by mmasino-matc** [comment]
Any updates on where this at for the import node?

**Comment by defensivedepth** [comment]
Progress is being made - the changes we needed for SO integration have been merged upstream: https://github.com/sumeshi/evtx2es/pull/5

**Comment by launchdaemon** [comment]
Hi @defensivedepth, thanks for your working in getting this merged upstream.  Is there any further progress in bringing the functionality in to Security Onion as this is something I would specifically like to be able to do?

I am happy to try helping to test or troubleshoot anything if needed.

**Comment by defensivedepth** [comment]
@launchdaemon Should have an update out for this soon!

**Comment by defensivedepth** [comment]
Initial functionality added with https://github.com/Security-Onion-Solutions/securityonion/pull/5527
