### ISSUE TITLE
Allow to configure transport.ping_schedule on remote seed level

### ISSUE THREAD

**Issue by trocade** [Security-Onion-Solutions/securityonion#2255]
I have been having some issues with latency and connection drops towards remote locations.

I have solved this by adding this to the locations where I have issues:
`"transport.ping_schedule": "30s"`

But this is of course overwritten when a new site is added or the config is updated, so it would be nice if this could be optional to set in salt per location.

Release: 2.3.10
OS: Ubuntu 18.04 LTS
Install: network install

**Comment by TOoSmOotH** [comment]
@trocade Is this in elastic for remote heavy nodes?

**Comment by trocade** [comment]
It is in the configuration of the manager elasticsearch.

So it can either be a generic setting for the whole cluster, but in this case I think it should be good to also set per indivual remote cluster as in:

```
PUT _cluster/settings
{
  "persistent": {
    "cluster": {
      "remote": {
        "cluster_one": {
          "seeds": [
            "127.0.0.1:9300"
          ],
          "transport.ping_schedule": "30s"
        }
      }
    }
   }
}
```

**Comment by TOoSmOotH** [comment]
Will address in #1257
