### ISSUE TITLE
FEATURE: Wazuh App Support

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#237]
Consider supporting, or provide a guide on how to install/use Wazuh App

**Comment by 8ear** [comment]
Since Kibana is in version 7.9.3 an upgrade to Wazuh v4 is required.

**Comment by metapolitics** [comment]
Maintaining version alignment between elasticsearch/kibana & the Wazuh manager is key to being able to integrate the kibana plugin. The [version matrix is here](https://github.com/wazuh/wazuh-kibana-app#wazuh---kibana---open-distro-version-compatibility-matrix).

Upgrading Wazuh to v4.1 is required before this gets a look in

Related: #1748

**Comment by vijaytejak** [comment]
Hi team, any update on this implementation

**Comment by SICKFREDO** [comment]
Hi can we please get an update on this?

**Comment by b4b857f6ee** [comment]
Hello,
Having the wazuh kibana UI, can be so good!

**Comment by gitmffonseca** [comment]
This would be really nice to have!

But I'm afraid that we will have it only next year (maybe)!!!

Besides being in Priority Backlog, it's being postponed since 17 March 2021!!!  #1748

**Comment by UMHB-InfoSec** [comment]
@weslambert:

I know it is a bit of bad form to @ you directly and I apologize for the inconvenience.  BUT, adding the wazuh app in kibana as a optional add-on to a SO deployment would be AMAZING.

Please add support for this, it would be a fantastic addition.  I will personally send you some coffee money to sweeten the deal!

**Comment by b4b857f6ee** [comment]
We need it <3

**Comment by john-mathew-itt** [comment]
We definitely need this one.
