### ISSUE TITLE
Setup: Add input validation for static IP details

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#2407]
We need to  perform input validation for the static IP details in setup.  Currently, a user can accidentally pass through the prompt with the default X.X.X.X value(s), or configure a mistyped/invalid subnet mask.  It's suggested to perform validation for at least:

- IP Address
- Gateway address
- Subnet Mask

**Comment by rwwiv** [comment]
Covered by #1065
