### ISSUE TITLE
Consider ejecting ISO after installation completes

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#2436]
I've noticed that SO that does not eject the ISO disc automatically before reboot.

![image](https://user-images.githubusercontent.com/71960097/102855705-17191100-4460-11eb-81a0-a71efafb3ed0.png)

Is this common? The reason I'm asking is certain distro will eject ISO automatically before reboot.

If I did not remove the disk from virtual drive, the installation process will keep going on in an infinity loop.

_Originally posted by @w0lfcat in https://github.com/Security-Onion-Solutions/securityonion/discussions/2419_

**Comment by dougburks** [comment]
Could this be as simple as changing https://github.com/Security-Onion-Solutions/securityonion-builds/blob/master/iso-resources/ks.cfg#L35 to `reboot --eject`?

Reference:
https://www.redhat.com/archives/kickstart-list/2007-August/msg00012.html

**Comment by TOoSmOotH** [comment]
We can do that but not sure it does anything for a virtual cdrom or a USB drive. Maybe just change the wording? Ubuntu tells you to remove the disk then hit enter.

**Comment by dougburks** [comment]
I think when the Ubuntu installer display this prompt:
![image](https://user-images.githubusercontent.com/1659467/103150581-86824f80-4743-11eb-859a-f93c298a5dcb.png)

it has actually run the [eject](https://linux.die.net/man/1/eject) command as my VM no longer sees the media in the virtual drive:
![image](https://user-images.githubusercontent.com/1659467/103150515-fb08be80-4742-11eb-9c84-fd6525c42554.png)
