### ISSUE TITLE
Playbook generated elastalert rules with wrong field names for winlogbeat

### ISSUE THREAD

**Issue by RedWolf74** [Security-Onion-Solutions/securityonion#2460]
SO version: 2.3.21
installed from ISO with v 2.3.10, updateted with soup

With v2.3.10 as well as v2.3.21, playbook generated elastalert rules use certain fields with the ".security" extension, which ist not, was the provided winlogbeat package submitts. Therefor the defined alerts never trigger.

i.e. Play #311
![image](https://user-images.githubusercontent.com/19188515/103170227-fb887e80-4842-11eb-9b89-0b80c15cc26b.png)

while removing the ".security" extension, the events match
![image](https://user-images.githubusercontent.com/19188515/103170254-46a29180-4843-11eb-887d-b76e4b977b14.png)

**Comment by RedWolf74** [comment]
forgot the generated elastalert rule:
query: (event.code.security:"1" AND winlog.channel.security:"Microsoft\-Windows\-Sysmon\/Operational" AND process.executable.security:"*\\reg.exe" AND process.command_line.security:("*query*" OR "*save*" OR "*export*") AND process.command_line.security:("*currentVersion\\windows*" OR "*currentVersion\\runServicesOnce*" OR "*currentVersion\\runServices*" OR "*winlogon\\*" OR "*currentVersion\\shellServiceObjectDelayLoad*" OR "*currentVersion\\runOnce*" OR "*currentVersion\\runOnceEx*" OR "*currentVersion\\run*" OR "*currentVersion\\policies\\explorer\\run*" OR "*currentcontrolset\\services*"))

**Comment by RedWolf74** [comment]
After executing a 'for F in `ls /opt/so/rules/elastalert/playbook/*.yaml`;do sed 's/.security:/:/g' /opt/so/rules/elastalert/playbook/$F | sudo tee /opt/so/rules/elastalert/playbook/$F;done';, playbook defined alert appear in the alerts section:
![image](https://user-images.githubusercontent.com/19188515/103213215-4b337c80-490d-11eb-81df-c9d749757204.png)

**Comment by OmerTirosh** [comment]
Hi @RedWolf74f. , 

The '.security' is the analyzer at the elasticsearch, and it has a problem.
I posted #2261, and they said they take look into it.

Hope more will be interested, so they will fix it.

**Comment by defensivedepth** [comment]
@OmerTirosh @RedWolf74 We have identified the problem and are currently working on a fix.

I have created an issue to track this: https://github.com/Security-Onion-Solutions/securityonion/issues/2483

**Comment by TOoSmOotH** [comment]
Tracking this under #2483
