### ISSUE TITLE
Refactor so-test to work with current image registry

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#2463]
Per #2452 and #2453, so-test no longer works since DockerHub does not host newer SO images.

Refactor the so-test script, the tcpreplay/init.sls to use the so-image-common library and eliminate any duplicated scripting logic between so-test and so-tcpreplay.

**Comment by rammyfzl** [comment]
Thanks for working on this. What can I do to get this up and running in my current SO build?

**Comment by jertel** [comment]
Several files were changed so it's not a simple drop-in replacement. If you are up for a challenge you could go through the commits to the dev branch and find those that mention so-test or so-tcpreplay. But there was no intention of backporting it to 2.3.21 so the recommendation is to wait for the next release, currently targeting a release sometime next month.

**Comment by cam98mac** [comment]
Thank you for working on this. I am also waiting on this to work through the training.
