### ISSUE TITLE
Optimize Filebeat for Send Bigger Amount of Data

### ISSUE THREAD

**Issue by OmerTirosh** [Security-Onion-Solutions/securityonion#2481]
Hi,

Currently Filebeat can send limited amount of data, because Filebeat configured with one worker for output.
In large scale scenario the Filebeat can't keep up with the amount of data ( the data sends in delay ), the solution for this is to add more workers means more data can be sent in parallel.

Also for optimize Filebeat, its recommended to increase the size of the memory queue with the size of the workers so they can pull data simultaneously. 
Best practice for the queue is considered as `queue.mem.events = 2 * worker * bulk size` and `bulk size = queue.mem.flush.min.events` . 
[See 'How To Tune Elastic Beats Preformance'](https://www.elastic.co/blog/how-to-tune-elastic-beats-performance-a-practical-example-with-batch-size-worker-count-and-more)

I think the best solution for this is to add the settings to the pillar file.

Thanks!

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/2701
