### ISSUE TITLE
Reserve Ports for Docker Proxy

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#2492]
Wazuh API server uses a listen port of 55000 which falls in the CentOS and Ubuntu ephemeral range. Adjust the /proc/sys/net/ipv4/ip_local_port_range values to avoid that port.

**Comment by dougburks** [comment]
`ip_local_reserved_ports` – list of comma separated ranges:
https://www.thegeekdiary.com/how-to-reserve-a-port-range-for-a-third-party-application-in-centos-rhel/

**Comment by weslambert** [comment]
Same with Strelka Frontend port 57314.
