### ISSUE TITLE
FIX: Avoid telegraf apparmor issues

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#2560]
Ossec creates ~5700 Daily Alerts for Apparmor Denied.

The Message looks like this:
{"timestamp":"2021-01-05T20:26:30.803+0000","rule":{"level":3,"description":"Apparmor DENIED","id":"52002","firedtimes":105,"mail":false,"groups":["local","syslog","apparmor"]},"agent":{"id":"001","name":"xxx","ip":"xxx"},"manager":{"name":"xxx-wazuh-manager"},"id":"1609878390.2230765","full_log":"Jan  5 20:26:30 xxx kernel: [2955743.701286] audit: type=1400 audit(1609878390.062:96652): apparmor=\"DENIED\" operation=\"ptrace\" profile=\"docker-default\" pid=26439 comm=\"telegraf\" requested_mask=\"trace\" denied_mask=\"trace\" peer=\"unconfined\"","predecoder":{"program_name":"kernel","timestamp":"Jan  5 20:26:30","hostname":"xxx"},"decoder":{"parent":"kernel","name":"kernel"},"data":{"status":"DENIED","extra_data":"ptrace"},"location":"/var/log/syslog"}

Which also creates an entry in /var/log/kern.log and syslog looking like this:

audit: type=1400 audit(1608077130.299:36612): apparmor="DENIED" operation="ptrace" profile="docker-default" pid=14562 comm="telegraf" requested_mask="trace" denied_mask="trace" peer="unconfined"

Now this creates a load of entries in those logs and unecessary spam in the alert view.
It seems similar to an older docker issue referenced here : https://github.com/moby/moby/issues/7276

Is this a known issue or something specific to my installation as i haven't seen any similar post so far?

_Originally posted by @Jus-R in https://github.com/Security-Onion-Solutions/securityonion/discussions/2543_

**Comment by cvfdblaze624** [comment]
I am having the same issue, I have even tried booting the docker container with apparmor disabled and it still seems to somehow load apparmor and trigger these alerts.  I have read posts about editing the default docker profile for apparmor but can't seem to find such a file on my system.  This doesn't seem to be causing any issues other than log spam.  Any fixes we are aware of?

**Comment by jaredatobe** [comment]
These two most recent comments in the telegraf project show a workaround ("--security-opt apparmor:unconfined" in docker-compose.yml). I do not know if this applies here, as there is no docker-compose.yml in the security onion install, and documentation does not seem to cover adding such flags.

https://github.com/influxdata/telegraf/issues/6574#issuecomment-785353410

**Comment by kmfreder1** [comment]
+1

**Comment by oscar-o-oneill** [comment]
Also reporting this showing up in my security onion install.

**Comment by mciantar** [comment]
Is there a way to fix this please?

**Comment by dougburks** [comment]
We will look into this issue as time allows. In the meantime, you should be able to tune the Wazuh rule to exclude those logs you don't care about:
https://docs.securityonion.net/en/2.3/wazuh.html#tuning-rules

**Comment by dougburks** [comment]
Tested and confirmed fixed in 2.3.110.

**Comment by oscar-o-oneill** [comment]
Great to hear this is fixed! I never did filter out all of these apparmor alerts... lol almost 2.5M alerts...
<img width="180" alt="image" src="https://user-images.githubusercontent.com/71148006/157277174-19c8a8c2-b828-4554-abec-24e83fecd603.png">

**Comment by dougburks** [comment]
This fix was too aggressive and has been reverted. I've updated the documentation with a simple rule that will silence this alert:
https://docs.securityonion.net/en/2.3/wazuh.html#apparmor-denied-alerts

**Comment by oscar-o-oneill** [comment]
Nice improvement to the documentation, @dougburks. Thank you! Will do that now.
