### ISSUE TITLE
Warn user when trying to use default "securityonion" as hostname

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#2580]
CC: https://github.com/Security-Onion-Solutions/securityonion/discussions/2568#discussioncomment-269469

**Comment by TOoSmOotH** [comment]
I am not sure what we can do here. Host names in a grid must be unique thus making the minion IDs unique.

**Comment by defensivedepth** [comment]
Yep agreed. Can we do a check in setup to see if a hostname or minionid will be duplicated?

**Comment by TOoSmOotH** [comment]
I think the best option would be to notify the user when using the hostname securityonion is not recommended.
