### ISSUE TITLE
Cannot Escalate or Acknowledge Alerts "Request failed with status code 400"

### ISSUE THREAD

**Issue by Cra5hedC0w** [Security-Onion-Solutions/securityonion#2595]
I cannot remove certain alerts from the SOC alert screen. When trying to escalate or acknowledge, the SOC log shows:

timestamp=2021-01-08T21:26:56.154071483Z level=error message="Failed request" contentLength=0 elapsedMs=86 error="No eligible events available to acknowledge" impl=*server.EventHandler method=POST path=/api/events/ack sourceIp=172.17.0.1:58628 statusCode=400

This issue is similar to issue #2462 

This is on SO 2.3.21

**Comment by jertel** [comment]
The referenced issue related to TheHive key mismatch, where-as the issue you raised relates to SOC performing an update on the ES datastore to mark an event as being acknowledged, yet ES responds that it found nothing to update. Unrelated to TheHive. 

What kind of installation/grid setup do you have SO deployed in? Ex: standalone? eval? distributed?

**Comment by Cra5hedC0w** [comment]
That is why I said this issue is "similar" vs. "related".  The issue (#2462) produces similar UI output to the user. 

My setup is standalone.

**Comment by jertel** [comment]
Does the error occur on all search results? For example if you don't specify any filters and then acknowledge a few randomly selected events does it fail with that same error on all of them? Any additional information you provide will help me better understand what might be happening.

**Comment by Cra5hedC0w** [comment]
The event seems to happen so far with only wazuh alerts. For example, when SCA was enabled, this generated many alerts that I was not interested in (50 plus). So going down the list fairly quick, filtered on Name, Module, it would hang on 3 or 4 of these alerts with an error, then 3 to 4 above them would acknowledge properly. Unfortunately I don't see a way to view these alerts on the alert screen via a different filter, to test if they would remove if filtered differently. The other filters are related to source/dest ip, in which case would not include Wazuh alerts. On the hunt screen, the only option is to escalate to the hive, and this includes alerts that have already been acknowledged. In the hunt screen, the same happens with an alert that can't be acknowledged (400 error).

**Comment by jertel** [comment]
I've spent about an hour trying to reproduce this, but haven't been able to reproduce it on my fresh standalone install; I can acknowledge ossec alert groups and individual ossec alerts without problem. Have you tried different time ranges, or very specific filters where only the one wazuh event is in the result set? Just trying to think of different ways to isolate this.

If you have any other details, logs, or screenshots you can share I will take another look. My public key is here, if needed: https://keybase.io/jasonertel.

I'll ask others to keep an eye out for this as well. If I can see it in action and have access to the machine it will be solved more quickly.

**Comment by TOoSmOotH** [comment]
Going to close this due to inactivity
