### ISSUE TITLE
Feature Request: Update so-allow to allow for salt and docker-proxy inbound communication.  

### ISSUE THREAD

**Issue by BustedSec** [Security-Onion-Solutions/securityonion#2628]
After much troubleshooting I've come to realize that a typical manager node install does not open all the needed ports to allow a new forward sensor to connect to it. The so-allow command does not have an option to open up ports 4505, 4506 (salt) and 5000 (pulling configs for docker images). I recommend updating the so-allow script so it can open these ports for users unfamiliar with iptables.  

These commands seem to fix it, substituting $ip for the IP
sudo iptables --wait -t filter -I INPUT 1 -p tcp --dport 4506 --source $IP --jump ACCEPT
sudo iptables --wait -t filter -I INPUT 1 -p tcp --dport 4505 --source $IP --jump ACCEPT
sudo iptables --wait -t filter -I DOCKER-USER 1 -p tcp --dport 5000 --source $IP --jump ACCEPT

**Comment by rwwiv** [comment]
Nodes **_should_** add the necessary firewall rules on the manager during install, are you not seeing this behavior?

**Comment by BustedSec** [comment]
Negative, I have multiple failed installs where salt communication times
out due to 4505and 4506 being closed and also where it failed to pull data
from the sensor on port 5000 when pulling down docker images.

**Comment by TOoSmOotH** [comment]
Are the IP addresses showing up in the minion pillar on the manager? That would be the only reason why the firewall ports would not be opened. Sounds like the issue is with the ssh connection via soremote. Can you provide a sosetup.log for a failed minion install?

**Comment by BustedSec** [comment]
The IP addresses are not showing up on the minion pillar on the manager but are showing up in grid on the web ui. I ran 'salt '*' pillar.items' and don't see sensor/ip of the forward sensor - this may explain why I'm not getting any logs forwarded from it.  I have attached my most recent sosetup.log  
[sosetup.log](https://github.com/Security-Onion-Solutions/securityonion/files/5816162/sosetup.log)
I don't have other logs available because I blow away failed installs to avoid running issues from re-installing and start fresh - but if there is a safe way to do a re-install without doing that let me know.

**Comment by TOoSmOotH** [comment]
According to the log it exists in the right place. /opt/so/saltstack/local/salt/firewall/hostgroups.local.yaml should have the ip listed under minions. Can you conifrm that?

**Comment by BustedSec** [comment]
it's got the LAN IP of the minion, but the minion would show up to the Manager under the WAN IP when establishing connections due to NAT settings. I just did another install, it seems to have connected ok. Not sure if it's sending over logs yet.

**Comment by BustedSec** [comment]
this new sensor is connected but not sending any logs. I temporarily spun down the first one. This one installed with no errors according to the install script. I was able to pull a pcap from the webui asking for traffic going to port 22, and it returned a few. So I know it's working - but when I check under Grafana it shows that it isn't getting any data from the sensor. Any advice on troubleshooting this?

**Comment by BustedSec** [comment]
and before you ask, yes, I have verified SPAN traffic works on the vswitch this vm is connected to.

**Comment by BustedSec** [comment]
I have verified there is traffic coming from the sensor going to the manager on ports 443 and 34018 and 23020 via a pcap from another machine attached to the same monitoring network. So it IS sending data or at least has a connection established.

**Comment by rwwiv** [comment]
It looks like the original scope of the issue has been resolved, if you're still unable to see network events please open a discussions post [here](https://github.com/Security-Onion-Solutions/securityonion/discussions/new).
