### ISSUE TITLE
Provide a means for users to add a text banner to the SOC login form

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#2647]
Is there anyway to add a login banner to the WebUI Login page?  If so where are the files located for that page and how can I do that?

Thanks

_Originally posted by @out-n-about in https://github.com/Security-Onion-Solutions/securityonion/discussions/2643_

**Comment by darth-drew** [comment]
Can someone point me in the direction of this code? I apologize, I have not figured out how to navigate to it myself from this page.

**Comment by innovate-support** [comment]
I'm running an exhaustive grep search on my Manager to see if I can figure out what file to edit.  I'll post back here if I find it.

**Comment by innovate-support** [comment]
After some searching it appears that my files are located in
`/var/lib/docker/overlay2/c7f239ecd9beb8aa0762a0cf96f1da0dea33f3282e546dde52f1daadef43b13c/merged/opt/sensoroni/html/`
I'm not sure if the long string of characters is random or static, so yours may be a different folder.

I was able to edit the login/index.html file on line 79 and added an image.  You could easily add whatever html code you wanted in there.

Here's a screenshot of what I put in mine.
![Screenshot from 2021-03-30 13-51-09](https://user-images.githubusercontent.com/20424476/113047900-21cdfb00-915f-11eb-8fc8-1666f11bb9d8.png)

**Comment by darth-drew** [comment]
Thanks for this. That string of characters does appear to be unique to you.

My concern with that file is that when the docker images get updated your unique string will change and your changes will get overwritten. I think there is likely a way to insert our edits before those files make it in to /var/lib/docker, but I have not found that yet. Perhaps someone else has found another solution.

**Comment by jertel** [comment]
Upgrading the SO nodes would likely destroy any customizations as have been suggested two comments above. See https://github.com/Security-Onion-Solutions/securityonion/discussions/3680 for an alternative solution coming in the next scheduled release.
