### ISSUE TITLE
Add parentheses to correlate functions in the hunt.actions.json file that contain multiple fields.

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion#2654]
When correlating events in Hunt, adding additional filters may cause no results to be returned.

Correlating on uid then adding a filter returns no results: 
Example:
"Cbks2b2YpAggp0JOFb" OR "1:UFPRpor9BNxhRwEIIEblxGelpTw=" AND event.dataset:"ssl" | groupby event.module event.dataset 

Wrapping the correlated events in parentheses returns results.
Example: 
("Cbks2b2YpAggp0JOFb" OR "1:UFPRpor9BNxhRwEIIEblxGelpTw=") AND event.dataset:"ssl" | groupby event.module event.dataset

Fixed the issue by making the following  in the hunt.actions.json file.
    "/#/hunt?q=(\"{:log.id.fuid}\" OR \"{:log.id.uid}\" OR \"{:network.community_id}\") | groupby event.module event.dataset", 
    "/#/hunt?q=(\"{:log.id.fuid}\" OR \"{:log.id.uid}\") | groupby event.module event.dataset", 
    "/#/hunt?q=(\"{:log.id.fuid}\" OR \"{:network.community_id}\") | groupby event.module event.dataset", 
    "/#/hunt?q=(\"{:log.id.uid}\" OR \"{:network.community_id}\") | groupby event.module event.dataset",

**Comment by jertel** [comment]
This has been pushed.
