### ISSUE TITLE
Update logic for determining max disk to use /nsm vs entire physical space

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#2737]
Currently the max log size is based off the physical disk size and not the size of /nsm causing issues for standalone.

**Comment by dougburks** [comment]
We need to make sure that LOG_SIZE_LIMIT gets set correctly in at least the following use cases:
- /nsm is a dedicated partition
- /nsm is NOT a dedicated partition but part of /

I have a standalone installation with a dedicated /nsm partition that is 147GB:
```
df -h /nsm
Filesystem              Size  Used Avail Use% Mounted on
/dev/mapper/system-nsm  147G  130G   17G  89% /nsm
```

LOG_SIZE_LIMIT should have been half of that 147GB, but instead it's 117:
```
grep log_size_limit /opt/so/saltstack/local/pillar/minions/standalone_standalone.sls 
  log_size_limit: 117
  log_size_limit: 117
```

For reference, here's what we do in 16.04:
https://github.com/Security-Onion-Solutions/securityonion-setup/blob/master/bin/sosetup#L124-L127
