### ISSUE TITLE
Fix: Curator should only run on manager when set to use true clustering.

### ISSUE THREAD

**Issue by OmerTirosh** [Security-Onion-Solutions/securityonion#2806]
Hi, 

Recently, Indexes from the last few days have been deleted, I checked the log files and found that they were deleted by the Curator delete_indices action. [The delete action](https://github.com/Security-Onion-Solutions/securityonion/blob/master/salt/logstash/pipelines/config/so/0010_input_hhbeats.conf) 

It is configured to delete Indexes by disk size of each node even though it should consider all nodes disk space [From curator docs](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/filtertype_space.html). 

For example, three es nodes with 3T disk space each, should delete old indexes when the total size of all Indexes reach 9T and not 3T as log_size_limit. 

Thanks!

**Comment by weslambert** [comment]
If you are referring to a traditional Elasticsearch cluster, we have not optimized deletion for that, but for single-node clusters which is the default deployment method for Security Onion.

**Comment by OmerTirosh** [comment]
I do refer to a elasticsearch traditional cluster.

I think it's a major issue,  the Curator should work for each cluster separately and in traditional cluster there should be one Curator running on the master node. 

I will try to contribute for this.

**Comment by TOoSmOotH** [comment]
Well you will need to set the log_size_limit to 9T on all the curator instances for now until its improved. You should be able to do something like this:

sed -i "s/  log_size_limit.*/  log_size_limit: 9000/g" /opt/so/saltstack/local/pillar/minions/*_searchnode.sls

Multiple curators running shouldn't cause an issue.
