### ISSUE TITLE
FIX: Properly handle unauthorized responses during API requests from SOC app

### ISSUE THREAD

**Issue by BustedSec** [Security-Onion-Solutions/securityonion#2908]
Security Onion 2.3 ManagerSearch node - accessing from WebUI - underlying OS is Ubuntu 18.04.

When logging in with a user account that has had it's password reset - redirected to /changes.json%3Fv#/ with a 404 after login.

**Comment by jertel** [comment]
Background requests, such as those to the API from the browser app, and which result in a failed request due to invalidated login session, will now cause the user to be redirected to the login screen.
