### ISSUE TITLE
Limit number of backup files in /nsm/backup/

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#2915]
On a prod box, I have backup files in /nsm/backup/ back to October 15. We need to limit the number of days of backups on the box.

**Comment by m0duspwnens** [comment]
https://github.com/Security-Onion-Solutions/securityonion/commit/7099ed4bf5fd7085e87e240cdbebdb3fe3e4b93f#diff-974ef131b6b9eb2d6a1f1e0679a2204326885c328e9fc14a0680d40425f23a7c
