### ISSUE TITLE
Add the ability to enable and disable rules with so-rules

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#2926]
Users are struggling with syntax and spacing when adding sids to disabled etc. Create a tool to take this out of the equation.

**Comment by BustedSec** [comment]
It's like you read my mind and created an issue for it without me even telling you. I didn't know developers were psychic

**Comment by rwwiv** [comment]
@BustedSec
If you'd like to test the tool out early, copy [this link's content](https://raw.githubusercontent.com/Security-Onion-Solutions/securityonion/feature/so-rules/salt/common/tools/sbin/so-rules) into `/usr/sbin/so-rules` on the manager (or alternatively, copy the script from the `feature/so-rules` branch of this repo - found under `securityonion/salt/common/tools/sbin`), then copy the following script somewhere onto the same system and run it as root:
``` sh
#!/bin/bash

. /usr/sbin/so-common

# Surround double curly braces in any minion pillar in single quotes so the pillars can be parsed as regular yaml

readarray -t minion_pillars <<< "$(find /opt/so/saltstack/local/minions -type f -name '*.sls')"
for pillar in "${minion_pillars[@]}"; do
  sed -i -r "s/ (\{\{.*}})$/ '\1'/g" "$pillar" 
done
```

**Comment by BustedSec** [comment]
Awesome I'll test it out later today
