### ISSUE TITLE
Setup hangs indefinitely attempting to setup thehive

### ISSUE THREAD

**Issue by petiepooo** [Security-Onion-Solutions/securityonion#2973]
Within thehive_init() function, attempts to connect to thehive will timeout with a diagnostic.  However, before calling that function, attempts to contact ElasticSearch will loop forever.
https://github.com/Security-Onion-Solutions/securityonion/blob/aa15f3ca4a00acd7f6d0af21c3627520f608f8d2/salt/thehive/scripts/hive_init#L63-L68

This seems to be the most common place for failure when the install scripts mess up the /etc/hosts file by removing the entry with the hostname as defined in /etc/hostname.

**Comment by jertel** [comment]
Both issues were addressed in mid December and are fixed in 2.3.30.
