### ISSUE TITLE
Administrative username password field allows user to remove text. 

### ISSUE THREAD

**Issue by j-bernal** [Security-Onion-Solutions/securityonion#3099]
During initial installation, using 2.3.21 iso, when prompted to create a new administrative user the password field and password verification field allows the user to delete the entire line of text.  This is a visual bug that does not affect the functionality of creating a user password.

![image (3)](https://user-images.githubusercontent.com/59663876/108897823-7fad7700-75e4-11eb-8560-871e926a2f4e.png)
![image (4)](https://user-images.githubusercontent.com/59663876/108897841-82a86780-75e4-11eb-82ed-993323529016.png)

**Comment by dougburks** [comment]
Does this fix need to be applied to other kickstart files like https://github.com/Security-Onion-Solutions/securityonion-builds/blob/master/iso-resources/kstrain.cfg?
