### ISSUE TITLE
FEATURE: Refactor docker_clean salt state to use loop w/ inspection instead of hardcoded image list

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#3113]
Currently the docker_clean/init.sls file hardcodes a static list of images to prune following a soup upgrade. This list represents the last duplication of the official image list defined in so-image-common. Refactor this salt state to instead invoke a new `so-docker-prune` script that is a wrapper to a new `prune_docker_images` function inside of `so-image-common`.

This new function should run `docker images | grep $VERSION_CUTOFF` and then `docker rmi` each stale image. VERSION_CUTOFF represents two versions in the past. Essentially after soup completes we only want the current images and the previous version images installed. All older images should be removed. Use an OLDVERSIONS list of stale versions if necessary but I would think there's a programmatic way to do this without having to remember to update the OLDVERSIONS list on every release.

**Comment by rwwiv** [comment]
The final version of the script gathers images with the same base name (i.e. so-\<image\>) together and removes all but the 2 most recent images from each group.
