### ISSUE TITLE
Elasticsearch: Ensure geo fields are corrrectly typed

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#3152]
Need to make sure geo fields are correctly typed so they can be used in maps, etc.

**Comment by RagnarSTS** [comment]
I know I'm sounding needy, but I know more people than just me have been frustrated by 2.x handing of geoip data. Are you able to provide a 10 step process for normal folk that don't eat and breathe kibana all day to fix this?  I've taken a stab at it a good dozen times, reloaded at least 4 times and just sort of feel defeated but still refusing to go back to 16.04 base.

**Comment by datlife** [comment]
Hi @weslambert ,

I can contribute if you don't have enough bandwidth for this. I am currently a user of SO for my homelab and super happy with it.
 
Digging through the code, it seems that one change we need is to update the index pattern in Kibana [0] and templates in ES [1] from `[source|destination]_geo` to `[source|destination].geo`. Someone has already run into a similar in here [2].

In SO, how should I reset Elastic / Kibana to reflect a new config change? 

[0] https://github.com/Security-Onion-Solutions/securityonion/blob/master/salt/kibana/files/saved_objects.ndjson
[1] https://github.com/Security-Onion-Solutions/securityonion/blob/master/salt/elasticsearch/templates/so/so-common-template.json#L126
[1] https://discuss.elastic.co/t/index-with-geo-point-entry-doe-not-show-up-in-maps-heatmap/252458

**Comment by weslambert** [comment]
Hi @datlife , thanks.   I've already tested the change  -- the issue lies more in how the data will be handled afterwards (there may be conflicts that will need to be resolved unless we were to have the older data deleted or wait until it rolls off or reindex to allow for aggregations on some of the related fields).  This change is planned for the next (upcoming) release.

**Comment by eric-holtzclaw** [comment]
Sorry I don't get why this is not working, GeoIP matter to me

**Comment by RagnarSTS** [comment]
@eric-holtzclaw  I'm with you.  I feel the bar for real world deployment and operation requires geoip and something to manage suricata rules.

**Comment by weslambert** [comment]
This should be fixed in the latest release.

**Comment by RagnarSTS** [comment]
Woot woot!  xoxo

**Comment by presianbg** [comment]
Whooo yeah indeed! 

To make it clear, @weslambert  are you talking about 2.3.120 or 2.3.110 ?

**Comment by dougburks** [comment]
Working in 2.3.110:
![image](https://user-images.githubusercontent.com/1659467/158464403-fb58d8e5-08e1-4506-b3a3-d1879a531047.png)

**Comment by presianbg** [comment]
@dougburks  I've just tried again and looks like the `Geospatial` field in my upgraded instance is still with underscore `_` :
![image](https://user-images.githubusercontent.com/2163486/158538056-69594454-825f-4256-8ada-4f8d7ca6340c.png)
And the plotting is not working.

Should I re-index or something to make ti work ?

**Comment by weslambert** [comment]
Did you add this field before the transition to .110? IIRC, we were using `destination_geo.location` before the release. 

Regardless, you'll need to do one of the following:

- Wait until the data rolls off/delete older conflicting indices
- Close conflicting indices (should work, although haven't tested)
- Re-index

**Comment by presianbg** [comment]
@weslambert I haven't touched anything in the elastic config since the original installation (2.3.30 IIRC).
I will wait all of my indexes to be rolled off and check again. 

Cheers,
PY
