### ISSUE TITLE
Include so-analyst RPMs on the ISO image for airgap

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#3160]
Allow users to install a Analyst Workstation in an airgap environment.

**Comment by TOoSmOotH** [comment]
One idea here is to have a smaller ISO that could be used for remote sites as well as analyst workstation for airgap

**Comment by dougburks** [comment]
This was completed in 2.3.120:
https://blog.securityonion.net/2022/04/security-onion-23120-now-available.html
https://docs.securityonion.net/en/2.3/release-notes.html#changes
