### ISSUE TITLE
[Feature Request] Modular PCAP capture and sniff

### ISSUE THREAD

**Issue by cyberpika2** [Security-Onion-Solutions/securityonion#323]
USE CASE:
I am testing HH for battlefield forensics / triage IR use cases from a quick live-host forensics collection where time is a factor (like a field agent messed with squirrels, fire, or zombies).
All you have are evil files, .evtx logs, and registries.

REQUEST:
1. Modularize the pcap/snort functionality during installs like other options, sometimes we will just need elk, strelka, node, and thehive so as to save cpu cycles and keep all-the-things tidy.

**Comment by weslambert** [comment]
Hi @cyberpika2 , and thanks for this issue.  This should eventually make its way in; with the current platform we have the ability to disable or only enable pcap, so we will aim to mirror the same functionality here.

**Comment by TOoSmOotH** [comment]
fixed in #1601
