### ISSUE TITLE
[Feature Request] Local cli import tool .evt / .evtx to logstash

### ISSUE THREAD

**Issue by cyberpika2** [Security-Onion-Solutions/securityonion#325]
USE CASE:
Analyzing host logs from archived data relevant to your current case - just a drive with windows .evt / .evtx logs as host was imaged already.
Host is critical to the org and cannot be taken offline or is physically in-accessible and cannot be modified.

REQUEST:
Local .evt / .evtx logstash importing cli tool.

(I have tested evtxtoelk.py but it crashes the max fields sometimes so i have to delete the offending log file and redo it multiple times. Corruption maybe?)
I am unaware of any other linux tool that can. I use current SO for this functionality too.

I'll continue testing and giving feedback / suggestions. TY!

**Comment by weslambert** [comment]
Hi @cyberpika2 , thanks for this issue.  I'm currently working on something similar to this -- I'll run through some testing as I get time and keep you updated.

**Comment by TOoSmOotH** [comment]
#2206
