### ISSUE TITLE
DNS assignment consistency

### ISSUE THREAD

**Issue by darth-drew** [Security-Onion-Solutions/securityonion#3313]
2.3.30 DNS assignment consistency issue:

During Fresh install "configure networking only" DNS assignment requires a comma separator.
During Fresh install "SO install" DNS assignment requires space.

I know.. picky..

**Comment by rwwiv** [comment]
I think you're referring to DNS servers vs home net CIDR blocks needing spaces and commas, respectively. This was standardized to commas by commit 4dc3a6a, so I'm closing this issue.

If you're still seeing behavior like this please provide screenshots showing the different requirements and we'll look at getting it fixed.
