### ISSUE TITLE
2.3.30 Standalone Install enhancement

### ISSUE THREAD

**Issue by andrewalbertson93** [Security-Onion-Solutions/securityonion#3314]
SO Standalone Install still prompts user for grid input.
How would you like to download OS package updates for your grid?
- Manager
- Open

Set password for soremote user. This account is used for adding sensors remotely.

Are these prompts still necessary/useful?

**Comment by TOoSmOotH** [comment]
Yes because you can add sensors, search nodes, and heavy nodes to a standalone deployment.
