### ISSUE TITLE
2.3.30 can't have a "$" in the password at installation

### ISSUE THREAD

**Issue by woodts** [Security-Onion-Solutions/securityonion#3318]
This is simple to reproduce.  Perform a fresh installation of 2.3.30 from the ISO.  Give the installer a password with a "$" in it.  The password that will be set is the password provided truncated at the "$".

**Comment by ktothelohello** [comment]
Yes we discovered this issue when adding a new user.
The SOC allows that type of password but TheHive and Fleet won't allow it.

**Comment by dougburks** [comment]
Closing this issue in favor of https://github.com/Security-Onion-Solutions/securityonion/issues/4249
