### ISSUE TITLE
FIX: SMTP shoud read SNMP on Kibana SNMP view

### ISSUE THREAD

**Issue by rosswakelin** [Security-Onion-Solutions/securityonion#3413]
The circular SNMP version graph on the Kibana Network Data -> SNMP dataset has a title of SMTP - it should read SNMP
![image](https://user-images.githubusercontent.com/22168385/110883809-ebb00f00-8348-11eb-90b8-ccfd05c94549.png)

**Comment by dougburks** [comment]
Hi @rosswakelin ,

Thanks for reporting this issue. It should be resolved in the upcoming 2.3.40 release.
