### ISSUE TITLE
FEATURE: soup should check for OS updates

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#3489]
We recently added a note to soup about OS updates (https://github.com/Security-Onion-Solutions/securityonion/issues/3486):
```
Please note that soup only updates Security Onion components and does NOT update the underlying operating system (OS). When you installed Security Onion, there was an option to automatically update the OS packages. If you did not enable this option, then you will want to ensure that the OS is fully updated before running soup.
```

The next step is for soup to actually check for OS updates.

**Comment by TOoSmOotH** [comment]
We would need it to push a yum/apt update to all minions.

**Comment by TOoSmOotH** [comment]
This is to inform the user that they are missing OS updates and that they should remedy that.
