### ISSUE TITLE
FEATURE: setup should run so-preflight

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#3497]
Now that we have a pre-flight check (https://github.com/Security-Onion-Solutions/securityonion/issues/3025), we should update Setup to run it automatically. This would most likely need to be after the user has entered all input into Setup but before Setup makes any changes to the system. If user chooses Airgap, we shouldn't run so-preflight (or maybe so-preflight needs special logic for airgap so that it can test nodes connecting to manager but not check for any Internet resources). Otherwise, run so-preflight, show the output to the user, and give them the opportunity to exit Setup before making changes.

**Comment by weslambert** [comment]
Also consider enhancing preflight check to include something like the following:

Set initial firewall policy here:
https://github.com/Security-Onion-Solutions/securityonion/blob/master/setup/so-setup#L594-L596

Then wait for firewall config to be applied for the node that is joining the grid (ensure the state completed on manager), then check everything we just applied.

Ex. A function to do something similar to the following (populating ports, based on role):

```
for port in 443 3142 4505 4506 5000 5644 8086 9200 9300 9696; do
      nc -vzw 5 $manager $port
      status=$?
      if [[ $status -ne 0 ]]; then
        echo “Unable to connect to $port -- please ensure proper connectivity is in place.”
        exit 1
      fi
done
```

This could be done before other configuration to ensure connectivity for all ports were in place before proceeding with the rest of the install

**Comment by TOoSmOotH** [comment]
airgap does not use this. Have to factor in proxy configs.
