### ISSUE TITLE
FIX: so-ssh-harden needs improvement

### ISSUE THREAD

**Issue by rwwiv** [Security-Onion-Solutions/securityonion#3600]
Changes to be made: 

- [x] Change when script runs during setup
- [x] Test a temp config rather than make changes to the live config file (i.e. don't append directly to `/etc/ssh/sshd_config`)
- [x] Don't add lines if they already exist in the config

**Comment by jertel** [comment]
Also, ensure so-ssh-harden is not invoked unless the system was actually installed. And ensure it's included during automated tests.

![image](https://user-images.githubusercontent.com/16639611/112537130-b6fa7980-8d84-11eb-9ad1-6d444a98b97b.png)
