### ISSUE TITLE
Document HW requirements for each component (RAM, CPU, free space)

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#364]
For example:

[  ]  Fleet - 1GB
[  ] Playbook - 1.5GB

**Comment by defensivedepth** [comment]
As of now, I am seeing the following:
-Grafana: <128MB
-Fleet + Redis: < 256MB
-Playbook + Navigator:  < 1GB
-TheHive + Cortex: around 1.6GB

**Comment by rwwiv** [comment]
Instead of listing this during setup we've decided it would be better to include this information in the documentation.
