### ISSUE TITLE
FEATURE: Provide customizable Login page banner content using markdown format

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#3659]
Follows same customization process as described on the default Overview tab, except using banner.md file instead of motd.md.

Content will appear immediately above the Username input field on the login page.

**Comment by xfaith** [comment]
I know this is old, but can we get this added to the doc.s.

**Comment by dougburks** [comment]
Done:
https://docs.securityonion.net/en/2.3/soc-customization.html#login-page
