### ISSUE TITLE
Email: Provide stats/alerting via email

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#377]
Outside of Elastalert and other applications possessing native email/alerting mechanisms, we should provide a method to easily configure emails/alerts (similar to so-email in current platform).

**Comment by IntegrityGit6580** [comment]
This feature is the only thing preventing me from migrating a small lab to version 2 (as there are no users monitoring the alert queue manually, email alerts are sent for top priority NIDS/etc alerts).
Thank you for logging it!

**Comment by poobar** [comment]
This feature is the only thing preventing me from migrating a small lab to version 2 (as there are no users monitoring the alert queue manually, email alerts are sent for top priority NIDS/etc alerts). I expect this is the same for most home users. 
Thank you for logging it!
