### ISSUE TITLE
FEATURE: Allow for the installation of zeek packages

### ISSUE THREAD

**Issue by deathnmind** [Security-Onion-Solutions/securityonion#3847]
FIX:

Please create an empty "custom" folder on manager node for Zeek custom packages.  

Further clarify the instructions to add a Zeek custom package on readthedocs.  This should clarify that all custom Zeek packages need to be in "/opt/so/saltstack/local/salt/zeek/policy/custom", because this location is a mapped volume to the zeek docker and custom packages will not work unless they are in the correct folder.

**Comment by TOoSmOotH** [comment]
We currently do not support installing Zeek packages. We will need to create a framework to allow this.

**Comment by deathnmind** [comment]
The docs say you do support it... https://docs.securityonion.net/en/2.3/zeek.html?highlight=custom%20zeek#custom-scripts

But the default "/opt/so/saltstack/local/salt/zeek/policy/custom" is not created (on a Manager node at least) and it isn't clear from the instructions that packages need to be in this folder.  

However on line 193 of https://github.com/Security-Onion-Solutions/securityonion/blob/master/salt/zeek/init.sls you can see that this is mapped volume through docker to zeek.

This could be explained better in the docs I think.

**Comment by deathnmind** [comment]
Created a pull request with edits to the Docs to clarify.
