### ISSUE TITLE
FEATURE: SOUP - Prompt user when local modifications are detected 

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#3860]
We should consider letting users know that we've detected local modifications to their applications' configuration that may affect their proper performance during an application/config update (for example if their local copy is not up-to-date with what the application requires, and it fails to start, etc).

This would be mostly applicable to items users have copied from the `default` to `local` directories.

**Comment by petiepooo** [comment]
This would make my life MUCH easier during upgrades!  Thank you.
