### ISSUE TITLE
FEATURE: Filebeat Modules Enablement

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#3877]
We should allow users to utilize FIlebeat's built-in modules to ease the onboarding of log sources.

The first run should include documentation around how to enable FB modules in `filebeat.yml`, as well as a script to load the associated pipelines.

Later, this can be simplified and automated through the use of [pillars](https://github.com/Security-Onion-Solutions/securityonion/issues/3859), and within the state.

**Comment by TOoSmOotH** [comment]
#3859
