### ISSUE TITLE
Playbook's osquery.template file is missing the play_id key

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#3974]
The osquery.template file that gets placed in `/opt/so/rules/elastalert/playbook` directory is missing at least the play_id key. This causes rules based on the osquery product type to fail to be submitted by Elastalert. The elastalert log file will show a stack trace error. Check other fields compared to generic.template to ensure nothing else is missing. Test by creating a new rule via Playbook, using the osquery example in the GUI and make sure it successfully creates new alerts in SOC.

**Comment by defensivedepth** [comment]
No longer needed - RE: Detections
