### ISSUE TITLE
FIX: Add event_data to Elasticsearch template(s)

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#4012]
Currently, the `event_data` field is not getting indexed as intended.

**Comment by Listerofsmeg** [comment]
Just to add to this, I'm seeing what I think is the result of this when looking at events in hunt.

As an example if I group by "winlog.event_data.TargetUsername" this works, but if I try and do the same to group alerts created with the data and group by "event_data.winlog.event_data.TargetUsername" I don't get the "most occurences" "fewest occurcences" graphs and group metrics is not available.

While this is on the fix list is there a work around we could implement ourselves? We've just started using Security Onion so still getting used to which bits handle what!

**Comment by weslambert** [comment]
> Just to add to this, I'm seeing what I think is the result of this when looking at events in hunt.
> 
> As an example if I group by "winlog.event_data.TargetUsername" this works, but if I try and do the same to group alerts created with the data and group by "event_data.winlog.event_data.TargetUsername" I don't get the "most occurences" "fewest occurcences" graphs and group metrics is not available.
> 
> While this is on the fix list is there a work around we could implement ourselves? We've just started using Security Onion so still getting used to which bits handle what!

In the meantime, you can modify the `so-common-template.json` file in `/opt/so/saltstack/default/salt/elasticsearch/templates/so`.  This will get overwritten during upgrades, but assuming there are no other changes to the file, it would be replaced with the correct template changes whenever your deployment is updated to the next version of Security Onion.  This may pose less risk than copying and overwriting, as you would be less likely to run into issue with overriding the default config.

For example, add the following to `/opt/so/saltstack/default/salt/elasticsearch/templates/so/so-common-template.json` under https://github.com/Security-Onion-Solutions/securityonion/blob/master/salt/elasticsearch/templates/so/so-common-template.json#L231:

```
"event_data":{
  "type":"object",
  "dynamic": true
},
```

Then restart Elasticsearch on your nodes.

The changes will be picked up once a new index is created.

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/4079
