### ISSUE TITLE
FEATURE: Mechanism for opening closed indices

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#4036]
We should provide a procedure/script for opening closed indices, including caveats for disk usage and current thresholds while Curator cron jobs are disabled:

Ex.

- Check if available disk percentage is enough to perform operation
- Stop salt-minion
- Stop Curator
- Open Index
- Provide search pattern
- Consider setting timer on how long index can remain open before start Curator and Salt minion again (to ensure data is getting managed as it should)

**Comment by TOoSmOotH** [comment]
ILM
