### ISSUE TITLE
FIX: Reconcile InfluxDB/Grafana containers in certain setup modes

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#4207]
SOC relies on InfluxDB to show node status (the green OK badge) on the Grid interface. Yet setup allows users to opt-out of installing Grafana. If this opt-out occurs, setup will also skip the installation of InfluxDB. The simple solution is to always install InfluxDB and potentially Grafana. However there is concern that this will impact hardware requirements for Import installations.

**Comment by TOoSmOotH** [comment]
For import eval mode we should disable the live system checks and go back to monitoring if sensoroni is connected. 

We should go ahead and enable influx and grafana for the rest of the modes since we will use the grafana API for alerting at some point.

**Comment by cyberkimh** [comment]
Hi we have that Grid error showing in the SOC also. 
We have a distributed deployment and I thought we had installed Grafana at installation on all our nodes (search and forward) and data for them is showing in the Grafana dashboard on the SOC, but when I **so-status** it doesn't show Grafana installed and there is no Grafana folder in  /opt/so/conf/ either search node or forward node.
I was wondering if you have any advice on reinstalling Grafana on the other nodes to hopefully remove that error on the Grid?

**Comment by jertel** [comment]
Hello, Grafana is installed on the manager node only, and is not installed on the search or sensor nodes.
