### ISSUE TITLE
Remove Zeek artifacts when switching to mdengine to Suricata  

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion#4221]
The grid interface in SOC displayed a fault message for all sensors after switching my metadata engine to Suricata.  The issue was fixed by removing so-zeek from /opt/so/conf/so-status/so-status.conf.  

Recommend verifying so-zeek docker container is stopped and so-zeek is removed from /opt/so/conf/so-status/so-status.conf if suricata is set as the mdengine.

**Comment by TOoSmOotH** [comment]
Fixed in 2.4
