### ISSUE TITLE
UPGRADE: Elastic to 7.13

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#4313]
Update Elastic to 7.13

**Comment by dougburks** [comment]
Release Notes for Elastic 7.13.0:

https://www.elastic.co/guide/en/elasticsearch/reference/7.13/release-notes-7.13.0.html

https://www.elastic.co/guide/en/logstash/7.13/logstash-7-13-0.html

https://www.elastic.co/guide/en/kibana/7.13/release-notes-7.13.0.html

**Comment by dougburks** [comment]
Release Notes for Elastic 7.13.1:

https://www.elastic.co/guide/en/elasticsearch/reference/7.13/release-notes-7.13.1.html

https://www.elastic.co/guide/en/logstash/7.13/logstash-7-13-1.html

https://www.elastic.co/guide/en/kibana/7.13/release-notes-7.13.1.html

**Comment by dougburks** [comment]
Release Notes for Elastic 7.13.2:

https://www.elastic.co/guide/en/elasticsearch/reference/7.13/release-notes-7.13.2.html

https://www.elastic.co/guide/en/logstash/7.13/logstash-7-13-2.html

https://www.elastic.co/guide/en/kibana/7.13/release-notes-7.13.2.html
