### ISSUE TITLE
FIX: git failing behind corporate proxy

### ISSUE THREAD

**Issue by gebhard73** [Security-Onion-Solutions/securityonion#4358]
Hi,

the older version of git shipping in the CentOS image (1.8.3.1-23) started to fail getting through the corporate proxy. It got stuck after `Resolving deltas: 100% (26067/26067), done.`

This happened in a `sudo soup` on SO 2.3.40 but could be reproduced by a simple `git clone <whatever repo>`

Using a newer version of git (e.g. from https://ius.io/setup) has fixed this. Example for workaround:

```
yum install https://repo.ius.io/ius-release-el7.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
yum remove git
yum remove perl-Git-1.8.3.1-23.el7_8.noarch
yum install git224

```

Perhaps we can include an updated version of git in SO?

Thanks & Regards,
Gebhard

**Comment by TOoSmOotH** [comment]
Rocky has the new version
