### ISSUE TITLE
FEATURE: Set minimum TLS version for registry to 1.2 to match nginx config

### ISSUE THREAD

**Issue by rwwiv** [Security-Onion-Solutions/securityonion#4403]
See distribution/distribution#3169 for merged PR that supersedes changing the config. This issue will remain open until a release is made with the linked code changes.

**Comment by rwwiv** [comment]
The relevant config option won't actually make it into a release until distribution/distribution#3380 is merged and 2.7.2 is released. Putting this on the back burner until that happens.

**Comment by Masaya-A** [comment]
2.8.0 has been released!
https://github.com/distribution/distribution/releases/tag/v2.8.0
