### ISSUE TITLE
FEATURE: Ability to disable Zeek, Suricata

### ISSUE THREAD

**Issue by abesinger** [Security-Onion-Solutions/securityonion#4429]
I want to comment on the post a while ago about disabling zeek and/or suricata on a sensor node.  I was able to implement the mod suggested here, it worked but Grafana reports an error because some services aren't running on the sensor: _Originally posted by @weslambert in https://github.com/Security-Onion-Solutions/securityonion/discussions/2205#discussioncomment-214755_

I'd like to submit a feature request that the installer prompt for what services one wants on a sensor node, or other means to easily choose. I'm looking doing a campus-wide deployment, where I'll want to e.g. run zeek on one set of sensors, suricata on another, etc.

**Comment by defensivedepth** [comment]
Closed with https://github.com/Security-Onion-Solutions/securityonion/pull/5566

Current implementation requires the following to be added to the Zeek / Suricata pillar (no Installer support at this time)
`enabled: true | false`
