### ISSUE TITLE
Add mapping to extracted file directory

### ISSUE THREAD

**Issue by j-bernal** [Security-Onion-Solutions/securityonion#4622]
The current file mapping for extracted files points to /zeek/extracted/complete/ and /nsm/strelka/staging/ however with Strelka enabled the file is ultimately stored in /nsm/strelka/processed/.

Add/modify mapping to point to the /nsm/strelka/processed/ file location.

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/4798
