### ISSUE TITLE
Kibana Issue: Saved Items with Search Strings

### ISSUE THREAD

**Issue by gebhard73** [Security-Onion-Solutions/securityonion#4626]
Hi,

this issue is to make SO aware of an IMHO tricky issue in Kibana regarding saved items including a search string. A fix is already in the works, I'd suggest including it as soon as possible because for IR it's not that rare to work with saved search strings:
https://github.com/elastic/kibana/issues/101574 

Thanks!
Gebhard

**Comment by TOoSmOotH** [comment]
We plan to keep up with the latest Elastic 7.X releases as they come out so when the fix is applied upstream we should get it.

**Comment by gebhard73** [comment]
Thanks @TOoSmOotH !
