### ISSUE TITLE
Trying to run LAMP server on SO box as a Reverse Proxy

### ISSUE THREAD

**Issue by gigantor2** [Security-Onion-Solutions/securityonion#4660]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/4642

<div type='discussions-op-text'>

<sup>Originally posted by **gigantor2** June 30, 2021</sup>
After further study I am back to my initial theory of trying to run the  SO Nginx server as a Reverse Proxy. I would like Nginx to be a front end server and forward all requests that come to 80/443 to my Lamp web server. Right now, any requests to the host on 80/443 are sent to the 80/443 Nginx container SO sign-in page. This is not good!!! 

I currently have SO 2.3.50 installed and running on Docker in a  centos server ("stand alone" server installed by ISO) I also have a LAMP web server installed (which was installed before SO). After the SO install all web requests went through to SO and would no longer get through to my LAMP server. Essentially, SO took over the host and is not letting requests through to my LAMP Containers on any port. My Lamp web server's port 80 and 443 are mapped to other ports on the host via my compose file, so even though SO owns port 80 and 443 on the host, I thought I would be able to get through on the other mapped ports. I have tried all kinds of schemes to get this to work ( putting mgmt port on second interface, and have the primary interface for LAMP, Having 3 interfaces. and allowing LAMP be primary) , but to no avail. I believe I need Nginx to forward those requests, or some kind of pass through to my LAMP server.

BTW- I have no errors, the lamp server is up, listening, and ready to accept requests like it was prior to the S.O. install. In addition, S.O. is accessible via my browser and appears that all applications I selected are available and working. However, I cannot access web pages via the browser without attaching the other mapped ports to the end of the URL. (192.168.1.100:8330) I can then access web pages, but that will not work in a operational environment. Persons accessing my site won't know to include a unique port.

My goal is to have security around my web server in a Docker environment. They both work well separately, but I need them to work together. I read something in my research about SO allowing apps to "PASS TROUGH," but after logging into the SO Nginx container  it appeared the code was just for the SO applications (Kibana, Wazuh, etc.). Am I wrong, can the code be added for my LAMP apps.

BTW-  I am happy SO is working so well and not allowing anything through to the server. This is exactly what I want it to do, protect my web server. I just want it block everything going anywhere else but the web server ( port 80 or 443). I don't want to have to have two servers at this point ( LAMP and SO, maybe at a later date), I would like them to work together in tandem on the same box. My reason for this is the cost of running two servers on a hosting service. 

Am I wasting my time and spinning my wheels, or can this be done by a novice like myself? Any help would thoroughly  appreciated.</div>

**Comment by gigantor2** [comment]
UPDATE!!! I think I talked myself into heading in the right direction. After further research I see a ton of information on creating reverse proxies with Nginx. After reading and watching a few videos, I think I just might be able to "pull this off!!!" I understand how all of this works theoretically, but working on the operational/technical side vs. theoretical security is very different. However, I love a good challenge.   🙂  All of my concerns above seem to point to using SO/ Nginx as a reverse proxy.  Anyway, thanks to anyone who is listening for allowing me to vent and talk this situation out in my mind. Cheers!!! 😊

**Comment by TOoSmOotH** [comment]
Please use your discussion post for this. This is not an issue.
