### ISSUE TITLE
"Attempting to connect to manager" message at top of console in standalone mode

### ISSUE THREAD

**Issue by jaredatobe** [Security-Onion-Solutions/securityonion#4746]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/4734

<div type='discussions-op-text'>

<sup>Originally posted by **jaredatobe** July  7, 2021</sup>
After installation using the ISO, while reviewing the freshly-installed Security Onion console, I see a message at the top. It toggles between "Attempting to connect to manager" and "Disconnected from manager" continuously, every few seconds. It's a standalone install. All is well according to so-status. Where should I look to begin resolving this?</div>

**Comment by dougburks** [comment]
Please keep all discussion in Discussions. Thanks!
