### ISSUE TITLE
FEATURE: so-firewall needs an option to run apply by itself

### ISSUE THREAD

**Issue by asinger-ncat** [Security-Onion-Solutions/securityonion#4765]
It would really be nice if so-firewall had an option to apply changes already made without having to make another one, e.g. something like "`so-firewall apply`"

As so-firewall is currently written, the` --apply` option only takes effect if one is also making a change, specifically `addport, removeport, includehost, excludehost, removehost` (note  also that addhostgroup and addportgroup ignore the `--apply` option.

 I understand the value of not applying changes automatically - it's faster/better to make all the changes I want to make before applying, especially when my workflow involves creating a new hostgroup and portgroup. But if I forget to include `--apply` on the last change (as I have just done 3 times now) it's a bit frustrating.  The only solution I see (besides hacking so-firewall) is to remove an entry, e.g. exlude a host, and then re-include the host with the `--apply` option.

Looking at the code it could be a pretty simple addition.

**Comment by jertel** [comment]
`so-firewall apply` will be supported in an upcoming release.
