### ISSUE TITLE
UPGRADE: TheHive to v4

### ISSUE THREAD

**Issue by Az0res** [Security-Onion-Solutions/securityonion#4831]
[TheHive4 ](https://blog.thehive-project.org/2020/07/27/thehive-4-0-is-out/)has been out for some time, and it contains many bug fixes and features that are needed to SO users.

**Comment by weslambert** [comment]
We are aware of TheHIve 4 , however, we have held off on integration for the time being because TheHive and Cortex have not been updated to use the same backend.
