### ISSUE TITLE
filebeat / redis: Need warning when data is dropped

### ISSUE THREAD

**Issue by gebhard73** [Security-Onion-Solutions/securityonion#4883]
It must be easily detectable when a component drops data so that queues can be optimized and the issue be fixed. Otherwise it would never be noticed, esp. when using UDP for the entry point into SO universe.

I haven't been able to figure out a way how to get this information for filebeat / redis:

For redis you may indirectly observe this by redis consuming max configureed memory / max queue length in Grafana. For filebeat I have found nothing.

Feature request: implement "some way" for filebeat / redis to complain about dropping data. Honestly I don't have any idea how.

Reference: https://github.com/Security-Onion-Solutions/securityonion/discussions/4796

**Comment by gebhard73** [comment]
I've just found out that there is a beat monitoring for Grafana, but it seems missing for standalone configuration. 
Perhaps we can add the beat monitoring to Grafana for standalone?

**Comment by TOoSmOotH** [comment]
Event monitoring is built into the influxdb dashboards alerts
