### ISSUE TITLE
filebeat: make pipelining configurable in minions file

### ISSUE THREAD

**Issue by gebhard73** [Security-Onion-Solutions/securityonion#4884]
The parameter `pipelining` in section `output.logstash` in `filebeat.yml` should be configurable in minions file `/opt/so/saltstack/local/pillar/minions/$MINION_$ROLE.sls`

see: https://github.com/Security-Onion-Solutions/securityonion/discussions/4796

Thanks!

**Comment by TOoSmOotH** [comment]
Elastic Agent
