### ISSUE TITLE
FIX: Disabled user still shows as active in GUI

### ISSUE THREAD

**Issue by petiepooo** [Security-Onion-Solutions/securityonion#5055]
Tested on 2.3.50, 2.3.60 and 2.3.61.  Works as intended on 2.3.50, fails on 2.3.60 and 2.3.61.

When using the so-user-disable command at the CLI, the disabled user still shows as active in the GUI.  It is expected that the user's status symbol would go from a checkmark to a padlock.

To ensure the user is not able to login, it is suggested that an administrator first update the password of the user before disabling them.  I would ask SO staff to please test and confirm whether the user is actually disabled and the display is wrong, or running so-user-disable does not actually disable the user.  Please post your results here so we know what actions are required until this is resolved.

**Comment by jertel** [comment]
Thanks for pointing this out. The user is in fact disabled, but we'll need to address the UI status icon in an upcoming release.

**Comment by petiepooo** [comment]
Thank you for confirming that, @jertel
