### ISSUE TITLE
FEATURE: Enable index sorting to increase search speed

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#5287]
https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules-index-sorting.html

**Comment by rwaight** [comment]
If it makes a difference, this follows along with the ['Tune for search speed' guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-search-speed.html#_use_index_sorting_to_speed_up_conjunctions).

**Comment by TOoSmOotH** [comment]
Thanks for the PR @rwaight! I went ahead and made it so that it is enabled by default but can be disabled if the impact to indexing causes an issue.
