### ISSUE TITLE
S.O Signature = Bad

### ISSUE THREAD

**Issue by jalby** [Security-Onion-Solutions/securityonion#5416]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/5415

<div type='discussions-op-text'>

<sup>Originally posted by **jalby** September  6, 2021</sup>
Downloaded 2.3.70 via <wget https://download.securityonion.net/file/securityonion/securityonion-2.3.70-WAZUH.iso> .. also imported sig key with command as defined in instructions <wget https://raw.githubusercontent.com/Security-Onion-Solutions/securityonion/master/KEYS -O - | gpg --import - >  

Result?  

 gpg --verify securityonion-2.3.70-WAZUH.iso.sig securityonion-2.3.70-WAZUH.iso
gpg: Signature made Mon 30 Aug 2021 06:13:14 PM EDT
gpg:                using RSA key 7C1060B7FE507013
gpg: BAD signature from "Security Onion Solutions, LLC <info@securityonionsolutions.com>" [unknown]

Please advise.  Do I install it or not?  All actions were taken Sept 6th 2021. 
</div>

**Comment by dougburks** [comment]
Resolved in #5415
