### ISSUE TITLE
wazuh agent trying to connect to security onion , but SO refusing connection

### ISSUE THREAD

**Issue by brebe** [Security-Onion-Solutions/securityonion#5690]
hello dear guys,
i am trying to enroll a linux agent to the SO wazuh system.
i did 
1. so-allow > w >and enter ip 
2. sudo so-wazuh-agent-manage > extracted the key
3. entered in the conf the key and ip and restarted the agent

the logs saying that the agent is trying  to connect to server but server is refusing the connection 
what am i doing wrong ? thanks

**Comment by Sahale** [comment]
Hi! Did you configure firewall how explained in docs?

**Comment by brebe** [comment]
yes, 
i forgot to mention i have the CENTOS image installed.
