### ISSUE TITLE
FEATURE: HTTP module for SOC event escalation

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#5791]
Create an additional module for event escalation from SOC.  This module would allow for one or more configurable HTTP requests (similar to how we allow for [Actions](https://github.com/Security-Onion-Solutions/securityonion/issues/2904)).

- Options/Headers should be configurable
- Method should be configurable
- Body should be configurable, preferably with the ability to pull  all or  certain event field values into the body and format as desired.

**Comment by jertel** [comment]
To use, replace "thehive" module config in `soc.json` with:
```
        "httpcase": {
          "hostUrl": "http://some.external.host/some/path",
          "headers": [
            "Authorization: basic Fa3Fa01mDmCC09dA",
            "x-some-key: 1122"
          ],
          "verifyCert": true,
          "createPath": "/some/url/path/to/create/a/case",
          "createMethod": "PUT",
          "createBody": "{\"myid\":\"{{ .Id }}\", \"title\":\"{{ .Title }}\", \"desc\":\"{{ .Description | js }}\"\", \"time\":\"{{ .CreateTime.Format \"15:04\" }}\"}",
          "createContentType": "application/json",
          "createSuccessCode": 200
        }  
```
The `createBody` can be used as a template, substituting values from the [Case](https://github.com/Security-Onion-Solutions/securityonion-soc/blob/master/model/case.go) object as needed. See Go's template documentation for more information: https://pkg.go.dev/text/template
