### ISSUE TITLE
TheHive - Patch for tag filtering

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#591]
With an upgrade to TheHive4 blocked for the foreseeable future, we should consider patching our install with this, so that filtering of tags works better: https://github.com/TheHive-Project/TheHive/pull/1171

**Comment by defensivedepth** [comment]
This will be merged upstream - setting to `blocked`

**Comment by jertel** [comment]
@defensivedepth Is this still open? I thought I saw something about TheHive merging a PR in.

**Comment by defensivedepth** [comment]
This is not relevant anymore, with the move to SOC Alerts
