### ISSUE TITLE
Feature: Have Grafana Alerts/Notifications populate in the Alerts interface. 

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion#5948]
Develop a capability that allows Grafana alerts/notifications to be populated in the Alerts interface.

**Comment by jertel** [comment]
This request is obsolete. Grafana is no longer used in SO. Further, InfluxDB notifications should not be used. Instead use (or add
 additional) the new SO grid-health notifications via Sigma detections. Closing.
