### ISSUE TITLE
FEATURE: Consider adding Elasticsearch plugin repository-s3

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#6139]
_Originally posted by @influence2006 in https://github.com/Security-Onion-Solutions/securityonion/discussions/6126_

I think it would be a helpful repository to have the s3 as a default repository on containers.

``` 
elasticsearch-plugin install repository-s3 
```

**Comment by defensivedepth** [comment]
Closed with https://github.com/Security-Onion-Solutions/securityonion-image/pull/157

**Comment by TOoSmOotH** [comment]
https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3.html
