### ISSUE TITLE
TheHive - markdown images not working as expected

### ISSUE THREAD

**Issue by glwallum** [Security-Onion-Solutions/securityonion#6163]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/6156

<div type='discussions-op-text'>

<sup>Originally posted by **glwallum** November  8, 2021</sup>
Hello

I am working with TheHive to integrate images into the markdown/description fields of the cases and alerts. 

- If I use an external image URL it will load correctly and show the image.
- If I use an internal image URL the image will not load. 
- I have verified thehive node can do a wget to the image, and that the image loads on my machine that I am accessing TheHive from.

I have tried hosting the internal image on IIS and python simple-http-server. Both will not load.

Any advice would be appreciated</div>

**Comment by dougburks** [comment]
Answered in https://github.com/Security-Onion-Solutions/securityonion/discussions/6156. No need to create an issue as that's just one more thing we have to respond to.
