### ISSUE TITLE
FIX: Remove xml header from ossec.conf

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#6325]
It seems that the new so-allow is adding an xml header to `/opt/so/conf/wazuh/ossec.conf` and this is causing problems for Wazuh. If that is the case, then we need to prevent so-allow from writing the xml header and soup will need to remove the xml header from any existing installations.

_Originally posted by @bahoogawooga in https://github.com/Security-Onion-Solutions/securityonion/discussions/6322_:

fresh install of v2.3, trying to add wazuh agents and encountering the following

```
sudo so-wazuh-agent-manage
2021/11/23 02:08:37 manage_agents: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
```

log file (/nsm/wazuh/logs/osssec.log) show the following

     66 2021/11/22 23:38:36 ossec-logcollector: INFO: (1904): File not available, ignoring it: '/var/ossec/logs/active-responses.log'.
     67 2021/11/22 23:48:34 ossec-csyslogd: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
     68 2021/11/22 23:48:34 ossec-authd: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
     69 2021/11/22 23:53:12 ossec-csyslogd: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
     70 2021/11/22 23:53:12 ossec-authd: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
     71 2021/11/23 01:54:53 manage_agents: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
     72 2021/11/23 02:03:02 manage_agents: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
     73 2021/11/23 02:08:32 manage_agents: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).

seems to be two ossec.conf file.  one is located

`'/var/ossec/etc/ossec.conf'`

and the other is at

`/opt/so/conf/wazuh/ossec.conf`

running xmllint shows the following

```
 sudo xmllint /var/ossec/etc/ossec.conf
/var/ossec/etc/ossec.conf:167: parser error : Extra content at the end of the document
<ossec_config>
```

if you look at the /var/ossec/etc/ossec.conf file, it seems to have an extra <ossec_config> and </ossec_config> tag at the end of the file

    152
    153   
    154   <active-response>
    155     <disabled>no</disabled>
    156     <ca_store>/var/ossec/etc/wpk_root.pem</ca_store>
    157     <ca_verification>yes</ca_verification>
    158   </active-response>
    159
    160   
    161   <logging>
    162     <log_format>plain</log_format>
    163   </logging>
    164
    **165 </ossec_config>
    166
    167 <ossec_config>
    168   <localfile>
    169     <log_format>syslog</log_format>
    170     <location>/var/ossec/logs/active-responses.log</location>
    171   </localfile>
    172   <localfile>
    173     <log_format>syslog</log_format>
    174     <location>/var/log/secure</location>
    175   </localfile>
    176   <localfile>
    177     <log_format>syslog</log_format>
    178     <location>/var/log/syslog</location>
    179   </localfile>
    180
    181   <localfile>
    182     <log_format>syslog</log_format>
    183     <location>/var/log/dpkg.log</location>
    184   </localfile>
    185
    186   <localfile>
    187     <log_format>syslog</log_format>
    188     <location>/var/log/kern.log</location>
    189   </localfile>
    190
    191 </ossec_config>**

**Comment by jertel** [comment]
Also, the double `<ossec_config>...</ossec_config>` is supported by the Wazuh agent.

**Comment by bahoogawooga** [comment]
hi,

i tried removing the <ossec_config> line in the middle and still encountering the same issues.. perhaps i'm not thinking about this the right way.. here is a link to video showing the commands and outputs i'm getting on my build.  still can get

`sudo so-wazuh-agent-manage` to run

[https://watch.screencastify.com/v/1HfnxoqkI8yCAJBZA5FW](url)

**Comment by dougburks** [comment]
As I mentioned over at https://github.com/Security-Onion-Solutions/securityonion/discussions/6322, it should just be the xml header on the first line of /opt/so/conf/wazuh/ossec.conf that needs to be removed (and we have a hotfix coming soon that will do this automatically for all users). You shouldn't need to make any changes to /var/ossec/etc/ossec.conf.

**Comment by dougburks** [comment]
Security Onion 2.3.90 WAZUH Hotfix Now Available!
https://blog.securityonion.net/2021/11/security-onion-2390-wazuh-hotfix-now.html
