### ISSUE TITLE
Need a way to carve pcaps

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#635]
## Use Case
As an analyst, I need to be able to do some threat hunting, find an interesting file transfer, and then carve the file.  Some files might be carved automatically as Zeek is monitoring the network traffic (like EXEs), but I need to be able to carve any arbitrary file type in an adhoc fashion when working an incident.  

## Possible Solutions
- an option for a full desktop installation to include Wireshark and/or NetworkMiner
OR
- a web interface for pcap carving

**Comment by jertel** [comment]
@dougburks Is this still an open issue with the analyst workstation option?

**Comment by dougburks** [comment]
The analyst workstation is good enough for now. At some point in the future, it would be nice to have a native capability in the web interface, but it's a very low priority. I'll go ahead and close this issue now.
