### ISSUE TITLE
wazuh agent ERROR: Unable to connect

### ISSUE THREAD

**Issue by 01123581321345589144233** [Security-Onion-Solutions/securityonion#6360]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/6358

<div type='discussions-op-text'>

<sup>Originally posted by **01123581321345589144233** November 27, 2021</sup>
latest security onion iso, installed via usb.
default install
i have added syslog clients and this works perfect, now the next is add my servers via wazuh.
1. I have installed the wazhu agent on the servers and added the wazuh server ip in the config
2. so-allow on the sos server and enabled the option (w) and (r) for the servers, i added the server ips.
3. i try to /var/ossec/bin/agent-auth -m 192.168.1.95 (sos server ip)

2021/11/27 01:02:31 agent-auth: INFO: Started (pid: 16430).
2021/11/27 01:02:31 agent-auth: INFO: Starting enrollment process to server: 192.168.1.95
2021/11/27 01:02:31 agent-auth: ERROR: Unable to connect to 192.168.1.95:1515
</div>

**Comment by 01123581321345589144233** [comment]
why you have closed this ?

**Comment by dougburks** [comment]
Please continue discussing in Discussion https://github.com/Security-Onion-Solutions/securityonion/discussions/6358.
