### ISSUE TITLE
Install local analyst tools

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#643]

**Comment by TOoSmOotH** [comment]
wireshark
network miner

**Comment by phil1090** [comment]
foremost
bittwist
chaosreader
driftnet
dsniff
hping3
hunt
labrea
netsed
netcat
ngrep
scapy
sniffit
ssldump
sslsniff
tcpdump
tcpflow
tcpick
tcpslice
tcpstat
tcptrace
tcpxtract
tshark
whois
perhaps chromium

**Comment by weslambert** [comment]
strelka-fileshot
strelka-oneshot

**Comment by m0duspwnens** [comment]
strelka-fileshot and strelka-oneshot were not included

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion/commit/840b54d73c486a2dc246c26880c1b08e4b217018
