### ISSUE TITLE
FEATURE: add a Logging framework for for use in the bash scripts

### ISSUE THREAD

**Issue by JamesMConroy** [Security-Onion-Solutions/securityonion#6452]
Right now the scripts rely on a bunch of calls to `echo` and `printf` sometimes with hard coded colors.

Adding a logging framework would standardize how information is printed to stderr and stdout. A good logging framework would also handle checking if the output is a tty that can support colors, and exit the script when a fatal error is logged.

**Comment by rwwiv** [comment]
Closing, see #6453 for more information.
