### ISSUE TITLE
/nsm partition at 99% occupied disk space without using full available space

### ISSUE THREAD

**Issue by barbosaa99** [Security-Onion-Solutions/securityonion#6457]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/6456

<div type='discussions-op-text'>

<sup>Originally posted by **barbosaa99** December  6, 2021</sup>
Hello,

We are getting our /nsm partition with 99% of used disk space as you can see from the following image:

![image](https://user-images.githubusercontent.com/16745902/144839766-36f266d1-7d51-4553-831d-0306ab52cf77.png)

But if we go to the directory /nsm and execute "du -shc ./*" command:

![image](https://user-images.githubusercontent.com/16745902/144839874-d98c1549-cacc-463b-ab7c-791fc33c0630.png)

We can see that the total disk space is 3.3T and we are only using 1.3T.

This doesn't make any sense.

This is our elastic configuration file:

[root@papidss003 suricata]#  cat /opt/so/saltstack/local/pillar/minions/papidss003_standalone.sls
elasticsearch:
  es_port: 9200
  esclustername: '{{ grains.host }}'
  esheap: 25000m
  log_size_limit: 1000
  mainint: enp2s0f0
  mainip: 10.135.101.138
  node_route_type: hot
  node_type: ''
host:
  mainint: enp2s0f0
idstools:
  config:
    oinkcode: ''
    ruleset: ETOPEN
    urls: null
  sids:
    disabled:
    - '2221010'
    - '2100368'
    - '2200074'
    - '2221045'
    - '2101411'
    - '2100366'
    - '1100012'
    enabled: null
    modify: null
kratos:
  kratoskey: du8SHNYmhSzBpQzR0OXw
logstash_settings:
  ls_input_threads: 1
  ls_pipeline_batch_size: 125
  ls_pipeline_workers: 80
  lsheap: 1000m
manager:
  domainstats: 0
  elastalert: 1
  es_port: 9200
  esclustername: '{{ grains.host }}'
  esheap: 25000m
  freq: 0
  grafana: 1
  mainint: enp2s0f0
  mainip: 10.135.101.138
  mtu: 1500
  no_proxy: localhost, 127.0.0.1, 10.135.101.138, papidss003
  osquery: 0
  playbook: 0
  proxy: http://10.135.101.133:3128
  thehive: 0
ntp:
  servers:
  - 10.220.3.113
  - 10.220.3.114
patch:
  os:
    enabled: true
    schedule_name: manual
    source: direct
    splay: 300
sensor:
  hnsensor: null
  interface: bond0
  mainint: enp2s0f0
  mainip: 10.135.101.138
  manager: ''
  mtu: 1500
  suriprocs: 19
  uniqueid: 1638456971
  zeek_lbprocs: null
sensoroni:
  node_address: 10.135.101.138
  node_description: SO
soc:
  es_index_patterns: '*:so-*,*:endgame-*'
steno:
  enabled: false

Could you help us with this situation?

Thank you.</div>

**Comment by dougburks** [comment]
Please keep all discussion at https://github.com/Security-Onion-Solutions/securityonion/discussions/6456 rather than creating a new issue.
