### ISSUE TITLE
Grafana not showing any data

### ISSUE THREAD

**Issue by OzzyKampha** [Security-Onion-Solutions/securityonion#646]
I just installed HH to try it out, but when i check grafana for data, nothing is coming up.
Running Eval mode

**Comment by m0duspwnens** [comment]
@OzzyKampha Thanks for the report. Which OS is this running on, CentOS or Ubuntu? Can you run the following from the command line and report the results?

`sudo salt-call pillar.get master:grafana`

`sudo docker ps | grep grafana`

`docker ps|egrep 'telegraf|grafana'`

**Comment by OzzyKampha** [comment]
Using the latest HH ISO

`sudo salt-call pillar.get master:grafana`

local:
    1

`sudo docker ps|egrep 'telegraf|grafana'`

4b4d7db04b30        HH.local:5000/soshybridhunter/so-grafana:HH1.2.2              "/run.sh"                5 hours ago         Up 5 hours                  0.0.0.0:3000->3000/tcp                                                     so-grafana
787ae87518f3        HH.local:5000/soshybridhunter/so-telegraf:HH1.2.2             "/entrypoint.sh tele…"   5 hours ago         Up 5 hours                                                                                             so-telegraf

**Comment by TOoSmOotH** [comment]
Can you take a screenshot of where the data is missing?

**Comment by OzzyKampha** [comment]
![image](https://user-images.githubusercontent.com/14088328/81529951-2ed3d700-9360-11ea-895e-6149f5247eb9.png)

**Comment by m0duspwnens** [comment]
@OzzyKampha We have now seen this reproduced in our testing. We will dig into this as soon as we can. Thanks again for the report!

**Comment by GraemeBingham** [comment]
I was having this issue in the previous version but since upgrading to Beta 2 it seems to have been fixed.

**Comment by TOoSmOotH** [comment]
This is now fixed in RC1
