### ISSUE TITLE
Document OQL

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#651]
General documentation on OQL

**Comment by defensivedepth** [comment]
Something like this: https://drive.google.com/file/d/0B2S_IOa0MiOHWndxWFRiUHNoNW8/view

**Comment by dougburks** [comment]
We have some initial OQL documentation here at https://docs.securityonion.net/en/2.1/hunt.html#oql, but we should add more.

**Comment by dougburks** [comment]
Updated for 2.3.50:
https://docs.securityonion.net/en/2.3/hunt.html#oql
