### ISSUE TITLE
FIX: Remove elastalert rules when Play is deleted

### ISSUE THREAD

**Issue by idolaman** [Security-Onion-Solutions/securityonion#6531]
Hello,

We are using SO 2.3.60 in distributed mode.
When deleting play with playbook admin, the play does get deleted in the playbook GUI,
But the elastalert rule does not get deleted in the path:
/opt/so/rules/elastalert/playbook/

We tried to reset the playbook and soctopus services, but it didn't help.

Can you check this out?
Thank you!

**Comment by defensivedepth** [comment]
Yes, this would be the case because of the current design. 

For now, you can remove all the `.yaml` files in `/opt/so/rules/elastalert/playbook/` on the Manager, and then run the following:

`sudo so-playbook-sync`

**Comment by defensivedepth** [comment]
No longer relevant RE: Detections.
