### ISSUE TITLE
Review add value to new search

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#655]
Prototype has the ability to create a new search via an icon next to field. Review this feature

**Comment by dougburks** [comment]
One option to do this without taking up any more screen real estate might be to hyperlink the field value itself like this:
(+) (-) [result1](url)

Use case for this potential option:
Suppose we do a search and find a few interesting IP addresses.  I might want to open each of those IP addresses in a new tab to start new searches for each of them.
