### ISSUE TITLE
FEATURE: Allow to setup cold/warm search node

### ISSUE THREAD

**Issue by astroc0** [Security-Onion-Solutions/securityonion#6555]
Allow the change of attribute box_type for elasticsearch.
i.e user can specify which nodes can be cold/warm/hot in the cluster, this can be used to give more flexibility for the user to distribute data over the cluster in a more meaningful way.
In our case we have set replica:1 as we have 2 search nodes each has 1TB of NVMe storage, but we want to add a third node to keep the old data on it. Elasticsearch supports this scenario natively by allowing the user to setting **box_type:"cold"** in elasticsearch.yml file.
wish this will be possible in SO 2.

**Comment by TOoSmOotH** [comment]
Covered in #6554
