### ISSUE TITLE
Pivot from fields to external sources

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#656]

**Comment by TOoSmOotH** [comment]
Like pivot to a cortex analyzer

**Comment by dougburks** [comment]
Ideally, we should provide a default list of external sources like Google, VirusTotal, etc. but also give the user the ability to add their own lookups.

**Comment by jertel** [comment]
This has been implemented. There's a new issue #1299 created for pillarizing custom actions, but it's decoupled from the SOC work that is now complete.
