### ISSUE TITLE
Typo in so-image-common output

### ISSUE THREAD

**Issue by JoeySec** [Security-Onion-Solutions/securityonion#6563]
https://github.com/Security-Onion-Solutions/securityonion/blob/cfaa0e679c333f0671aca7bb058d46b22faee965/salt/common/tools/sbin/so-image-common#L135

Missing a "t" in raw.gi**T**hubusercontent.com

**Comment by dougburks** [comment]
Fixed via pull request https://github.com/Security-Onion-Solutions/securityonion/pull/6574.

If you find other typos in the future, you can submit your own pull requests as described here:
https://github.com/Security-Onion-Solutions/securityonion/blob/master/CONTRIBUTING.md
