### ISSUE TITLE
[Feature request] Integration with OpenCTI

### ISSUE THREAD

**Issue by SamuelHassine** [Security-Onion-Solutions/securityonion#6594]
Dear SecurityOnions mainteners (cc @dougburks),

A lot of OpenCTI users are requesting to be able to use their OpenCTI data (indicators and observables) into their SecurityOnion SIEM. Would it be possible to create this integration? If not, we may be able to create a connector on the OpenCTI side but it makes less sense.

Kind regards,
Samuel

**Comment by dougburks** [comment]
We don't have any time to work on this right now.
