### ISSUE TITLE
FIX: SOUP should check that en_US.UTF-8 is available before switching to it

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion#6599]
I was having the same error as above on my Ubuntu 18.04 install.  

I also saw this error in the console at the very top of the Soup run:

`/usr/sbin/soup: line 19: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory`

After coming here, I tried to run:

 `export LC_CTYPE="en_US.UTF-8"` 

but I got the following error:

`-su: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory`

So, I searched that error and found [this](https://askubuntu.com/questions/454260/how-to-solve-locale-problem)

From that link, I ran the following:

`sudo locale-gen en_US.UTF-8`

And then soup ran without the above errors.  

Interestingly, I performed an upgrade on another host that was also 2.3.80 on Ubuntu 18 and I didn't get either of those errors.  The only difference between those two hosts is that the one had originally been installed with 2.3.50 or 2.3.60 and upgraded from there over time and the other started out on 2.3.70.  

I don't know if that provides any insight for anyone, but for what it's worth, that's what worked for me.  

Thanks SO Team for responding so quickly to the log4j stuff!

_Originally posted by @kmfreder1 in https://github.com/Security-Onion-Solutions/securityonion/discussions/6431#discussioncomment-1814657_

**Comment by kmfreder1** [comment]
That would be great!

**Comment by m0duspwnens** [comment]
reworked soup to not need `export LC_CTYPE="en_US.UTF-8"`
