### ISSUE TITLE
FIX: Reinstall should not try to patch python3-influxdb modules if already patched.

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion#6765]
Part of this issue may be that salt is trying to patch the influxdb python module during every install and call to highstate.  By my reckoning, that should be done once during install (and subsequent upgrades if needed), and should fail gracefully if it's already been patched, but should not cause errors on every call to highstate.

_Originally posted by @petiepooo in https://github.com/Security-Onion-Solutions/securityonion/issues/6467#issuecomment-1003169216_

**Comment by m0duspwnens** [comment]
The `python3-influxdb` state checks for the existence of files in `/opt/so/state` to determine if the files have been patched. Since `/opt/so` is cleared during a reinstall, we lose the state of this patch and errors are caused trying to repatch them during a reinstall.

**Comment by petiepooo** [comment]
It sounds like you understand the issue better than I did.  Thank you.
