### ISSUE TITLE
FEATURE: MAC/IP/Hostname Translation Facilities

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#6774]
While we can't always know the best way for folks to be able to determine to what host a MAC address or IP belongs, we can make it a bit easier for them to be able to access or provide resources to do so. We might consider pre-creating an enrich routine, ingest pipeline, or SOC action to make this easier for folks to be able to plug in their data, or access to a data source.

**Comment by jertel** [comment]
Closing in favor to #8655.
