### ISSUE TITLE
Support CentOS 8

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#69]
First, we'll need the latest version of `salt` from https://repo.saltstack.com/py3/redhat/salt-py3-repo-latest.el8.noarch.rpm.

The next hurdle is that CentOS 8 no longer supports Docker:
https://www.redhat.com/en/blog/red-hat-enterprise-linux-8-beta-new-set-container-tools
https://access.redhat.com/discussions/3697371

We can still install Docker CE on CentOS, but there are no native packages for the Docker API like `python-docker` and `docker-python`.  Currently, salt controls our containers via the Docker API, so we'll need to change these API calls back to the Docker CLI method that we use in 16.04.  Once this is done, we should be able to get rid of the `python-docker` and `docker-python` requirements.

If we end up switching from Docker to native podman, then we'll also need to implement https://github.com/Security-Onion-Solutions/securityonion-saltstack/issues/68 (which might not be a bad idea anyway).

**Comment by TOoSmOotH** [comment]
CentOS 8 is no more
