### ISSUE TITLE
Issue with displaying Geoip coordinates on Kibana Maps

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#6905]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/6240

<div type='discussions-op-text'>

<sup>Originally posted by **esbat-max** November 16, 2021</sup>
Hello,

I am using security onion release 2.3.70 in standalone mode.

I am collecting OWA logs via filebeat to security onion. Dataflow is as follows: Beats -> Elasticsearch -> Index Template -> Ingest Processor -> Index.

Using the geoip processor pipeline I converted the device ip field into geoip coordinates. However, when I try to put the coordinates on maps, the result is empty map.

Any advice of missing configuration ?

thanks,
El

</div>

**Comment by RagnarSTS** [comment]
Fixing geo has sort of been back burnered for a while. 
https://github.com/Security-Onion-Solutions/securityonion/issues/3152

**Comment by dougburks** [comment]
This was resolved in 2.3.110:
https://github.com/Security-Onion-Solutions/securityonion/issues/3152#issuecomment-1068428872
