### ISSUE TITLE
so-thehive-cortex:2.3.91 seems outdated

### ISSUE THREAD

**Issue by maseron** [Security-Onion-Solutions/securityonion#6919]
I faced problem that so-cortex was not able to query OpenCTI instance (v5.1.3). The error in cortex analyze request was:

`ERROR:root:Cannot query field "x_opencti_report_status" on type "Report". Did you mean "x_opencti_graph_data"?Traceback (most recent call last):  File "/Cortex-Analyzers/analyzers/OpenCTI/opencti.py", line 111, in <module>    OpenCTIAnalyzer().run()  File "/Cortex-Analyzers/analyzers/OpenCTI/opencti.py", line 84, in run    "values": [observable["id"]],  File "/usr/local/lib/python3.6/dist-packages/pycti/entities/opencti_report.py", line 243, in list    "orderMode": order_mode,  File "/usr/local/lib/python3.6/dist-packages/pycti/api/opencti_api_client.py", line 280, in query    {"name": error_name, "message": main_error["message"]}ValueError: {'name': 'Cannot query field "x_opencti_report_status" on type "Report". Did you mean "x_opencti_graph_data"?', 'message': 'Cannot query field "x_opencti_report_status" on type "Report". Did you mean "x_opencti_graph_data"?'}`

Digging more I found that the OpenCTI python client (pycti) on so-cortex is quite old version - 4.4.1, but the latest version is 5.1.3.
Straight pip install pycti upgrade was not possibe, because pycti 5.1.3 needs python3.7 or greater version, but the so-cortex container is based on ubuntu 18.04... where by default the biggest python version is 3.6.
More or less I managed to get python3.7 with required modules working, but that did not helped - faced different error:

`Traceback (most recent call last):  File "/Cortex-Analyzers/analyzers/OpenCTI/opencti.py", line 111, in <module>    OpenCTIAnalyzer().run()  File "/Cortex-Analyzers/analyzers/OpenCTI/opencti.py", line 97, in run    del(report["x_opencti_graph_data"])KeyError: 'x_opencti_graph_data'`

But this more looks like is related with Cortex-Analyser version and that is the latest, so I am not sure if I messed up something with python upgrade.

**Comment by dougburks** [comment]
Cortex and TheHive are going away soon:
https://blog.securityonion.net/2022/01/coming-soon-in-security-onion-23100.html
