### ISSUE TITLE
FIX: Elasticsearch & Logstash logs not compressed or cleaned

### ISSUE THREAD

**Issue by petiepooo** [Security-Onion-Solutions/securityonion#6932]
All logs under /opt/so/log/* are rotated and compressed with a 14-day retention except for /opt/so/log/elasticsearch which exist uncompressed back to the day so-setup was run.

Elasticsearch logfiles are managed by log4j rather than logrotate.  I think this is just a matter of adding a value for appender.rolling.strategy.max and appending a '.gz' to the end of the appender.rolling.fileName in log4j2.properties.  Log4j should take care of the rest, from what I read.

**Comment by defensivedepth** [comment]
Closed with https://github.com/Security-Onion-Solutions/securityonion/pull/7765
