### ISSUE TITLE
FIX: Hunt - Alert user when trying to use * on non-string fields

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#6952]
When using the * in Hunt for showing missing values - if the field datatype is something like IP or boolean, it silently fails, which can lead the user to believe there is not actually any data. Appending .keyword to the field and it works as expected.

**Comment by jertel** [comment]
As of an earlier release this year, when this occurs the user will see a message similar to the following:

![image](https://user-images.githubusercontent.com/16639611/199070999-c2d41462-7ead-481b-9864-b3228cc998ac.png)

This is sufficient to alert the user that the query is invalid. Attempting to "fix" the query for the user will require additional meta data knowledge of the field mappings, and how Elastic handles aggregations with missing data for each data type.
