### ISSUE TITLE
FR: sort indices list alphabetically by index name

### ISSUE THREAD

**Issue by gebhard73** [Security-Onion-Solutions/securityonion#6969]
Hi,

FR: display index list sorted alphabetically by index name

Fix: change index list command in `/opt/so/saltstack/default/salt/common/tools/sbin/so-elasticsearch-indices-list` from
`
{{ ELASTICCURL }} -s -k -L https://{{ NODEIP }}:9200/_cat/indices?pretty
`
to

`
{{ ELASTICCURL }} -s -k -L "https://{{ NODEIP }}:9200/_cat/indices?pretty&v&s=index"
`

Thanks!

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/7136

**Comment by gebhard73** [comment]
thanks @weslambert
