### ISSUE TITLE
FIX: Cleanup Setup Terminology

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#7008]
Eg:

NSM
IDS
HOME_NET
'adding sensors remotely'
ntp vs NTP 
CIDR (some give examples, some dont)

**Comment by jertel** [comment]
Consider also adjusting the "optional components" setup screen to more helpful descriptions, such as (just ideas, not set in stone):
- OSSEC  FleetDM: Device management
- WAZUH  Host-based monitoring
- PLAYBOOK  Incident response playbook management
- STRELKA  Packet file extraction

From Doug: There's a lot of overlap between OSQUERY and WAZUH and it may be difficult to differentiate between the two in those few characters.
