### ISSUE TITLE
FIX: modify Zeek dockerfile to allow customizing base protocol scripts

### ISSUE THREAD

**Issue by cm-ops** [Security-Onion-Solutions/securityonion#7181]
We cannot modify Zeek base protocol scripts in the so-zeek container. Adjust dockerfile to allow for modifications. Example, MySQL port const cannot be redefined. Modifications are overwritten when container restarts.

**Comment by micrictor** [comment]
Should users be modifying these? I think it would be a better experience for users, with less unpredictable behaviour, if they used a policy script to register new ports for a given analyzer using something similar to this

```
const ports = { 11434/tcp, 13306/tcp };

event zeek_init() &priority=5
	{
	Analyzer::register_for_ports(Analyzer::ANALYZER_MYSQL, ports);
	}
```

**Comment by dougburks** [comment]
Great suggestion @micrictor !

Added to documentation:
https://docs.securityonion.net/en/2.3/zeek.html#modifying-base-protocol-scripts
