### ISSUE TITLE
Redirect error in SOC

### ISSUE THREAD

**Issue by rwwiv** [Security-Onion-Solutions/securityonion#722]
## Expected Behavior
Logging out then back in from SOC should redirect to the default page

## Actual Behavior
After logging in, if the user previously clicked the sidebar link to Kibana or Navigator, SOC redirects to a URL path related to whichever tool was selected

## Steps to Reproduce the Problem

  1. Click link in sidebar to Kibana or Navigator
  2. From original SOC tab, log out
  3. Log in again immediately

**Comment by jertel** [comment]
Unable to reproduce this issue. Screenshot below shows two examples of this not happening. Closing. If you can reproduce it with a screen recording then re-open the issue.

[recording.zip](https://github.com/Security-Onion-Solutions/securityonion/files/5483879/recording.zip)
