### ISSUE TITLE
FEATURE: Add "observable" button next to hash for case attachments

### ISSUE THREAD

**Issue by InfosecGoon** [Security-Onion-Solutions/securityonion#7222]
In addition to the "copy" button, could we add an "observable" eyeball button next to the hash when a file is attached to a case?

**Comment by dougburks** [comment]
The ATTACHMENTS tab now has an observable button for all 3 hash values:
![Screen Shot 2022-05-23 at 4 46 49 PM](https://user-images.githubusercontent.com/1659467/169903462-edcf3ba5-a510-4c01-881a-d05d063b6174.png)

Clicking that button creates a new observable on the OBSERVABLES tab:
![Screen Shot 2022-05-23 at 4 47 13 PM](https://user-images.githubusercontent.com/1659467/169903465-f86c4be0-83b5-4f99-9cfe-a08f221dac46.png)
