### ISSUE TITLE
Wait for package manager to become unlocked during setup

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#735]
`E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?`

- Add new "addPackage" function to `so-common`
- Function is responsible for determining which OS package (if different name per OS) and manager to use
- Existing setup logic refactored to call this new function.
- Add new logic to function to wait for Ubuntu/debian package manager to unlock.
- If the message is shown in whiptail, update the progress bar to indicate that its waiting for package manager to unlock.
- else show message on stdout.

**Comment by jertel** [comment]
Ensure CentOS/yum is also protected.
