### ISSUE TITLE
AWS-Marketplace Install, No alerts

### ISSUE THREAD

**Issue by ob1xxx** [Security-Onion-Solutions/securityonion#7533]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/7532

<div type='discussions-op-text'>

<sup>Originally posted by **ob1xxx** March 12, 2022</sup>
Hello Friend,

So I've installed the latest build, 2.3.10, from the market place. I've enabled 2 network interfaces and have verified with traffic mirroring and tcpdump. So the SO instance does see the traffic and there are low level alerts. The issue is I'm actively attacking a victim box, but don't see any alerting. I'm using Metasploit on the victim machine and am popping shells like a mad man. Still no alerting. I've ran "so-allow" and selected "analyst". Any thoughts as to what is happening?

Traffic Mirroring- There are two sessions active. 
1. Victim box mirror to SO eth0(mgmt interface)
2. Attack(Metasploit) to SO eth0</div>

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion/discussions/7532 is the proper place for discussion. Closing this issue.
