### ISSUE TITLE
FEATURE: Expose Case user info (email address) in SOC Alert/Hunt/Cases results instead of user ID

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#7548]
When viewing the list of cases, add the assigned user as a new column. This will require changes in the SOC UI to replace the user ID fetched from ES with the more human friendly information such as the user's email address.

Also consider the same functionality for the Hunt and Alert interfaces, including the group-by and chart visuals, so that managers can groupby assigned user to get a count of cases per analyst in both tabluar and chart forms.

**Comment by dougburks** [comment]
![image](https://user-images.githubusercontent.com/1659467/164771873-38aaaf1a-05e5-4e9d-98ea-c74a5d9bc129.png)
