### ISSUE TITLE
FEATURE: Add Advanced toggle to Alerts and Cases pages

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#7559]

**Comment by dougburks** [comment]
Tested and verified.

Alerts default interface with toggle to temporarily enable advanced interface:
![Screen Shot 2022-08-26 at 8 41 03 AM](https://user-images.githubusercontent.com/1659467/186906159-c8e5695f-e615-4f47-89e9-2e45bf8bab93.png)

Alerts advanced interface:
![Screen Shot 2022-08-26 at 8 41 14 AM](https://user-images.githubusercontent.com/1659467/186906222-811e3ac6-bcc2-4fc0-b3ab-1e926b97e107.png)

Dashboards uses the advanced interface by default so the toggle is not available:
![Screen Shot 2022-08-26 at 8 41 25 AM](https://user-images.githubusercontent.com/1659467/186906251-36002129-9de0-4265-8d7a-42704a13fad2.png)

Hunt uses the advanced interface by default so the toggle is not available:
![Screen Shot 2022-08-26 at 8 41 36 AM](https://user-images.githubusercontent.com/1659467/186906280-9ce12735-fa53-4327-be52-bffeb0087596.png)

Cases default interface with toggle to temporarily enable advanced interface:
![Screen Shot 2022-08-26 at 8 41 47 AM](https://user-images.githubusercontent.com/1659467/186906323-5f060a68-57ac-4bcf-af6d-e137c9d678a4.png)

Cases advanced interface:
![Screen Shot 2022-08-26 at 8 41 57 AM](https://user-images.githubusercontent.com/1659467/186906336-19834c43-39d3-467b-ae52-52065ad8c8fd.png)

**Comment by dougburks** [comment]
Updated documentation:
https://docs.securityonion.net/en/2.3/alerts.html
https://docs.securityonion.net/en/2.3/cases.html
https://docs.securityonion.net/en/2.3/soc-customization.html#soc-customization
