### ISSUE TITLE
FIX: Elastic 8 Breaking Changes

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#7563]
### Elasticsearch

https://www.elastic.co/guide/en/elasticsearch/reference/master/migrating-8.0.html

- [x] Remove `indices.query.bool.max_clause_count` (7128b046365a4dda76947478251979a5be3ae1da)
- [x] Remove `discovery.zen.*` settings
- [x] Review `xpack security.*ssl` settings
- [x] `kibana` user has been replaced by `kibana_system` - review code for impact, and make changes as necessary
- [x] Replace `search.remote` settings with `cluster.remote` (99430fddebb49ca015ddc396399f46e80c70f8ef, 99430fddebb49ca015ddc396399f46e80c70f8ef)
- [x]  Ensure `node.roles` is used when specifying node roles
- [x] Replace `transport.tcp.port` with `transport.port`
- [x] The S3, GCS and Azure repository plugins are now included in Elasticsearch (Remove plugin installation where necessary) (https://github.com/Security-Onion-Solutions/securityonion-image/commit/da2c7a3380692d9b829b07c14cd16b0502d7cfe1)
- [x] Review the ES data directory/layout changes for impact
https://www.elastic.co/guide/en/elasticsearch/reference/master/migrating-8.0.html#breaking_80_packaging_changes
- [x] Review BCs for REST API(s) (SOC/SOCtopus/utility scripts)
https://www.elastic.co/guide/en/elasticsearch/reference/master/migrating-8.0.html#breaking_80_rest_api_changes 

NOTE: Indices created in Elasticsearch 6.x and earlier versions are not supported.

### Logstash
https://www.elastic.co/guide/en/logstash/current/breaking-8.0.html
- [x] Review ECS compatibility setting for Logstash pipelines (might consider `pipeline.ecs_compatibility: disabled` in `pipelines.yml` or `defaults.yaml` for disabling globally if impacted)

### Kibana
https://www.elastic.co/guide/en/kibana/master/release-notes-8.0.0.html#breaking-changes-8.0.0
- [x] Switch from `so_elastic` user with `superuser` role to `so_kibana` user with `kibana_system` role (6f294cc0c24aafb4b09280c5ea160ed3e96f5203)
- [x] Add `xpack.reporting.kibanaServerhostname: localhost` in `defaults.yaml` (b2c26807a3caca16db429c74e670b64cd8876f00)
- [x] Update kibana config for 8.1.0 (https://github.com/Security-Onion-Solutions/securityonion/commit/e0374be4aac338aa3b5a6e2ccc19f9c1671af72f)

### Curator
- [x] Patch Curator to work with Elastic 8 (178e91c04a2edd726a31857627e87f103f68c76c)

### Elastalert
- [x] Update to Elastalert 2.4.0 (36783ff96112c647cbd747d0d179d9eed09f6715, 679aba52b2c7d37cbbfef5b2640dc147ebb8c3ed)
- [x] Ensure `match_body` mapping contains `"enabled":  "true"` for `object` (b2437ae8a9b0ae0ddd226f37e1c133348614abe1)
- [x] SOUP needs to delete existing Elastalert indices, and ensure Elastalert does not re-create them before the upgrade is finished (https://github.com/elastic/elasticsearch/issues/84199)

### Filebeat
- [x] Pipeline load workaround  (a18b38de4da36de0f470f7c79775dc38c094ab0d)
- [x] Restructure how modules are enabled (a60ef339309915e031f5fceeef0dfda2510ed2dc)
- [x] Switch from `log` input to `filestream` input (712a92aa39e443ba67b5ec9dc2c10b7011b4bfc2)

https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-8.0.0.html

### SOC 
- [x] Remove usage of `_type`

**Comment by dougburks** [comment]
Tested and verified:
![image](https://user-images.githubusercontent.com/1659467/178353411-a83f00f5-c640-43d3-90ed-eb3ad54fcc19.png)
