### ISSUE TITLE
FEATURE: Deploy Elastic Maps Server within Air-Gapped deployments where internet access is not available

### ISSUE THREAD

**Issue by metapolitics** [Security-Onion-Solutions/securityonion#7593]
**Feature:** Installation of the Elastic Maps Server within Security Onion Air-Gapped deployments where internet access is not available.

[Elastic offer the ability to self-host their Maps Server](https://www.elastic.co/guide/en/kibana/current/maps-connect-to-ems.html#elastic-maps-server)  where internet access may not be available. 

When deploying SO in Air-Gapped environments, the functionality of mapping geo-locations  in dashboards and reporting is lost. The inclusion of the Maps Server as another docker container alleviates this problem in air-gapped environments, and the docker image contains Zoom Level 8 (country level basemap data).

**Comment by dougburks** [comment]
The Elastic Maps Server is 2.3GB and we don't have room for it in our ISO image.

You may be able to manually sneakernet that Docker image and configure it yourself.
