### ISSUE TITLE
Apparmor Errors (Apparmor DENIED) after fresh install of HH on Ubuntu 18.04

### ISSUE THREAD

**Issue by Hops-AF** [Security-Onion-Solutions/securityonion#762]
<img width="1657" alt="Screen Shot 2020-05-21 at 7 32 25 PM" src="https://user-images.githubusercontent.com/65135457/82733079-73a42a00-9cdf-11ea-81fb-91a9c305a116.png">

**Comment by dougburks** [comment]
Closing in favor of https://github.com/Security-Onion-Solutions/securityonion/issues/2560
