### ISSUE TITLE
Wifi Management interface missing 

### ISSUE THREAD

**Issue by remrem29** [Security-Onion-Solutions/securityonion#763]
Hi 

Is there an issue with using a Wifi Usb nic as the management interface? The interface  is not being presented when setting up the NIC's going through the installer for Hybrid Hunter.

The centOS is seeing the device (Ifconfig will show it as wlpxxxxxxxx) but no /etc/sysconfig/network-scripts/ifcfg-wlp* is created (When breaking out of the install and go to cli), and I'm not allowed to create this file as user Onion. 

Is there an work-around for getting this device up as an choosable NIC in the HH installer?

**Comment by TOoSmOotH** [comment]
I can add it so it shows up but its still going to be an issue since we would need to identify that is a wireless interface and set up all the wireless details. The best way I think around this would be to do a centos minimal or an ubutnu 18.04 and do a network install. Set up your wireless before you run setup.

**Comment by remrem29** [comment]
Install HH from an ISO and after first boot login in as "Onion" and I cancel the setup - from the cli I configured the Wireless card through "nmtui", reboot HH. 

After boot cancel the setup again and from cli check that I have an IP from Wireless router which I have and I  can ping 8.8.8.8, so Wireless is working - run "sudo ./so-setup network"  - Press YES to "install SO over the internet" - choose "Eval" press enter  - Message saying that "only one NIC is found, two is needed" - card found is  eno1 and not the Wireless which is called wlp0s26u1u6.

So how did you get the "GUI" to find both NIC's? CentOS is seeing both NIC's and the wireless is working, but not in the HH installer.

**Comment by remrem29** [comment]
NVM - Got it

**Comment by TOoSmOotH** [comment]
I am going to keep this open because I think there is some need to at least support this in the network install.

**Comment by remrem29** [comment]
okay :-)  - But there is an issue with the install script - choose anything else than EVAL in "Install Type"  - then it will find the Wireless NIC - choosing EVAL and it will fail finding the wireless NIC.

**Comment by remrem29** [comment]
Could it be that this is the issue:

"filtered_nics=$(ip link| awk -F: '$0 !~ "lo|vir|veth|br|docker|wl|^[^0-9]"{print $2}' | grep -vwe "$grep_string"  | sed 's/"

This is from the so-common-functions file and looks like NIC's with wl are being filtered  - Seems that if I remove the "wl" part from the line  - Do a "sudo ./so-setup network" it will show my Wifi card (Start with running nmtui first and setup the Wifi and then the above)

**Comment by gebhard73** [comment]
I've managed to set up SO with only one WiFi management interface for testing usage / syslog at home. Perhaps this helps here. See https://www.thierfreund.de/security-onion-at-home/
