### ISSUE TITLE
Issues with installing ISO image

### ISSUE THREAD

**Issue by trb143** [Security-Onion-Solutions/securityonion#764]
-  Domain name set in the script should be fully qualified not just the server name?  Getting this wrong breaks the UI.
-  Keyboard on install is US which is different to Uk keyboard
-  Master IP address is asked for in EVAL and Stanalond mode even which the master is DHCP and you are building the Master.
- Fleet-setup provides incomplete output.

![image](https://user-images.githubusercontent.com/1388819/82887778-65087d80-9f40-11ea-8c08-8399ebbe4090.png)

**Comment by TOoSmOotH** [comment]
Can you explain the 3rd bullet a little more? Which part of the install are you referring to?

**Comment by trb143** [comment]
After you select the type of installation you want "Standalone" you are asked for the Master server name and then it asks for the IP address of the server.  If you are building a standalone server with DHCP at this point you would not know what the IP address was.

**Comment by TOoSmOotH** [comment]
> After you select the type of installation you want "Standalone" you are asked for the Master server name and then it asks for the IP address of the server. If you are building a standalone server with DHCP at this point you would not know what the IP address was.

It is doing that because it can't resolve itself. I have never had this happen as I use DHCP for all my install types. I created a new issue #778 for that bullet.
