### ISSUE TITLE
SOC: VXLAN Support for PCAP

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#773]
We should try to allow for rendering a transcript for VXLAN-encapsulated traffic, similar to how we do in vxlan2pcap:

https://github.com/Security-Onion-Solutions/securityonion-cloud/tree/master/vxlan2pcap/go

**Comment by MrSecure** [comment]
Would it be possible to add handle other encapsulations too - PPPoE in particular?

**Comment by weslambert** [comment]
Initial support has been added. If there are issues with implementation or further requests for enhancements, another issue can be filed, or this one re-opened.
