### ISSUE TITLE
FIX: Don't modify hostname of machine if preflight fails

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#7804]
Observed on Ubuntu 18 Network Install. Hostname was modified even though preflight check failed. It is expected that no changes should be made to a box if there is any failure before setup options have been selected and confirmed at the final prompt.

**Comment by TOoSmOotH** [comment]
In 2.4 we check for salt connectivity as everything is pulled from the manager. There is no preflight any more.
