### ISSUE TITLE
FIX: Improve Zeek file extraction

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#7829]
Per https://github.com/Security-Onion-Solutions/securityonion/discussions/7781, Zeek is currently not extracting files from some protocols due to the `total_bytes` check.

**Comment by dougburks** [comment]
Here's the before and after using the same set of sample PCAPs.

Before:
```
ls |cut -d- -f1 |uniq -c 
     36 HTTP
```

After:
```
ls |cut -d- -f1 |uniq -c
      1 FTP_DATA
     41 HTTP
      3 SMB
      1 SMTP
```

**Comment by ben-sec** [comment]
Thanks a lot!
