### ISSUE TITLE
FIX: selecting ETPRO rule set during installation

### ISSUE THREAD

**Issue by imanvp** [Security-Onion-Solutions/securityonion#7883]
Suricata rule update can't get new updates, when OINK Code was given during installation. I had to change it to ETOpen then get new rules and later change it to ETPro and then works.

**Comment by dougburks** [comment]
I tested a new installation supplying an ETPRO oinkcode during setup and it worked correctly for me:
![Screen Shot 2022-05-01 at 3 57 05 PM](https://user-images.githubusercontent.com/1659467/166221966-c2511a16-18fb-40f1-8fb5-e7da06d82767.png)

For your issue, it was most likely a typo in the oinkcode or a transient network issue.
