### ISSUE TITLE
FEATURE: Cases - Add ability to enable dynamic observable extraction

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#7972]
# Summary:
Automatically add observables to a case when a log record or network event is attached to the case.

# Terminology: 
- Case is a record in SOC where an analyst documents and collects information, in response to a possible intrusion event. Similar to a GitHub issue, but tailored to cybersecurity analysts.
- Observable is the analyst friendly term for something of interest that was observed while researching the case.
- Evidence is the internal SOC term for observable. Observable is used by some other Cybersecurity tools so we went with it on the UI.
- Evidence is composed of the Artifact interface, which is shared by other objects in the case system.

# Primary Objective:
Currently a user must manually add an observable to a case. They can do this by viewing an attached event, and clicking on one of the event fields to have it added as an observable. To eliminate some of these common observables, have the server automatically add typical observables, such as source/dest IPs, domains, etc.

# Additional Objective:
Allow admins to maintain a config setting that controls the list of field names that get automatically added as observables. This should already be implemented in the 2.4/dev branch, so all that is required is that the source list of field names be defined as a SOC config setting.

# Affected Code:
### [securityonion-soc](https://github.com/Security-Onion-Solutions/securityonion-soc) repository
- Go: `server/modules/elastic/elasticcasestore.go`, `CreateRelatedEvent()` method
- JS: `html/js/routes/case.js`, but may not need changes.
- HTML area: `html/index.html`, search for: `<v-tab-item value="evidence">`, but may not need changes.

**Comment by dougburks** [comment]
Tested escalating the following event:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/f9e4c393-7a66-47cc-9ad0-6c20181a6b5e)

Verified that the following observables were automatically extracted:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/41151f30-d0b3-4e49-8eb7-8a5521db51d9)
