### ISSUE TITLE
FEATURE: Add value from record in Hunt, etc as an observable to an existing or new case

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#7992]

**Comment by dougburks** [comment]
Tested and verified:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/247f0bfd-4bb7-4269-a03a-b44e18f7db50)
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/f772d1ed-317c-467b-a608-86ab1ab7711f)
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/23aab5d1-7fee-4685-80c5-5ab8fbff6c18)
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/99815eed-dcec-4f93-8843-c63d8d5eef16)
