### ISSUE TITLE
Feature request: Chinese translation

### ISSUE THREAD

**Issue by samuelxhu** [Security-Onion-Solutions/securityonion#8000]
I have not found any information on which languages are currently supported by Security onion, in particular i would like to participate the WebUI Chinese translation if it does not yet exist.

If possible, pls provide the necessary information on language translation. Thanks a lot

**Comment by dougburks** [comment]
> I have not found any information on which languages are currently supported by Security onion

https://docs.securityonion.net/en/2.3/faq.html#what-languages-are-supported
