### ISSUE TITLE
FEATURE: Add pivots for relational operators on numbers

### ISSUE THREAD

**Issue by phil1090** [Security-Onion-Solutions/securityonion#8024]
An analyst could use additional pivots on a number field in Hunt:
\>
<
maybe >= and <=

**Comment by coreyogburn** [comment]
Might also add a "Between" option

**Comment by dougburks** [comment]
Tested and verified:

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/55e10089-ec9f-4623-885e-1c6f7b2b73c0)

![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/587b45a0-c2c4-4b0f-9f3b-84eb059094d5)
