### ISSUE TITLE
FIX: Ensure operations on records with "*Missing" fields use correct search

### ISSUE THREAD

**Issue by phil1090** [Security-Onion-Solutions/securityonion#8025]
The Hunt pivot on a missing field (from a multi-field aggregation) does not produce a useful search. For example, if the network.protocol field displayed "*Missing", pivots on the field would use the search "network.protocol:"*Missing"". That search should be "-\_exists\_:network.protocol".

Also applies to Acknowledgments, and any other query that is executed against a search result record.

**Comment by dougburks** [comment]
Tested and verified:
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/366bc687-dfca-41f9-9223-05c2e96fc643)
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/742fef2c-c019-46bc-9e09-f2cb93aa8cb1)
![image](https://github.com/Security-Onion-Solutions/securityonion/assets/1659467/dd25d23d-e0cf-404d-aec3-54acbae69aa5)
