### ISSUE TITLE
Documentation / Script: Backup of Cases

### ISSUE THREAD

**Issue by gebhard73** [Security-Onion-Solutions/securityonion#8127]
Hi,

the backup documentation (and possibly the backup script) doesn't take into consideration the new Cases tool in ELK. This data doesn't belong to "big data" anymore, and backup / desaster recovery is critical and a must IMHO.

Can you please update the documentation (https://docs.securityonion.net/en/2.3/backups.html) and provide a procedure to backup the case data?

Thanks & Regards.

**Comment by dougburks** [comment]
I've updated the following:
https://docs.securityonion.net/en/2.3/backups.html
https://docs.securityonion.net/en/2.3/cases.html#data

**Comment by gebhard73** [comment]
Hi,

many thanks, this is really what I was looking for :-) Thanks,  @dougburks .

Cheers,
Gebhard
