### ISSUE TITLE
FIX: Improve default dashboards

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#8136]
- [x] Re-arrange charts on default dashboard
- [x] Add `groupby file.resp_mime_types` to HTTP dashboard

**Comment by jrmsq** [comment]
Thank you for the update.

How do I get data for the HTTP dashboard. I have gone as far back as weeks but I have nothing. How do I capture the HTTP/HTTPS traffic so I can see the same type of data you have on this sample dashboard.

**Comment by dougburks** [comment]
@jrmsq Please start a new discussion at https://securityonion.net/discuss
