### ISSUE TITLE
Missing FleetCTL link on docs site

### ISSUE THREAD

**Issue by isaacgolding** [Security-Onion-Solutions/securityonion#8172]
On the docs site:  https://docs.securityonion.net/en/2.3/fleet.html?highlight=fleetdm
The link for fleetctl documentation is 404 not found.

> fleetctl documentation can be found at https://github.com/fleetdm/fleet/blob/main/docs/01-Using-Fleet/02-fleetctl-CLI.md.

A google search revealed this link which might? be the replacement link?

https://fleetdm.com/docs/using-fleet/fleetctl-cli

**Comment by dougburks** [comment]
Fixed.
