### ISSUE TITLE
FEATURE: Provide ability to maximize view of a groupby chart or table

### ISSUE THREAD

**Issue by j-bernal** [Security-Onion-Solutions/securityonion#8176]
Please include an option to each panel in the Dashboards interface that will display the panel in full screen.

**Comment by dougburks** [comment]
Tested and verified:
![image](https://user-images.githubusercontent.com/1659467/178349838-755498dd-3486-4d90-b834-fdee2879974c.png)

![image](https://user-images.githubusercontent.com/1659467/178349920-1a8bd487-4291-4a15-9a05-2ea74b70c83d.png)
