### ISSUE TITLE
FEATURE: Remove disabled accounts from Assignee list Cases

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#8184]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/8161

<div type='discussions-op-text'>

<sup>Originally posted by **Hammer-Bear** June 21, 2022</sup>
Is it possible to remove disabled SOC accounts from the assignee list in cases, I know you can't/shouldnt delete SOC accounts which I'm fine with but the accounts still show under assignees in cases.</div>

**Comment by weslambert** [comment]
Thanks for the feedback! This will be addressed in a future release.

**Comment by dougburks** [comment]
Tested and verified:
![image](https://user-images.githubusercontent.com/1659467/178343533-41220509-d1c9-47a6-a8e4-398fce763ccc.png)
![image](https://user-images.githubusercontent.com/1659467/178343655-5f6091b9-13f0-4d60-92b6-512353a362cd.png)
![image](https://user-images.githubusercontent.com/1659467/178343723-d9c6ab2d-a41c-49d2-b497-104cd40c9168.png)
