### ISSUE TITLE
SOUP should not let you update to 140 or above unless you have updates to at least 110.

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#8239]
To go from ES 7 to ES 8 you need to at least be on 2.3.110 in order to update. If this protection was removed you will lose all of your data.

**Comment by dougburks** [comment]
Tested and verified:
![image](https://user-images.githubusercontent.com/1659467/178314717-23d13e0e-d8cc-4019-8a11-2edda1dd3f08.png)
