### ISSUE TITLE
FIX: Using so-firewall to list default port groups

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#8264]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/8259

<div type='discussions-op-text'>

<sup>Originally posted by **darth-drew** July  8, 2022</sup>
Discovered a traceback from 'so-firewall --defaultports listportgroups' after attempting an upgrade from 2.3.90 to 2.3.130 which went south in our distributed, airgapped, environment. Wondering if this is expected behavior.

</div>

**Comment by jertel** [comment]
This problem was introduced with the IDH node release, earlier this year.

**Comment by jertel** [comment]
Commit: https://github.com/Security-Onion-Solutions/securityonion/commit/a8e6b26406485fe4a856cf6f7979a68722987d71

**Comment by darth-drew** [comment]
Thanks jertel. I meant to include the idh-node reference. My apologies.

**Comment by dougburks** [comment]
Tested and verified:
![image](https://user-images.githubusercontent.com/1659467/178353130-5c9b2f0b-8a9a-4d69-9337-256b313cdceb.png)
