### ISSUE TITLE
ES Image - Automate ingest plugin var

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#828]

**Comment by TOoSmOotH** [comment]
@defensivedepth Can you provide more details on what we need to do?

**Comment by defensivedepth** [comment]
@TOoSmOotH If ES is updated, the ingest_community_id plugin version needs to match - ie https://github.com/Security-Onion-Solutions/securityonion-image/commit/d91fedb93901c7988df656256f4ef6f3caa8e6ef#diff-b59af65516473a3c4cb4943e7c29533f
