### ISSUE TITLE
FEATURE: Count time between events

### ISSUE THREAD

**Issue by gsprojectacc** [Security-Onion-Solutions/securityonion#8301]
Hi!
I would like to request you to add Elapsed filter plugin (https://www.elastic.co/guide/en/logstash/current/plugins-filters-elapsed.html#plugins-filters-elapsed) to Logstash container in order to count time between events.

From plugin description:
"The elapsed filter tracks a pair of start/end events and uses their timestamps to calculate the elapsed time between them.
The filter has been developed to track the execution time of processes and other long tasks."

**Comment by dougburks** [comment]
We've moved from Logstash parsing to Elasticsearch ingest parsing. You should be able to do something like this in Elasticsearch ingest:
https://alexmarquardt.com/2020/06/02/storing-ingest-time-and-calculating-ingest-lag-in-elasticsearch/
