### ISSUE TITLE
FEATURE: Add geoip.elastic.co to pre-flight check

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#8370]
Add `geoip.elastic.co` to the pre-flight check (GeoIP updates for Elasticsearch) to ensure that geoip updates are available to the end user.

**Comment by dougburks** [comment]
Looks like it should also check for `storage.googleapis.com`:
https://www.elastic.co/guide/en/elasticsearch/reference/master/geoip-processor.html#manage-geoip-database-updates

**Comment by palichx** [comment]
yep. correct url for download json
https://geoip.elastic.co/v1/database?elastic_geoip_service_tos=agree

**Comment by dougburks** [comment]
Changing geoip strategy, so this is no longer needed.
