### ISSUE TITLE
FIX: Elasticsearch geoip lookups fail for some users in Elastic 8

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#8373]

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/8453

**Comment by dougburks** [comment]
Tested and verified:
![image](https://user-images.githubusercontent.com/1659467/183160796-e2976ffb-96f7-463e-8e54-4037aad7dd44.png)

**Comment by dougburks** [comment]
Updated geoip documentation:
https://docs.securityonion.net/en/2.3/elasticsearch.html#geoip
