### ISSUE TITLE
FIX: Require a selection for Zeek/Suricata cores

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#8434]
_Originally posted by @xfaith in https://github.com/Security-Onion-Solutions/securityonion/discussions/8402_

Under the advance setup for the # of cores for Zeek/Suricata, if you dont "select" the number of cores, it lets you move on without a notification of no core selected.  I only noticed this when I  got the the review stage.  

I had highlighted # of cores for suricata (did not select it though), and hit enter, which brought me to the next step in the install.   I noticed when i checked the review that I had 0 core assigned to suricata.  

Might be good to have some sort of error check here that makes sure the user selects any of the available numbers.

**Comment by TOoSmOotH** [comment]
2.4 Setup removes the need for this.
