### ISSUE TITLE
Update TALOS rules snapshot version to 29200

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#8551]
#8541

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/8557

**Comment by dougburks** [comment]
Tested and verified:
![image](https://user-images.githubusercontent.com/1659467/185688726-28a46e58-8a2f-4f48-bd9b-5a3e1fd4611f.png)
