### ISSUE TITLE
FEATURE: Events table(s) for Windows Events matching default view

### ISSUE THREAD

**Issue by bryant-treacle** [Security-Onion-Solutions/securityonion#8591]
Add additional event table layouts for Windows event logs based on event datasets.

**Comment by dougburks** [comment]
Verified new table layouts:

![image](https://user-images.githubusercontent.com/1659467/191759068-65b6c532-9946-4555-af90-6d161d9153b3.png)

![image](https://user-images.githubusercontent.com/1659467/191759172-226aae62-700a-42ea-bffe-48b2da16308d.png)

![image](https://user-images.githubusercontent.com/1659467/191759267-4406fde8-61ee-4c6c-8b77-bb2c43e05c57.png)

![image](https://user-images.githubusercontent.com/1659467/191759391-22584d3d-7add-42e9-a6a8-1f2dddb04545.png)

![image](https://user-images.githubusercontent.com/1659467/191759484-48a3b167-28aa-4cf0-be87-a646897775cb.png)

![image](https://user-images.githubusercontent.com/1659467/191759632-5a56803a-3012-497c-94b1-be7f02321ed5.png)
