### ISSUE TITLE
Unify Zeek and Strelka File Data

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#881]
Change Zeek `files` dataset to be `file`

**Comment by weslambert** [comment]
[] Set the field value in zeek.files
[] Change Hunt queries
[] Check for other conflicts

**Comment by delbs27** [comment]
Is strelka installed in any of the releases of HH at the moment for me to try and provide any feedback on if its needed?

**Comment by delbs27** [comment]
for the latest install Hybrid Hunter Beta 1.4.1 - Beta 3 is it roughly documented somewhere where strelka hooks into zeek? are they in their own containers? or if i replay a random pcap with zeek SCP'd into HH it perform the file extraction and strelka module analysis across that pcap already?

**Comment by weslambert** [comment]
HI @delbs27, yes they run in their own containers.  Zeek outputs to `/nsm/zeek/extracted/complete`, then `so-strelka-filestream` picks up the files from there.  If Zeek extracts a file out of a network stream, it will be analyzed by Strelka.

**Comment by delbs27** [comment]
Thanks. Is tcpreplay the method to parse a pcap through zeek or invoking zeek directly with 'zeek -C - r test.pcap' as strelka is already integrated with zeek?
________________________________

**Comment by weslambert** [comment]
We don't currently include tcpreplay, but you could install it locally.  You may not be able to use `zeek -C -r test.pcap` as you expect, as it is running in a Docker container (may have to pass the command/file to Docker container in a different manner).  We are also working on a version of `so-import-pcap` for Security Onion 2.0 (still in progress).

**Comment by delbs27** [comment]
Oh thats useful.  Either im happy to help test out import-pcap or might install HH on physical and feed it from an actual TAP

________________________________

**Comment by weslambert** [comment]
Since so-import-pcap is still in progress, please using tcpreplay, a TAP, or mirror session, and let us know the results via the mailing list.  Thanks!
