### ISSUE TITLE
FIX: Re-running Setup should reset Grafana admin password

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#8949]
_Originally posted by @swannman in https://github.com/Security-Onion-Solutions/securityonion/discussions/8741#discussioncomment-3911496_

      Hi @dougburks, I was able to repro this issue:

1. `sudo bash so-setup-network`. Select `standalone` and accept the default settings.
2. `sudo salt-call pillar.get secrets`. This returns `grafana_admin: password1`. 
   - I verified that `password1` was correct for the `admin` user in Grafana.
4. `sudo bash so-setup-network` again. Select `standalone` and accept the default settings.
5. `sudo salt-call pillar.get secrets`. This returns `grafana_admin: password2`.
   - However, the `admin` user in Grafana was not updated and is still set to `password1`.

**Comment by dougburks** [comment]
Workaround:
https://github.com/Security-Onion-Solutions/securityonion/discussions/8741#discussioncomment-3657071

**Comment by TOoSmOotH** [comment]
Grafana does not exist. Influx supports the so model of sso.
