### ISSUE TITLE
FIX: Improve soup's local file modification logic

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#8972]
Currently, the `check_local_mods()` function in `soup` only checks to see if the diff of two files returns a `<` character at the beginning of the output. 

Ex. `grep -c "<"`

We should also check to see if a `>` character is returned.

We might be able to improve the logic using something like the following:

`grep -cE "^<|>"`

**Comment by dougburks** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/10178

**Comment by petiepooo** [comment]
The grep command above will not work as you intend, Wes.  Either include the carat in both expressions or use square brackets like my PR.

> $ cat test
aabb
bbaa
bbcc
ccbb
$ grep -E '^a|b' test
aabb
bbaa
bbcc
ccbb
$ grep -E '^[ab]' test
aabb
bbaa
bbcc
$ grep -E '^a|^b' test
aabb
bbaa
bbcc
$

**Comment by dougburks** [comment]
Tested with 3 different locally modified files (adding lines, removing lines, and modifying lines):
```
Potentially breaking changes found in the following files (check /opt/so/saltstack/default for original copy):
  /opt/so/saltstack/local/salt/soc/init.sls
  /opt/so/saltstack/local/salt/suricata/init.sls
  /opt/so/saltstack/local/salt/zeek/init.sls
```
