### ISSUE TITLE
FIX: Remove JA3er Analyzer

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#8984]
JA3er appears to no longer exist, so we should remove the `JA3er` analyzer.

We might consider looking into alternatives that provide a database for HTTP/TLS fingerprints.

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/pull/9002

**Comment by dougburks** [comment]
Also committed to 2.4:
https://github.com/Security-Onion-Solutions/securityonion/commit/8b0ea7104f7cfcbadc5df040e22b9ded718dd960

**Comment by dougburks** [comment]
Tested and verified that `ja3er` no longer exists in `/opt/so/saltstack/default/salt/sensoroni/files/analyzers/`:
```
ls /opt/so/saltstack/default/salt/sensoroni/files/analyzers/
build.sh  emailrep  greynoise  helpers.py  helpers_test.py  localfile  malwarehashregistry  otx  pulsedive  pytest.ini  README.md  spamhaus  urlhaus  urlscan  virustotal  whoislookup
```
