### ISSUE TITLE
UPGRADE: Strelka

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#8996]
The version of Strelka currently included in Security Onion includes speakeasy-emulator which has caused some AV false positives. The latest version of Strelka removes speakeasy-emulator:
https://github.com/target/strelka/commit/b14526ae4d56c187e3a6f15f3513b418d0942f2e

**Comment by weslambert** [comment]
New images have been built.

**Comment by dougburks** [comment]
Tested and verified that Strelka no longer includes the sample EXE.

**Comment by weslambert** [comment]
We have added the following YARA rules to Strelka's default ignore list, as they are causing YARA compilation errors:

- apt_apt27_hyperbro.yar
- apt_turla_gazer.yar
- gen_google_anomaly.yar
- gen_icon_anomalies.yar
- gen_nvidia_leaked_cert.yar
- gen_sign_anomalies.yar
- gen_susp_xor.yar
- gen_webshells_ext_vars.yar
