### ISSUE TITLE
ES is empty in Cluster mode

### ISSUE THREAD

**Issue by shipler** [Security-Onion-Solutions/securityonion#901]
I installed the HH1.4.0 cluster using the ISO file. My cluster contains - 1XMaster, 1XSensor and 1XSearch Node with local storage.

I had some issues to debug along the way since i didnt had DNS server (so i created one) and while inserting the master's hostname without the localdomain field the x509 certificate didn't matched, a new install with the right params solved it. 

But now after having all the cluster setup, my kibana is not showing any logs are saved and i'm not familiar with how to debug it.

![image](https://user-images.githubusercontent.com/67597270/86028817-0c466c00-ba3b-11ea-89e5-db65cb5d4546.png)

Grafana Logs for written documents - 
![image](https://user-images.githubusercontent.com/67597270/86028890-254f1d00-ba3b-11ea-9a1e-2a178483c7aa.png)

**Comment by TOoSmOotH** [comment]
This should be addressed with the latest release candidates
