### ISSUE TITLE
Check hashes for duplicates before sending to strelka

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#9034]
Currently all files extracted from the network are processed by strelka. If 1000 people download the same word doc it is processed by strelka 1000 times. This update will monitor files as they come in and keep a cache or "history" for the last 48 hours. That way a file is only analyzed once in a 48 hour period.

**Comment by dougburks** [comment]
Added to 2.4 as well:
https://github.com/Security-Onion-Solutions/securityonion/commit/bf31b593ed4a5ffba2ae203e19d515a3081da7ac

**Comment by dougburks** [comment]
Tested by replaying same pcap of a file transfer multiple times and verified that Strelka only processed once.
