### ISSUE TITLE
FIX: Hunt - Removing Filter with Pipe 

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#9092]
Hunt Query:

`osquery.Status: "Failing"  AND osquery.Failing_Context:"Current C: drive Bitlocker details: conversion_status 0 | protection_status: 0 | percentage_encrypted: 0"`

Removing the `osquery.Failing_Context` via clicking the `x` on the Bubble, leaves this, which throws an error.

`osquery.Status: "Failing"  | protection_status: 0 | percentage_encrypted: 0"`

![Bug](https://user-images.githubusercontent.com/954732/200633384-a2a96be0-8062-4a81-959c-41794f1690cc.gif)

**Comment by jertel** [comment]
Fixed by https://github.com/Security-Onion-Solutions/securityonion-soc/commit/534ed09799ac625989fbd33a47b83cf66038fac6.
