### ISSUE TITLE
upgrade iso to include bug 0015522 centOS

### ISSUE THREAD

**Issue by ingAntoN-71** [Security-Onion-Solutions/securityonion#9139]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/9133

<div type='discussions-op-text'>

<sup>Originally posted by **ingAntoN-71** November 13, 2022</sup>
Someone can upgrade iso  to include bug 0015522?
![Capture222](https://user-images.githubusercontent.com/118121467/201530838-f6cad351-fda9-467f-94c3-ad6d4aea9a9b.PNG)
</div>

this bug blocks at all a clean install into old servers.

**Comment by TOoSmOotH** [comment]
Duplicate.
