### ISSUE TITLE
UPGRADE: Zeek 5.0.4

### ISSUE THREAD

**Issue by TOoSmOotH** [Security-Onion-Solutions/securityonion#9167]
Upgrade Zeek to 5.0.4

**Comment by dougburks** [comment]
https://github.com/zeek/zeek/releases/tag/v5.0.4

**Comment by dougburks** [comment]
Tested and verified:
![image](https://user-images.githubusercontent.com/1659467/203545442-6735b501-360e-44b3-8b3e-30a89e2fefe9.png)
