### ISSUE TITLE
Feature Request: 'Back' button during setup/installation to easily correct setup configuration errors

### ISSUE THREAD

**Issue by faurkaurage** [Security-Onion-Solutions/securityonion#9362]
Security Onion is my SIEM of choice, I am amazed at how much the platform has evolved in the past year alone.

Request:
o During installation, SecOnion can be very unforgiven. The setup process gives you the ability to double check your configuration details that you inputted in during set up (i.e. ip address, dns search domain, etc) at the end of the setup. However, if you press 'cancel' you have to start all over again. 

Is it possible to add a 'back' or forward button to the screen during the setup/installation process? That way, if I mess up during one of the setup screens, I can just hit back and correct it without having to start over from scratch.

Noobs like me make mistakes 

Thanks so much for all the hard work @SecOnion Team. I'm sure bad guys hate yall

-Wallace

**Comment by dougburks** [comment]
We are simplifying Setup for Security Onion 2.4 so that hopefully you won't need a Back button.
