### ISSUE TITLE
FIX: Superuser permission check for so-elasticsearch-indices-list

### ISSUE THREAD

**Issue by Njinx** [Security-Onion-Solutions/securityonion#9461]
`so-elasticsearch-indices-list` fails if run without superuser permissions. The error messages spat out are vague and don't allude to the fact that superuser is required.

**Comment by dougburks** [comment]
`so-elasticsearch-indices-list` wasn't properly sourcing `so-common` and that's where the superuser check should take place. Resolved via the following PRs.

2.3:
https://github.com/Security-Onion-Solutions/securityonion/pull/9513

2.4:
https://github.com/Security-Onion-Solutions/securityonion/pull/9514

**Comment by dougburks** [comment]
Tested and verified:
```
doug@securityonion:~$ so-elasticsearch-indices-list 
This script must be run using sudo!
```
