### ISSUE TITLE
Test Coverage - Navigator /  Playbook / Fleet

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#972]
- [ ] Navigator - Loads with no errors when browsed to
- [ ] Navigator - Check that Playbook layer shows coverage for the active Play
- [x] Fleet - Login & run query against `manager` - confirm that results are returned
- [ ] WLB - W10 shipping logs to SO via WLB

**Comment by jertel** [comment]
@rwwiv and @defensivedepth This should be reviewed as well, with the new 2.3.30 test coverage.
