### ISSUE TITLE
UPGRADE: nginx 1.22.1

### ISSUE THREAD

**Issue by petiepooo** [Security-Onion-Solutions/securityonion#9742]
Please upgrade so-nginx image to use the latest stable version 1.22, first released 2022-05-24 and currently at v1.22.1.

Image nginx:1.20.2-alpine is no longer maintained or updated.

**Comment by dougburks** [comment]
Tested and verified:
```
sudo docker exec so-nginx /usr/sbin/nginx -v
nginx version: nginx/1.22.1
```
