### ISSUE TITLE
Change SOC Help link

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/securityonion#984]
In SOC, the Help link currently points to:
https://github.com/Security-Onion-Solutions/securityonion/wiki/FAQ

We should change that to:
https://docs.securityonion.net/en/2.0/

**Comment by dougburks** [comment]
Looks like that value is set here?
https://github.com/Security-Onion-Solutions/securityonion-soc/blob/dev/html/index.html#L169

**Comment by jertel** [comment]
Updated to new URL.
