### ISSUE TITLE
Intel E810 NIC's are not supported in ISO install.

### ISSUE THREAD

**Issue by CodeCommandoPants** [Security-Onion-Solutions/securityonion#9868]
**Into:**

When installing the SO ISO the included kernel is too old to support latest Intel E810 NIC's. It is possible to bypass this issue by installing SO as a package as described in the [documentation](https://docs.securityonion.net/en/2.3/installation.html#installation-on-ubuntu-or-centos) but this requires internet access as [described here](https://docs.securityonion.net/en/2.3/airgap.html#airgap) and therefor does not work for airgapped deployments.

To make the E810 NIC's work with SO you are going to need the Intel ice drivers, they are however only compiled for RHEL 7.9 that uses a newer kernel than the one included with SO (CentOS 7). You can compile the Intel ice drivers from source but none of the build tools or kernel headers are included with the SO ISO so they need to be individually installed which is very labor intensive.

When installing any other "modern" distro ([Ubuntu 20.04 as in the docs](https://docs.securityonion.net/en/2.3/installation.html#installation-on-ubuntu-or-centos)) on the same hardware the NIC's work out of the box.

**Possible fixes:**

- Include newly built DKMS ice drivers for the distro.
- Include development tools so that binary's can be built from source.
- Upgrade the kernel to a new version with newer drivers built in.
- Add documentation or support for installing SO as a package in airgapped mode.

**Hardware tested on:**
- Intel E810-CQDA2
- Intel E810-XXV

**Comment by TOoSmOotH** [comment]
So on the ISO the latest kernel should be in the Packages directory which then gets dropped into /nsm/repo during the kickstart process. You should be able to log in, cancel the setup, then apply the updated kernel via sudo rpm -Uvh. Does that seem like a useable workaround? 2.4 which uses Rocky 9 should support these nics from the jump.

**Comment by TOoSmOotH** [comment]
This is addressed in 2.4
