### ISSUE TITLE
Setup - Password req checks

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#988]
-Document requirements in docs
-Extend password req checks to local admin user creation & soremote user creation (all passwords created in setup should have the same pw check applied(?))
-Document in whiptail what the requirements are  - at a minimum, when the password req check fails

**Comment by jertel** [comment]
@rwwiv and @defensivedepth Please review the changes William made for 2.3.30 for password validation to see if this issue is satisfied.

**Comment by defensivedepth** [comment]
- Whiptail script doesn't specify what the requirements are
- soremote doesnt have the same requirements as SOC user 
- ISO local user doesnt have the same requirements as SOC user
