### ISSUE TITLE
UPGRADE: REDIS 6.2.11

### ISSUE THREAD

**Issue by defensivedepth** [Security-Onion-Solutions/securityonion#9980]
Rebuild base REDIS-alpine image, which will upgrade it to 6.2.11.

**Comment by dougburks** [comment]
Tested and verified.

Before:
![image](https://user-images.githubusercontent.com/1659467/227970258-57b30560-f18a-4f76-b607-5db5d4263730.png)

After:
![image](https://user-images.githubusercontent.com/1659467/227979584-8c6fc8a3-e0e1-4843-bc1d-695317d8ff97.png)
